### ISSUE TITLE
Another Driver does not support get/set network timeout for connections

### ISSUE THREAD

**Issue by obperryo** [brettwooldridge/HikariCP#1017]
#### Environment
```
HikariCP version: 2.7.2
JDK version     : 1.8.0_131-b11
Database        : MariaDB
Driver version  : mysql-connector-java-8.0.8-dmr-bin.jar
Driver version  : sqljdbc4.jar and tried sqljdbc42.jar
Driver version  : ifxjdbc.jar (4.10.8)
```
-----------------------------------------------------------------------------------------
I have six different pools and three different drivers, one using mysql, three using sqlserver and one using informix. They all work fine, but the sqlserver and informax are giving me the info message of driver does not support get/set network timeout for connections. From reading, I see this message is info, however I am not sure if I should attempt to resolve these or not. From reading, it seems like the Microsoft driver should, but I am not sure and wanted to get some input before going down that path. As for the Informix driver, per the link below, it looks to state that it is not supported... I'm just looking for an agreement on that to make sure I am not missing anything. I would appreciate any input/direction you may have on this.

Using jdbcURL only...

- jdbc:mysql://
Works fine...

- jdbc:sqlserver://
INFO com.zaxxer.hikari.pool.PoolBase - CC-Pool - Driver does not support get/set network timeout for connections. (null)
INFO com.zaxxer.hikari.pool.PoolBase - DBR-Pool - Driver does not support get/set network timeout for connections. (null)
INFO com.zaxxer.hikari.pool.PoolBase - TD-Pool - Driver does not support get/set network timeout for connections. (null)
INFO com.zaxxer.hikari.pool.PoolBase - JPOSLOG-Pool - Driver does not support get/set network timeout for connections. (null)

- Informix Driver: jdbc:informix-sqli://
INFO com.zaxxer.hikari.pool.PoolBase - INF-Pool - Driver does not support get/set network timeout for connections. (Method not supported : IfxSqliConnect.getNetworkTimeout())

It looks like informix does not support it if I am understanding this correctly:
https://www.ibm.com/support/knowledgecenter/en/SSEPGG_9.7.0/com.ibm.db2.luw.apdv.java.doc/src/tpc/imjcc_rjvjdapi.html#imjcc_rjvjdapi__d60801e409

Thanks for the help!

**Comment by brettwooldridge** [comment]
@obperryo I [fixed the SQL Server](https://github.com/Microsoft/mssql-jdbc/pull/253) driver some months back. :-)  That went out in [pre-]release [v6.1.7](https://github.com/Microsoft/mssql-jdbc/releases/tag/v6.1.7), and should be in stable release [v6.2.2](https://github.com/Microsoft/mssql-jdbc/releases/tag/v6.2.2).

Look at the tables for informix, it seems to indicate that support exists in the "IBM Data Server Driver for JDBC and SQLJ support" driver, which the top of page seems to indicate works for "DB2 for Linux, UNIX, and Windows, DB2 for z/OS®, or IBM Informix".  But because I'm not an informix user, I can't really say if that is true or not.
