### ISSUE TITLE
make the "metricsTracker" configurable 

### ISSUE THREAD

**Issue by yuanyangen** [brettwooldridge/HikariCP#1043]
#### Environment
```
HikariCP version: 2.4.9
```

hi :
   I just use HikariCP-2.4.9, and it's performance is very good, all of our project online use it. Thanks for this project again.

In my code, I user `getConnection()` to get a connection and use `recycle` to release it.
and I found  in my online java machines,  full gc happen about  every 6 hour (the heap size is 5G , and old gen is 3G), it's really too often , after some work, I found out it's the  "metricsTracker".
in function recycle below:  
```
final void recycle(final PoolEntry poolEntry)
   {
      metricsTracker.recordConnectionUsage(poolEntry);
      connectionBag.requite(poolEntry);
   }
```

the metricsTracker will record the usage of poolEntry every time I call recycle,  also means every request. that why the jvm trigger fullgc frequently. 

I know we can disable metricsTracker with `setMetricRegistry`,but I want  use other  work "metricsTracker" does. so, is it possible to make  `metricsTracker` configurable in 2.4.* ? 

thanks

**Comment by johnou** [comment]
@yuanyangen yep, using ```setMetricsTrackerFactory``` implement your own ```MetricsTrackerFactory``` which finally implements your own metricstracker (implementing the ```MetricsTracker``` interface).

**Comment by billoneil** [comment]
Two things

1. I don't think `2.4.9` is a valid version I don't see it anywhere in Maven or in the releases. Either way it's pretty old and you should upgrade.
2. I don't think you should be calling `recycle` directly at all. It's not even clear how you are since it's package private. You should just call `close` on the connections / statements. They are proxied under the hood and handle everything for you. Calling `close` will return it to the pool not actually close it.

**Comment by yuanyangen** [comment]
@johnou  thanks， you are right, I will try this. @billoneil  2.4.9 is a valid version but a little old, you can see it at tag list.  my description in is not so accurate . The truth is I called  the `close()` , and `close()` invoke `recycle()` .   

thanks for you warm heart guys . I figure out how to fix my problems.
