### ISSUE TITLE
Why is executeQuery marking the connection as dirty?

### ISSUE THREAD

**Issue by sternr** [brettwooldridge/HikariCP#1051]
#### Environment
```
HikariCP version: 2.6.1
JDK version     : 1.8.0_101
Database        : MySQL|Vertica
Driver version  : x.x.x
```
-----------------------------------------------------------------------------------------

Looking at the ProxyStatement code I see it marks the connection as dirt on every possible execution - even for query statements (e.g. event at ResultSet executeQuery(String sql)). why?

In certain isolation levels a read statement could dirty a connection (e.g. repeated read in mysql), BUT, the fact this can't be configured in any way means EVERY (used) connection would result in a rollback.
I would've hacked my way in, but all classes are final and nothing here is pluggable...
Why not add a config per datasource that would allow some means of control?

Thanks!

**Comment by 18814127356** [comment]
"EVERY (used) connection would result in a rollback"
I think this is not true, the isCommitStateDirty is set to false when you invoke Connection.commit(), and rollback will not be invoke when isCommitStateDirty is true

**Comment by sternr** [comment]
You are correct, I meant every connection that we don't explicitly call either rollback or commit would result in rolllback.

**Comment by brettwooldridge** [comment]
@sternr Databases are tricky things.  JDBC is a fairly high-level API and in some ways ignorant of the actual transaction boundaries of the underlying database.

Consider the following SQL (PostgreSQL):
```sql
UPDATE products SET price = price * 1.10
  WHERE price <= 99.99
  RETURNING name, price AS new_price;
```
Even though this is an ``UPDATE`` it returns columns (i.e. a ``ResultSet``).  This query, in JDBC-land, can be executed by either ``stmt.execute()`` *or* ``stmt.executeQuery()``.  JDBC is blissfully unaware that data was modified.

Moral of the story, if ``autoCommit=false`` you absolutely *must* call ``commit()`` or ``rollback()`` in order to ensure correctness.  On MySQL you *might* avoid a roundtrip to the database if ``useLocalTransactionState=true``, but I'm not sure of that.  Better to explicitly commit/rollback yourself; if you do not, HikariCP *will* rollback the transaction to ensure correctness.

**Comment by brettwooldridge** [comment]
@sternr Just one more example that occurred to me today:
```java
Statement stmt = conn.createStatement();
stmt.execute("INSERT INTO products(name, price) VALUES ('broom', 2.99);" +
             "SELECT * FROM products WHERE name='broom';" +
             "SELECT * FROM orders;");
// process products
ResultSet rs = stmt.getResultSet();
...
// process orders
if (stmt.getMoreResults()) {
   rs = stmt.getResultSet();
   ...
}
```
The point, as above, being that multiple statements can be executed in a single call, one of which may initiate a transaction (which HikariCP has no way of knowing about), and therefore HikariCP *must* assume that the commit state is dirty after *any* SQL execution.
