### ISSUE TITLE
Is it possible to use different app with single connection pool

### ISSUE THREAD

**Issue by kumar-cherry** [brettwooldridge/HikariCP#1054]
Hi,
We have multiple app run on tomcat we need to configure each tenant can use maximum number of connections. looks like ,
123.abc.com -----> Can use max 4 connections
456.abc.com ------> Can use max 6 connections

Currently each application taking configured connections, we need to control all application should use same connection pool, Any suggestions.

#### Environment
```
HikariCP version: x.x.x
JDK version     : 1.8.0_111
Database        : PostgreSQL
Driver version  : x.x.x
```
-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*

**Comment by brettwooldridge** [comment]
This is simple Tomcat configuration; define the DataSource in the Tomcat conf/context.xml rather than in each deployment.  Google “Tomcat shared DataSource”; I will not provide you complete configuration details here because I am not a Tomcat user.  You are also free to ask in the Google group as maybe another user is running a similar setup.
