### ISSUE TITLE
HikariProxyConnection cannot be cast to oracle.jdbc.OracleConnection when mapping TIMESTAMPTZ

### ISSUE THREAD

**Issue by george2515** [brettwooldridge/HikariCP#1172]
#### Environment
```
HikariCP version: 2.7.9 (tried with the latest as well)
JDK version     : 1.8.0_101
Database        : Oracle
Driver version  : 12.1.0.2.0
EclipseLink version: 2.7
SpringBoot version: 2.0.2.RELEASE 
```
Hi,
I am trying to configure a SpringBoot project to use Eclipselink instead of Hibernate and I would like to take advantage of HikariCP since it's now default pool in the spring boot stack. The problem arises when the native connection needs to be fetched in order to perform mapping of some Oracle specific type (TIMESTAMPTZ in an example I tested). Since HikariCP wraps connection into HikariProxyConnection, ojdbc7 fails to cast it as an OracleConnection. 

Has anyone had any experience with this type of setup? Is there a way to configure HikariCP to return platform specific connection types?

Thanks

**Comment by brettwooldridge** [comment]
The official way is to call ``Connection.unwrap(...)``.

**Comment by shashick** [comment]
For Spring Boot. Get an OracleDataSource

import java.sql.SQLException;
import javax.sql.DataSource;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import oracle.jdbc.pool.OracleDataSource;

@Configuration
public class DataSourceConfig
{
	@Value("${spring.datasource.username}")
	private String username;
	
	@Value("${spring.datasource.password}")
	private String password;
	
	@Value("${spring.datasource.url}")
	private String url;
	
	@Bean
	public DataSource dataSource() throws SQLException 
	{	  
		OracleDataSource dataSource = new OracleDataSource();
		dataSource.setUser(username);
		dataSource.setPassword(password);
		dataSource.setURL(url);
		dataSource.setImplicitCachingEnabled(true);
		dataSource.setFastConnectionFailoverEnabled(true);
		return dataSource;
	}
}

**Comment by stewartie4** [comment]
Old question but for anyone else wondering:
   
I ran into the same problem but found the common suggestions to be deficient in one area or another.

- **use `Connection.unwrap(..)`**: leads to the 'real' connection being closed outside of the connection pool and therefore eventual pool exhaustion 

- **use `OracleDataSource` instead of Hikari**: removes Hikari completely - presumably not something many want or can do 

- **override the 3rd party code:** this is hacky, difficult to maintain and only solves this single isolated issue

The problem arises because of mutually exclusive requirements - the ojdbc driver explicitly casts to an `OracleConnection` so we can't pass the `HikariConnection` managed object 
However we want the close method to return the connection to the pool, not actually close the connection which requires the `HikariConnection` managed object

My solution was to implement a delegating wrapper - something that could present as an `OracleConnection` when necessary but delegate to the original `HikariConnection` wrapper in important situations such as close();

Handily, `OracleConnectionWrapper` is an abstract class already provided by the driver so we can skip a lot of the boilerplate 

```
public class DelegatingOracleConnection extends OracleConnectionWrapper {

    private final Connection delegate;

    public DelegatingOracleConnection(Connection delegate){
        super(delegate.unwrap(OracleConnection.class));
        this.delegate = delegate;
    }
    
    @Override
    public void close(){
        delegate.close();
    }
}
```

```
Connection hikariConnection = getConnectionFromHikariPool(); //Hikari managed connection

//old
Connection oracleConnection = hikariConnection.unwrap(OracleConnection.class); // underlying "real" connection
oracleConnection.close(); // closes the actual connection - Hikari is not informed leading to inconsistent behaviour (connection closed, no connection available, pool exhausted etc.)

//new 
Connection wrappedOracleConnection = new DelegatingOracleConnection(hikariConnection);
assertTrue(wrappedOracleConnection instanceof OracleConnection) // wrapper can be cast successfully
wrappedOracleConnection.close(); //wrapper delegates to Hikari close - returns the connection to the pool

```

**Comment by prz3m3q** [comment]
I think the best solution is to use Oracle connetion pool insted of Hikari. I don't have any problems when i used UCP from Oracle.
