### ISSUE TITLE
Error monitoring a Tomcat HikariCP Data Source with Zabbix

### ISSUE THREAD

**Issue by fhperuchi** [brettwooldridge/HikariCP#1211]
#### Environment
```
HikariCP version: 3.1.0
JDK version     : 1.8.0_131
Database        : PostgreSQL
Driver version  : 42.1.4
```

Tomcat data source configuration (<TOMCAT_HOME>/conf/context.xml):
```
 <Resource
        name="jdbc/gd"
        auth="Container"
        type="javax.sql.DataSource"
        driverClassName="org.postgresql.Driver"
        minimumIdle="5"
        maximumPoolSize="95"
        connectionTimeout="1000"
        jdbcUrl="jdbc:postgresql://localhost:5432/mercedes_gd"
        dataSource.implicitCachingEnabled="true"
        dataSource.user="*****"
        dataSource.password="********"
        factory="com.zaxxer.hikari.HikariJNDIFactory"
        registerMbeans="true"
        poolName="nomeDoPool" />
```

Zabbix item key:
`jmx["Catalina:type=DataSource,context=/,host=localhost,class=javax.sql.DataSource,name=\"jdbc/gd\"",totalConnections]`

I'm getting this error monitoring a Tomcat HikariCP Data Source with Zabbix.

Error:
`Cannot find attribute totalConnections for HikariDataSource (nomeDoPool)`

Please, can you help me?

**Comment by zimmi** [comment]
I'm not very fluent in JMX and Zabbix, but I think you are trying to access the `totalConnections` property on the `HikariDataSource` directly, but it's on the `HikariPoolMXBean` instead.

You could try the following:

`jmx["Catalina:type=DataSource,context=/,host=localhost,class=javax.sql.DataSource,name=\"jdbc/gd\"",HikariPoolMXBean.TotalConnections]`

or change the selector to `com.zaxxer.hikari.HikariPoolMXBean` instead of `javax.sql.DataSource`.

**Comment by fhperuchi** [comment]
Hi @zimmi .

Now it's working. I did it this way:

`jmx["com.zaxxer.hikari:type=Pool (nomeDoPool)",TotalConnections]`

Thanks a lot.

**Comment by zimmi** [comment]
Awesome, thanks for posting your solution! :+1:
