### ISSUE TITLE
advisory

### ISSUE THREAD

**Issue by sds0917** [brettwooldridge/HikariCP#1217]
#### Environment
```
HikariCP version: 2.7.9
JDK version     : 1.8.0_162
Database        : MySQL
Driver version  : 5.1.46
```
## Is there no need to initialize the value of fastPathPool here?

![qq 20180808143058](https://user-images.githubusercontent.com/7779851/43820142-eca54856-9b17-11e8-80a9-eca6d1ac6083.png)

**Comment by brettwooldridge** [comment]
``fastPathPool`` is a ``final`` member, and can only be initialized in a constructor.  If the ``HikariDataSource`` is constructed with a ``HikariConfig``, it provides synchronization-free access to the pool.

If the ``HikariDataSource`` is constructed with the no-arg constructor, the pool must be lazily initialized in the ``getConnection()`` method, which requires synchronization overhead.

Thus, one is called ``fastPathPool`` and the other simply ``pool``.  ``fastPathPool`` cannot be set anywhere except for a constructor, because it is ``final``.

**Comment by sds0917** [comment]
I get it, thank.
