### ISSUE TITLE
Fairness testing and question

### ISSUE THREAD

**Issue by rivenhk** [brettwooldridge/HikariCP#1232]
#### Environment
```
HikariCP version: 3.2.0
JDK version     : 1.8.0_111
Database        : MySQL
Driver version  : my-sql-connector-5.1.27
CPU: i7-3770 @ 3.40GHz 4 Cores
```

https://github.com/rivenhk/benchmark-tools/blob/master/ConnectionPoolBenchmarkTest.java

I test the scenario when number of worker threads(32) > pool size(16), with both hikariCP and tomcat jdbc pool 9.0.11. The performance of hikariCP is obviously faster than tomcat on average, but when it comes to the 99.9 percentile, the performance goes down drastically. I suspect it is due to the fairness of hikariCP not working correctly. Any idea on that?

results:
testing datasource: hikaricp
warmup running..
trial 1 running..
trial 2 running..
trial 3 running..
trial 1: average: 0.577 min: 0.092 max: 179.494 99.9-percentile: 30.134 total_elapsed_time: 184527.197
trial 2: average: 0.583 min: 0.092 max: 154.749 99.9-percentile: 30.773 total_elapsed_time: 186612.471
trial 3: average: 0.583 min: 0.092 max: 103.570 99.9-percentile: 29.852 total_elapsed_time: 186496.204

testing datasource: tomcat-jdbc-pool
warmup running..
trial 1 running..
trial 2 running..
trial 3 running..
trial 1: average: 0.709 min: 0.096 max: 90.682 99.9-percentile: 5.930 total_elapsed_time: 226832.198
trial 2: average: 0.703 min: 0.102 max: 123.856 99.9-percentile: 9.030 total_elapsed_time: 225089.579
trial 3: average: 0.706 min: 0.098 max: 58.889 99.9-percentile: 4.993 total_elapsed_time: 226031.942

**Comment by brettwooldridge** [comment]
@rivenhk I concur with your suspicions.  It is likely fairness.  But I would say, it is not that "the fairness of HikariCP" is not working correctly, because HikariCP does not provide a hard fairness guarantee.

But I will also say that such unfairness anomalies typically surface in synthetic benchmarks, which tend to execute extremely tight-loops that hammer the pool.  The vast majority of real-world applications have some degree of business logic, however small, surrounding JDBC calls -- the presence of which, in concert with OS scheduling, generally eliminates "barging" behavior.

See *13.4* in [Java Concurrency In Practice](https://pdfs.semanticscholar.org/3650/4bc31d3b2c5c00e5bfee28ffc5d403cc8edd.pdf) for a decent writeup.

**Comment by rivenhk** [comment]
thanks for the feedback, i will take a look on the Java Concurrency in Practice.
