### ISSUE TITLE
Calling close() on connection still says INACTIVE connection in the Oracle DB while monitoring using SQL Developer Tool

### ISSUE THREAD

**Issue by mthirani** [brettwooldridge/HikariCP#1277]
#### Environment

HikariCP version: 2.7.5
JDK version     : 1.8.0_91
Database        : Oracle
Driver version  : 

-----------------------------------------------------------------------------------------
When opening the connection to the Oracle via hikari pool, I can see one session to Oracle DB via Oracle SQL Developer Tool but when I am done completing the execution of my query and called close() on connection, HikariCP says connection is closed.
![image](https://user-images.githubusercontent.com/13495519/48431347-5673c000-e726-11e8-8d4a-2894478c1625.png)

But while monitoring the session to the Oracle DB, I can see the connection is still INACTIVE (not completely gone) from there.
![image](https://user-images.githubusercontent.com/13495519/48431413-7c996000-e726-11e8-94bd-d82bcc55c4e7.png)

Below is the Account setting used for connection pool:
![image](https://user-images.githubusercontent.com/13495519/48431462-9f2b7900-e726-11e8-8049-ef07222f2204.png)

MaxIdle Time and Idle Connection Test Period is in minutes while Checkout Timeout is in ms.

I tried the test with the latest version and faced the same behavior.  

Please suggest and let me know if you need further information.

**Comment by billoneil** [comment]
That is the intended behavior of a connection pool. It keeps the connections open to the database and reuses them. The next time you get a connection it will give you the previously opened connection to the database saving the time of establishing a new connection.

**Comment by mthirani** [comment]
@billoneil  Yes but if I call close() on connection then it shouldn't..right? My understanding about close(): While calling the close() on any connection, it should release the object and terminate the session so if I call connect again then it establishes a new connection.

**Comment by billoneil** [comment]
Connections returned by the pool are wrapped in a proxy connection and when you call `close()` it just returns the connection to the pool keeping the underlying connection to the database open. See https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/ProxyConnection.java#L222

Connection pools generally work this way so you can continue to use standard idioms such as try with resources without taking any performance hits. Otherwise you would need to make all of your code be aware of the connection pool and manually choose when to actually close connections vs return them to the pool. By proxying the connection it happens transparently for you.

If you have a use case to actually close the connection I believe you can cast it to a `ProxyConnection` and call `unwrap()` then close the internal connection. The performance benefits of a connection pool come from keeping the connections open though.

**Comment by mthirani** [comment]
Ok, thanks @billoneil . We can close this issue. 
Thanks for clarification.
