### ISSUE TITLE
some doubts about ConcurrentBag#add(final T bagEntry)

### ISSUE THREAD

**Issue by gumandy** [brettwooldridge/HikariCP#1305]
```
// spin until a thread takes it or none are waiting
  while (waiters.get() > 0 && !handoffQueue.offer(bagEntry)) {
     yield();
  }
```
why not be same with ConcurrentBag#requite(final T bagEntry)
```
  for (int i = 0; waiters.get() > 0; i++) {
     if (bagEntry.getState() != STATE_NOT_IN_USE || handoffQueue.offer(bagEntry)) {
        return;
     }
     else if ((i & 0xff) == 0xff) {
        parkNanos(MICROSECONDS.toNanos(10));
     }
     else {
        yield();
     }
  }
```

**Comment by brettwooldridge** [comment]
It’s complicated.

In the case if requite(), there is the possibility that the connection (bag item) may change state while spinning — because a reference to it may exist in another thread’s ThreadLocal queue.  So the state must be checked while spinning.

This kind of state change cannot happen in the case of add(), because no other thread has a reference to the new item.

Regarding the yield() vs. yield()+parkNanos():
A yield()-only loop can peg a CPU core at 100%.  As there can be *many* threads in requite(), the occasional call to parkNanos() prevents CPU usage across many cores.  As connections are added by a single dedicated thread, we don’t mind spinning.

**Comment by gumandy** [comment]
but
...
add()  `sharedList.add(bagEntry);` first, then spin `handoffQueue.offer(bagEntry)`
borrow() traversal sharedList first, then `handoffQueue.poll()`
