### ISSUE TITLE
How do we decide on Maxpoolsize value in hikaricp

### ISSUE THREAD

**Issue by RaghavendraLhegde** [brettwooldridge/HikariCP#1314]
Im using hikaricp in our playframework project with mysql as db server, we have set max poolsize to 3. but i want to know how to decide upon size value.
How many requests can be sent per connection?

**Comment by billoneil** [comment]
The answer is "it depends" [About Pool Sizing](https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing) is a great start but it really depends how many api servers you have, how big is the database, what types of queries are you running?

A lot of very high throughput fast queries can be handled by a small number of database connections. If you have longer running SQL queries you may need a larger pool size. If you have a mixture of very fast queries and some slow ones you might want two different pools configured.

**Comment by RaghavendraLhegde** [comment]
Thank you for your reply.

And for a pool size of 1, how many concurrent connections are possible.

With Regards,
Raghavendra Hegde

**Comment by billoneil** [comment]
Again that depends on the queries you are running. A connection can only be used by a single thread at a time.

Some scenarios
* If your query takes 5ms you can handle ~200 queries per second with a single connection
* If the query takes 100ms you can handle ~10 queries per second with that single connection
* 5 servers with 1 connection each is pretty much the same as a single server with 5 connections as far as the database is concerned
* If you have a mixture of slow running queries and fast ones a few slow queries can lock up the pool which is why it is suggested to have separate pools for long-running queries.

There is no universal answer this is something you are going to have to test with your application. Every workload is different and requires tuning.

**Comment by brettwooldridge** [comment]
@billoneil Thanks for the answer, Bill.

**Comment by ShriMay26** [comment]
Can anyone help me to decide the best Hikari configuration for application which has 2 Springboot microservices hosted on AWS that uses RDS as database. We have configured ECS to have 10 task definitions (6 for 1 service and 4 for other). 

We are facing major performance issues (low response or 504 timeouts)  with following Hikari specific errors:

_o.h.engine.jdbc.spi.SqlExceptionHelper   : HikariPool-1 - Connection is not available, request timed out after 61939ms."
__
Connection leak detection triggered for org.mariadb.jdbc.MariaDbConnection@4bcb6258 on thread http-nio-8080-exec-27, stack trace follows"
at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128) ~[HikariCP-3.2.0.jar!/:na]
at com.zaxxer.hikari.HikariDataSource$$FastClassBySpringCGLIB$$eeb1ae86.invoke(<generated>) ~[HikariCP-3.2.0.jar!/:na]


could not execute statement; SQL [n/a]; nested exception is org.hibernate.PessimisticLockException: could not execute statement_

We have mix of long running and slow queries. How do I configure 2 pools for the above mentioned environment.

Please help.
