### ISSUE TITLE
HikariCp connection pool doesn't return the abandoned connections to pool and I am getting message too many clients connected to postgres, mysql, mssql

### ISSUE THREAD

**Issue by lusit** [brettwooldridge/HikariCP#1361]
#### Environment
```
HikariCP version: 3.3.1
JDK version     : 1.8.0_111
Database        : PostgreSQL|MySQL|...
Driver version  : x.x.x
```
<sup>⚠️ Please verify that your issue still occurs on the latest version of HikariCP before reporting. </sup>

-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*

I have an application where user can choose any type of database(relational) provide URL, username, password and create datasource connect to database, then run SELECT queries. To connect to databases I am using HikariCp for my connection pool(before I used DBCP2 as connection timeout didn't work I changed to HikariCp). Here is my configuration

```
HikariConfig config = new HikariConfig();       
config.setDriverClassName(StringUtils.trimToEmpty(driver));      
config.setJdbcUrl(StringUtils.trimToEmpty(url));
config.setUsername(username);
config.setPassword(password);       
config.setMaximumPoolSize(100);
config.setMinimumIdle(3);        
config.setConnectionTestQuery(validationQuery);      
config.setConnectionTimeout(TimeUnit.SECONDS.toMillis(jdbcTimeout)); 
config.setIdleTimeout(TimeUnit.MINUTES.toMillis(10));
config.setMaxLifetime(TimeUnit.MINUTES.toMillis(11)); 
config.addDataSourceProperty("closeMethod", "close"); 
HikariDataSource dataSource = new HikariDataSource(config);
Connection connection = dataSource.getConnection();    
``` 
jdbcTimeout- is configurable it can be 0 -30
 I close all connections (with autocloseable try (Connection connection = dataSource.getConnection(); ) {}).
Running tests which using application creates queries and runs those queries, after some time I am getting an error that too many clients.

What properties should I add to return abandoned connections to the pool?

**Comment by brettwooldridge** [comment]
@lusit If you are using try-with-resources, as stated above, there should be no abandoned connections.

But, for example, if your database only supports 100 connections (the default in PostgreSQL), and you set your maximum pool size to 100, you may encounter errors.  This is because closing (physical) connections and creating connections occur asynchronously.  It is possible for a connection that has reached max. lifetime or max. idle time, to be in the "close queue" (but not yet closed), while another thread is trying to create a new connection.  It is therefore possible for there to be small windows of time where 100 connections exist and yet the pool is trying to create another connection.

It is better not to set HikariCP's ``maximumPoolSize`` to the exact maximum database connection limit, but rather a few connections less (for example 95 instead of 100).

It is also possible that you may have some code that actually does not use try-with-resources and therefore has the possibility of a leak.  I recommend enabling the leakDetectionThreshold and watching your log to see if leaks are reported.  The logged message should pinpoint the location where the leak occurred.
