### ISSUE TITLE
Physical connection Exposure,may be closed by user

### ISSUE THREAD

**Issue by JoyceLikeRose** [brettwooldridge/HikariCP#1444]
I am studying HikariCP‘s code, and  doubt exist a defect at your pool. please read the following code 

```
Connection con = dataSource.getConnection();
javax.sql.DatabaseMetaData meta = con.getMetaData();
Connection con2 = meta.getConnection();
```

Usually   con2 == con ？ 

if don't add Proxy Wrapper on DatabaseMetaData, the physical connection will be exposure to user,      then the  pool connection closed by user directly. it is true?

**Comment by JoyceLikeRose** [comment]
validation code

```
Connection con=datasource.getConnection();
PreparedStatement st =con.prepareStatement(sql);
ResultSet re=st.executeQuery();
		
System.out.println("Statement equals:" +(re.getStatement()==st));
System.out.println("Connection equals:" +(st.getConnection()==con));
System.out.println("Meta Connection equals:" +(con.getMetaData().getConnection()==con));
```

if there are three true,meas pool has add proxy wrapper, some pool has match the result:
C3P0, Vibur, BeeCP.  The last test item is false for HikariCP and Druid and three was false for tomcat

**Comment by JoyceLikeRose** [comment]
I study four pool : Tomcat-jdbc, Druid, HikariCP, BeeCP with comparison way, and found the difference.   

I doubt  it is a defect,  Beg you to comfirm it is true ?

**Comment by lfbayer** [comment]
There is no way that the HikariCP data source is returning the implementation's connection implementation directly. I suspect that you are your `datasource` object is not actually a `HikariDataSource`.

But if you attach a test case that demonstrates this behavior, we can investigate.

**Comment by JoyceLikeRose** [comment]
```
public class TestConnection {
	
	public static void main(String[] args) throws Exception {
		HikariConfig config = new HikariConfig();
		config.setJdbcUrl("xxx");
		config.setUsername("xxx");
		config.setPassword("xxx");
		config.setDriverClassName("xxx");
		HikariDataSource datasource = new HikariDataSource(config);
		testCloseMetaConnection(datasource);
	}
	private static void testCloseMetaConnection(DataSource datasource) throws Exception {
		Connection con = datasource.getConnection(); // here con is a wrap connection.
		
		try {
			DatabaseMetaData meta = con.getMetaData();
			readDatabaseMetaData(meta, con);
		} finally {
			con.close(); 
                      // in fact,here return a closed connection to pool,
		      // because the physical connection has bee closed in
	              // method 'readDatabaseMetaData'.
	              // Maybe some Exception will be thrown here.
		}
	}
	private static void readDatabaseMetaData(DatabaseMetaData meta,Connection con) throws SQLException {
		Connection con2 = null;
		try {
			con2 = meta.getConnection();
			System.out.println("con:" + con);
			System.out.println("con2:" + con2);
			System.out.println("con2 is wrap connection?:" +(con2==con));
		} finally {
			con2.close();// if con2 is physical,how about close it directly here?
		}
	}
}
```

**Comment by JoyceLikeRose** [comment]
If contribute, and can gain money from the project? 
sorry to ask the  question.

**Comment by lfbayer** [comment]
You shouldn't be trying to close the same connection twice like that. And if the DatabaseMetaData gives you the raw connection object, then closing that connection will confuse hikaricp as the assumption is that you would never close that connection directly.

**Comment by lfbayer** [comment]
Also, a "test case" is something that anyone can run in order to reproduce an issue. What you've provided isn't runnable on its own.

No one gets paid to write HikariCP.

**Comment by JoyceLikeRose** [comment]
I want to say   "con2 is physical connection,  which maybe closed by developer direct. "

**Comment by lfbayer** [comment]
Yes, that is not a good idea. For symmetry, you should never close a connection that you don't create. Otherwise you end up with multiple calls to close. Also, since the physical connection knows nothing about HikariCP, HikariCP has no way of knowing that the connection was closed out from underneath it.

HikariCP is behaving correctly in this case. And I would say the answer is fix the code to not close the connection that was retrieved from the DatabaseMetaData.getConnection() call. There is no reason to call close there.

**Comment by brettwooldridge** [comment]
My kind of issue ... everybody's right!  (except me)

HikariCP will surely never give out a "raw" connection from the ``DataSource``.

I ran into this flavor of issue [before](https://github.com/brettwooldridge/HikariCP/issues/221).

For example, when you create a ``Statement`` from a ``Connection`` (proxy), you get a ``ProxyStatement``.  It just so happens that ``Statement`` has a method, ``getConnection()``, which returns the ``Connection`` that created it.  Earlier versions of HikariCP (circa 2015) did not intercept this method, and therefore the ``ProxyStatement`` simply called the *delegate* ``Statement``, which ended up returning the "raw" ``Connection`` instead of the ``ProxyConnection``.

This also cropped up again later, when I discovered that ``ResultSet`` has a ``getStatement()``, which returns a ``Statement`` that has a ``getConnection()``.  So *all of that* had to be intercepted -- so that ``ResultSet.getStatement()`` returns a proxy, and that statement's ``getConnection()`` returns a proxy connection.

I completely missed ``Connection.getDatabaseMetaData()``, which returns a ``DatabaseMetaData`` instance that (of course) has a ``getConnection()`` method.  Not only that, it has a million methods that return ``ResultSet``.  So, now I have updated the code to generate a ``HikariProxyDatabaseMetaData`` class that intercepts all of that nonsense.

``DatabaseMetadata`` implements ``Wrapper``, so of course an implementation of ``unwrap()`` is also provided.

I'll publish an update shortly.

@JoyceLikeRose might deserve some kind of award for the first *real* "issue" (I wouldn't say bug) in a long time. 🏆

**Comment by JoyceLikeRose** [comment]
java.sql.ResultSet.class
	
```
   /**
     * Retrieves the <code>Statement</code> object that produced this
     * <code>ResultSet</code> object.
     * If the result set was generated some other way, such as by a
     * <code>DatabaseMetaData</code> method, this method  may return
     * <code>null</code>.
     *
     * @return the <code>Statement</code> object that produced
     * this <code>ResultSet</code> object or <code>null</code>
     * if the result set was produced some other way
     * @exception SQLException if a database access error occurs
     * or this method is called on a closed result set
     * @since 1.2
    */
    Statement getStatement() throws SQLException;
```

```
Connection con=datasource.getConnection();
DatabaseMetaData meta=con.getMetaData();
ResultSet re= meta.getSchemas();
System.out.println(re.getStatement()==null); //<---here 
```
