### ISSUE TITLE
Support multi-threaded pool filling

### ISSUE THREAD

**Issue by Ni3Aphle** [brettwooldridge/HikariCP#1445]
#### Environment
```
HikariCP version: 3.2.0
JDK version     : 1.8.0_111
Database        : any
Driver version  : x.x.x
```

I read about Hikari having multi-threaded behavior when system property "_com.zaxxer.hikari.blockUntilFilled_" is set to true. 
But this multi-threaded behavior is restricted only to pool initialization phase.

What is the reason for not having this feature for pool lifetime?

If it can be provided for specific scenarios for limited time period, then why not add it for pool lifetime? This can be added as new configuration to _HikariConfig_. This will help the pool to always fill faster and hence serve connections without delays.
Same parallel behavior can be applied for closer threads so that connection eviction process is faster and new connections get added quickly.
Similar requirement was filed in #934 before #1287 , but it wasn't taken up.
This (#934) has been a long standing requirement on Hikari from our side as it is really impacting the performance of our application and hence the customers. We do not want to go to Apache DBCP as we found Hikari much better in all aspects.

Please refer the following issues stating the demand for parallel connection creation and closure:
1) Adder thread execution behaviour #934
2) HikariCP getConnection blocks when establishing new connection #1287

I would like this behavior to be added in Hikari as it is a generic requirement for any end user and will help improve the performance of any application using Hikari. This would really give Hikari an edge over other connection pools.

**Comment by lfbayer** [comment]
During the lifetime of a connection pool, only a small portion of the time is actually spent on creating connections. The whole purpose of a connection pool is to allow reuse of connections which by definition reduces the frequency that new connections will be created. HikariCP is specifically designed so that multiple connections don't need to get evicted at the same time. There are many parts of the design that attempt to ensure that there will always be connections available. But this will fail if the application isn't using those connections wisely.

Can you explain more about the use case where you need to close and recreate connections rather than continuing to use the connections that are already available in the connection pool? My gut feeling is that if there is any contention closing connections and creating new connections, then there is likely a suboptimal configuration. Maybe the system is trying to run way too many connections simultaneously.

If you can provide an example use case that justifies the need for parallel connection creation, then I think we can investigate it. But currently we haven't heard any specific use case that hasn't had a much better alternative solution.

In the case of #934, that is an edge case. No normal database takes longer than even a second, and it is likely that it would better worth everyone's time to fix that database to allow for faster connections than to alter HikariCP which likely could have a negative effect on the other 99% of use cases.

In the case of #1287, that particular use case was handled by allowing the parallel connection creation on startup, but subsequent connection creation should not be a performance problem, as the connections should not all be being evicted simultaneously.

As a final note, any effort to improve the performance of connection creation for these edge cases actually has the side effect of reducing the absolute maximum performance for all the other use cases. As was stated in #1287, adding support for parallel connection creation while the pool is running can greatly increase the complexity which in turn would increase the risk of race conditions and other bugs. It also would likely hurt the top end performance by introducing the need for locks. The current architecture works without needing locks in cases where other connection pools need them. This is one of the reasons why the benchmarking generally has HikariCP much faster than other connection pools.

And lastly, as this is an open source project and no one is making any money off of it (that I know of), there isn't much expectation of developers going and investigating this without having a personal motivation to do so. Since you are motivated, you would be in a perfect position to try to implement a fix. If you were to create a Pull Request that adds support for this functionality and can demonstrate that it has no negative effect on performance, as well as being not needlessly complicated, then we can easily consider merging it in.

**Comment by Ni3Aphle** [comment]
@lfbayer , databases do not take more than a second to create a connection. But in our case, we do not connect to databases or RDBMSs to be precise.
Our application is a middleware which connects to source and destination application systems and helps migrate the data. These applications can be like Teamcenter, SAP, WindChill, Primevera or any other application system for that matter.
The connection pool we are creating here is for the connections to these applications. These applications take time to connect to, which may vary from few seconds to around a minute as well. Teamcenter, for that matter, takes around 30 to 40 seconds to create a connection. For a connection pool with minimum idle set to 50 and maximum set to 100, it would take around 25 - 30 minutes to create those many minimum idle connections. 
After our applications starts up (start up completes within 2 minutes), hundreds of requests (bulk load) come to acquire connections. Since the pool will not be filled by this time, users experience a huge delay in getting response.
We cannot block the connection acquisition from the pool for this time either as blocking the pool would only create a bottleneck and reduce the performance drastically.

Another use case is for closing and recreating connections. Teamcenter connections are observed to consume more memory on each use. This leads to high memory consumption which slows down the execution. This is solved by closing and recreating the connection. Since many consumers may return the connections to the pool after use, lots of connections can be evicted simultaneously thus reducing the pool size. Parallel connection creation in this case again would help serve the subsequent requests without delay.

We are using HikariCP to solve our use cases. Our time is spent on addressing the needs of our application, hence it would be difficult for us to investigate and understand HikariCP enough to effectively contribute to it and carry out all test cases. Since you guys are totally familiar with Hikari, you can address the requirement more effectively and perfectly.

**Comment by lfbayer** [comment]
Seems like it would be worthwhile for Teamcenter to work out their issues? Even if HikariCP did support parallel connection creation, based on what you are saying, there would still a big performance hit on the Teamcenter side.

There have been other cases where there were bugs in drivers and users have asked for a workaround to be created within HikariCP. The answer has almost always been no. And in most cases the fix was actually easily added to the driver itself. Sometimes it just takes a pull request against the right system. This way all the various systems involved can improve, instead of just using one of the systems as the catch all to solve every problem.

Would it be viable to have the performance issues resolved in those other applications?

Out of curiosity, do all of those application systems really provide JDBC data sources? HikariCP is explicitly a JDBC connection pool, so it is a little surprising to hear it being used something that isn't an RDBMS.

**Comment by Ni3Aphle** [comment]
Teamcenter and other such systems are third party commercial applications. Getting any changes done on those would not be feasible.
These applications do not provide JDBC data sources. We adapt to those connections by wrapping them inside JDBC connections.

**Comment by lfbayer** [comment]
This is a use case outside of the scope of HikariCP, as HikariCP is specifically a JDBC connection pool.

It sounds like it might be better to use a generic object pool rather than something specifically designed for JDBC. This would also remove the need for wrapping connections in JDBC connections.

Something like [apache commons pool](https://commons.apache.org/proper/commons-pool/) might provide the flexibility that you are interested in.

**Comment by brettwooldridge** [comment]
@Ni3Aphle It sounds like you aren't using JDBC at all, and instead just using HikariCP as an object pool with faux JDBC connections that wrap some other third-party connection mechanism.

If this is what you are indeed doing, I recommend using [stormpot](https://github.com/chrisvest/stormpot) or [Apache Commons Pool](https://commons.apache.org/proper/commons-pool/).

You asked:
> If it can be provided for specific scenarios for limited time period, then why not add it for pool lifetime?

The answer is, the add connection path is using a lightweight locking mechanism with respect to borrowing from the pool that only allows a single-thread to add to the pool when borrow is possible.   This is for performance reasons, acknowledging that borrows are several orders of magnitude greater than adds -- and therefore should not be penalized by acquiring a heavyweight lock on every borrow just to avoid a rare collision with add.

Therefore, parallel add is *only available* during startup, when there is a guarantee that the pool is not yet available for borrow.

This is not something that is likely to change.

If you insist on using HikariCP when what you need is a generic object pool, at least don't abuse the pool by manually evicting connections.  Set a relatively short ``maxLifetime``, like 15 minutes, to avoid your memory issue.  HikariCP contains logic to spread out connection retirement to avoid mass extinctions in the pool.  In time, retirements and replacements will spread out roughly evenly over the maxLifetime period.  By manually evicting connections, you can actually *cause* mass extinctions in the pool, thereby crushing your performance given your high acquisition times (so don't do that).

The reporters of #934 and #1287 were both satisfied with the parallel fill behavior on startup.  Unless your connection lifetimes are exceedingly short -- approaching 2x acquisition time -- it is hard to imagine running into any performance issues if your settings are properly tuned.
