### ISSUE TITLE
Hikari connection pool creates two connection after start

### ISSUE THREAD

**Issue by hladush** [brettwooldridge/HikariCP#1454]
I use Hikary connection pool with following settings:
```
  HikariDataSource dataSource = new HikariDataSource();
        dataSource.setMinimumIdle(0);
        dataSource.setMaximumPoolSize(Integer.MAX_VALUE);
        dataSource.setJdbcUrl(jdbcConnectionString);
        dataSource.setConnectionTestQuery("select 1");
        dataSource.setIdleTimeout(TimeUnit.SECONDS.toMillis(60));
    dataSource.getConnection();
```
After getConnection() hikari try to get 2 connections to instance, but put in connection pool just one connection. How can I fix it? The hikari version is 3.4.0 jdbc hikaricp

**Comment by brettwooldridge** [comment]
@Pryanic When HikariCP starts, it creates a ``Connection`` in order to validate that connectivity to the database is available.

If ``minimumIdle`` is greater than zero, this "test connection" is just added to the pool.  If ``minimumIdle`` is zero, the "test connection" is closed, instead of adding to the pool.

However, what you are likely observing is that connection closure is asynchronous.  So the "test connection" is queued for closure.  Therefore, if you call ``getConnection()`` *immediately* there is likely a several millisecond overlap between the asynchronous creation of a new connection and the asynchronous closure of an old one.  During this window of time two connections may exist to the database.

If you cannot tolerate even a several millisecond condition in which two connections exist, the only workaround I can think of is to pass a ``ThreadFactory`` to ``dataSource.setThreadFactory()`` that always returns a single identical (not new) thread.  By doing so, you ensure that the connection adder thread and the connection closer thread are actually the same, and therefore those two actions can never overlap.

**Comment by hladush** [comment]
Thank you for your answer. I found easier  solution https://stackoverflow.com/questions/58027582/hikari-connection-pool-creates-two-connection-after-starting
