### ISSUE TITLE
The Performance score is true?

### ISSUE THREAD

**Issue by BrandonGabriel** [brettwooldridge/HikariCP#1478]
![1](https://user-images.githubusercontent.com/53826869/67769587-ba0a1100-fa8f-11e9-9fe4-55d5f8db55d3.png)

![2](https://user-images.githubusercontent.com/53826869/67769637-d017d180-fa8f-11e9-9feb-36a3846ae1cb.png)

Found one new CP in github 

https://github.com/Chris2018998/BeeCP

**Comment by brettwooldridge** [comment]
Tomcat, in its default configuration, is also faster than HikariCP.  Unfortunately, it is also unreliable due to ignoring basic principles of correctness.  The same goes for BeeCP.  See:

["My benchmark doesn't show a difference."](https://github.com/brettwooldridge/HikariCP/wiki/%22My-benchmark-doesn't-show-a-difference.%22)

And in particular: [What does correctness and reliability mean?](https://github.com/brettwooldridge/HikariCP/wiki/%22My-benchmark-doesn't-show-a-difference.%22#what-does-correctness-and-reliability-mean)

**Comment by BrandonGabriel** [comment]
Hi Brett,

Thanks for your reply, You have read its source code or run it with your benchmark?  About reliability, you have some test case to validate CP ?
