### ISSUE TITLE
connectionInitSql does not allow multiple statements

### ISSUE THREAD

**Issue by baumeister** [brettwooldridge/HikariCP#152]
connectionInitSql allows to set a single initialization statement. However, there is no way at the moment to issue more than one statements.

It would be good if several such statements could be configured, or for maximum flexibility if a callback can be set

This is how I do it in Bonecp:

```
config.setConnectionHook(new AbstractConnectionHook() {
    @Override
    public void onAcquire(ConnectionHandle con) {
                con.setReadOnly(false);
                con.setAutoCommit(false);
                if (type==TYPE.ORACLE) {
                    // -- make oracle non case sensitive
                    try (Statement s = con.createStatement()) {
                        s.addBatch("alter session set NLS_COMP=ANSI");
                        s.addBatch("alter session set NLS_SORT=BINARY_CI");
                        s.executeBatch();
                        con.commit();
                    }
                }
        }
    });
```

**Comment by Menthalion** [comment]
This can be done with the current connectionInitSql and adjusting your SQL.

With Microsoft SQL and most other databases, simply concatenate your SQL statements into one statement, seperated with the databases query separator (usually _;_).

With Oracle you need to go one further step by wrapping these queries in a _BEGIN;...;END_ block. However, since this also applies some level of transactionality, some queries that cannot be performed transactionally (like _ALTER SESSION_) need to be prepended with _EXECUTE IMMEDIATE_ followed by the quoted SQL.

Example

    BEGIN;
    EXECUTE IMMEDIATE q'ALTER SESSION SET NLS_SORT='BINARY'';
    EXECUTE IMMEDIATE q'ALTER SESSION SET NLS_COMP='LINGUISTIC'';
    END

**Comment by eidottermihi** [comment]
@Menthalion
thanks for sharing your solution, I had to alter your solution to support altering other NLS parameters (`nls_date_format` and `nls_timestamp_format`):

```
BEGIN 
DBMS_SESSION.SET_NLS('nls_date_format', '''YYYY-MM-DD HH24:MI:SS''');
DBMS_SESSION.SET_NLS('nls_timestamp_format', '''YYYY-MM-DD HH24:MI:SS'''); 
END;
```
