### ISSUE TITLE
HikariPool-2 - Connection com.mysql.jdbc.JDBC4Connection@74e83476 marked as broken because of SQLSTATE(08007), ErrorCode(0)

### ISSUE THREAD

**Issue by yuandaqianchengli** [brettwooldridge/HikariCP#1554]
Environment:
HikariCP version: 3.2.0
JDK version : 1.8
Database : MySQL/mycat
mysql-connect :5.1.47

事务提交后，30分钟才有结果返回，时间和maxLifetime配置一样长。

**Comment by yuandaqianchengli** [comment]
HikariCP 配置

    hikari:
      maximumPoolSize: 20
      minimumIdle: 20
      idleTimeout: 60000
      leakDetectionThreshold: 30000
      connectionTimeout: 60000
      maxLifetime: 1800000
      connectionTestQuery: SELECT 1

**Comment by brettwooldridge** [comment]
Very likely the MySQL server is closing connections at a shorter time interval.  Possibly because of configuration, or because of resource constraint management.  I recommend setting ``maxLifetime`` lower, for example, 600000ms.  You can try higher timeout values if the error disappears.

MySQL服务器可能会在较短的时间间隔内关闭连接。 可能由于配置或资源限制管理。 我建议将``maxLifetime`` 设置得较低一些，例如600000ms。 如果错误消失，则可以尝试更高的超时值。
