### ISSUE TITLE
BeeCP claims faster than HikariCP,it is true? 

### ISSUE THREAD

**Issue by HawksSam** [brettwooldridge/HikariCP#1559]
URL: http://www.github.com/Chris2018998/BeeCP

![20200315_I3_7100_HikariCP_Bech_Pict](https://user-images.githubusercontent.com/53827206/77248024-456b8500-6c71-11ea-8991-e07d4517423e.png)

**Comment by brettwooldridge** [comment]
@HawksSam Have fun with that.  It's dangerous.  Apache tomcat pool is *waaay* faster than HikariCP, because by default it has no safeguards at all.  If all you want is speed, but don't care about data corruption, go ahead and use BeeCP.

Search for HikariCP vs BeeCP, I have written comprehensive answers about why it cannot even be configured for proper safety, and is "faster" because it takes unsafe shortcuts (like Apache tomcat).  It also appears that BeeCP copies many approaches, if not actual code, from HikariCP without fully understanding what the purpose is.

I'm tired of all the spam from BeeCP users.  It feels like a Chinese government conspiracy.  First it was *druid* users for years, and now it's BeeCP.
