### ISSUE TITLE
Hikari connections are in waiting even before reaching to max connection pool size

### ISSUE THREAD

**Issue by BoinaRamesh** [brettwooldridge/HikariCP#1720]
@brettwooldridge Please can you help us with this issue?

Versions:

Hikari version - 3.4.1
PG driver - 42.2.8
Springboot - 2.2.1

We are seeing CP waiting state even though didn't reach to max connections. our max pool size is 20. Whenever we see this behavior impacting latencies with DB.

CP config:

    minimum-idle: 2
    maximum-pool-size: 20
    idle-timeout: 3m
    max-lifetime: 4m

During this point of time noticed with hikaricpConnectionsAcquire metric jumped to 1.5s.. After 5 mins everything changed to normal and didn't see any high latencies with DB responses.

07:52:21.537	HikariPool-1 - Before cleanup stats (total=3, active=0, idle=3, waiting=0)
07:52:42.224	HikariPool-1 - Closing connection org.postgresql.jdbc.PgConnection@c101418: (connection has passed maxLifetime)
07:52:51.539	HikariPool-1 - Before cleanup stats (total=2, active=0, idle=2, waiting=0)
07:52:51.540	HikariPool-1 - After cleanup  stats (total=2, active=0, idle=2, waiting=0)
07:53:21.540	HikariPool-1 - After cleanup  stats (total=2, active=0, idle=2, waiting=0)
07:53:21.540	HikariPool-1 - Before cleanup stats (total=2, active=0, idle=2, waiting=0)
07:53:51.540	HikariPool-1 - Before cleanup stats (total=2, active=0, idle=2, waiting=0)
07:53:51.540	HikariPool-1 - After cleanup  stats (total=2, active=0, idle=2, waiting=0)
07:53:57.981	HikariPool-1 - Closing connection org.postgresql.jdbc.PgConnection@72140b9a: (connection has passed maxLifetime)
07:53:58.901	HikariPool-1 - Closing connection org.postgresql.jdbc.PgConnection@7cd3ea70: (connection has passed maxLifetime)
07:54:03.046	HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@3216a72a
07:54:03.075	HikariPool-1 - After adding stats (total=2, active=1, idle=1, waiting=14)
07:54:03.075	HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@3cd15f18
07:54:03.101	HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@38eecc5a
07:54:03.101	HikariPool-1 - After adding stats (total=3, active=2, idle=1, waiting=11)
07:54:03.132	HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@7dec5523
07:54:03.177	HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@7a449243
07:54:03.208	HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@4c5b2b8c
07:54:21.540	HikariPool-1 - After cleanup  stats (total=6, active=0, idle=6, waiting=0)
07:54:21.540	HikariPool-1 - Before cleanup stats (total=6, active=0, idle=6, waiting=0)

**Comment by brettwooldridge** [comment]
@BoinaRamesh It looks to me like connection establishment/setup times are slow. Or at least they were at that time...

When things were flowing normally, we can see that setup times are very low -- roughly ~30ms establishment times:
```
07:54:03.046 HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@3216a72a
07:54:03.075 HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@3cd15f18
07:54:03.101 HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@38eecc5a
...
```
However, the delay before creating new connections after these two closures is exceedingly long:
```
07:53:57.981 HikariPool-1 - Closing connection org.postgresql.jdbc.PgConnection@72140b9a...
07:53:58.901 HikariPool-1 - Closing connection org.postgresql.jdbc.PgConnection@7cd3ea70...
07:54:03.046 HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@3216a72a
```
With the normal setup time of 30ms, a new connection should have been established almost immediately after *07:53:57.981*. And yet, no connection was established in the 1000ms (1 second) before the next closure. And finally, no connection is established for ~5 **more** seconds until *07:54:03.046*.

It appears that the database was unresponsive, due to CPU load, disk I/O, paging, or network issue (if remote). I do not think HikariCP has anything to do with this behavior. HikariCP will *immediately* nudge a thread to establish a new connection as soon as the close of the previous occurs. The fact that this did not occur for some number of seconds implies that the thread was simply waiting for the underlying ``getConnection()`` call to return.

You'll need to setup more monitors of the CPU and disk on both the application server and the DB server in order to correlate this kind of issue with other data from the environment.
