### ISSUE TITLE
Regression in v4.0.0 : Micrometer's gauges return no values for PoolStats

### ISSUE THREAD

**Issue by ghusta** [brettwooldridge/HikariCP#1726]
Since v4.0.0, Micrometer's gauge metrics return no value.

For example, when using a Prometheus implementation, we will get `NaN` : 

```
hikaricp_connections_active{application="my-demo-webapp",pool="HikariPool-1",} NaN
hikaricp_connections_idle{application="my-demo-webapp",pool="HikariPool-1",} NaN
```

I checked, there is no regression with `PrometheusMetricsTracker`, only with `MicrometerMetricsTracker`.

This kind of problem is referenced by the Micrometer documentation as : 
- [Why is my Gauge reporting NaN or disappearing?](https://micrometer.io/docs/concepts#_why_is_my_gauge_reporting_nan_or_disappearing)

At first sight, it seems to be related to this commit, which should be (partially) reverted in my opinion : https://github.com/brettwooldridge/HikariCP/commit/6e0f4a8d441bb293d61755baefc6544ab6efeec4

**Comment by brettwooldridge** [comment]
@ghusta ~~This issue with that commit being the problem is that, as my linter pointed out, that private ``poolStats`` member is referenced nowhere inside of the class. So, it's removal cannot be responsible for any behavioral change. Still investigating ... possibly related to the Prometheus related changes.~~

Nevermind, just read the referenced link. Apparently this was fixed some time ago with a contributed commit and message ``Maintain strong reference to PoolStats for Micrometer gauges (#1108)``. Would have been nice if the code had included a comment to that effect...

**Comment by brettwooldridge** [comment]
Fixed, release publishing in ~30min.

**Comment by ghusta** [comment]
OK, thanks !
