### ISSUE TITLE
[Question]connections to DBMS are not made after short time of network outage

### ISSUE THREAD

**Issue by SeanKimMel** [brettwooldridge/HikariCP#1736]
Hello there, I'm more likely asking for help with issues I'm having here.

the issue we're having is that every time we have any network issue,

our AP Server is not being able to make another connection to PostgreSQL without restart itself.
(log: Hikari-Pool-1 Connection is not available, request timed out after 30000ms)

Even at this moment, I'm not sure whether the issue is related to HikariCP or something else.

So I'm just asking that if anyone have experience something like  this, please share your case with me.

Thank you.

**Comment by Brokkonaut** [comment]
I have got the same problem with a mysql backend. After DDOS attacks to our server all plugins recover and create new connections to the mysql server, only luckperms (using HikariCP) is not able to get a connection any more and we have to restart the server.

**Comment by realmfoo** [comment]
I have the same problem with Oracle Database. But not all connections remained unusable after the network down. Some of them were recreated successfully. So I guess it depends on usage of the DataSource.

**Comment by stefan-g** [comment]
Hi, Same problem here. I'm not sure if the problem occurs because of a network or db issues but from time to time we got the same exception
org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.

The HikariPool is not able to recover by himself (only restart of the service does help). 
The stats of the pool are (total=0, active=0, idle=0, waiting=1). the config of the pool is:
leakDetectionThreshold 8000,  maxLifetime 110000,  maximumPoolSize 20 and  minimumIdle 10.
Where are all the connections? 

We are using Prostgresql with an additional PgPool. Some of our services are using the tomcat connection pool without any issue til now. It seems to be a problem with the hikari pool.

**Comment by TomasTokaMrazek** [comment]
One possible solution is to use socketTimeout dataSource parameter, might solve it. Unfortunately in our case, it didn't.

**Comment by brettwooldridge** [comment]
Try the [Rapid Recovery guide](https://github.com/brettwooldridge/HikariCP/wiki/Rapid-Recovery).
