### ISSUE TITLE
Deadlock with many simultaneous  connections creations 

### ISSUE THREAD

**Issue by mabdelazim** [brettwooldridge/HikariCP#1775]
We have a code which creates many connections in same time by multiply threads. The threads are then wait in synchronized block to create one more connection. We set the max connection with enough number to ensure the deadlock never happens however we observed the deadlock happens sometimes. Below is a simple code which produces the issue.

```
// Begin coding
volatile boolean doneSharedConnect = false;  // This is class variable.
final HikariConfig config = new HikariConfig();
/// setup config with connection parameters
config.setMinimumIdle(0;
config.setMaximumPoolSize(40); // This should be enough to prevent the deadlock
HikariDataSource hikariDataSource = new HikariDataSource(hikariConfig);
CompletableFuture<Void>[]  myThreads = new CompletableFuture[13];
       for (int i = 0; i < 13; ++i) { // we have only 13 threads and pool size is 40
            myThreads[i]..runAsync(() -> {
                         Connection threadConn =  hikariDataSource.getConnection(); // connection for every thread
                         if (!doneSharedConnection) {
                          synchronized(this) {
                              if(!doneSharedConnection) {// double check technique
                                   Connection sharedConn = hikariDataSource.getConnection(); // Deadlock happens here
                                   doneSharedConnection = true;
                                    sharedConn;.close();
                                }
                           }
                         }
                      threadConn.close();
          });
        }
// Wait for all threads
CompletableFuture.allOf(myThreads).join();

// End coding
```

It is interesting that we set max pool to 40 and thread count = 13 but still we get the dead lock.
**Env**:
**HiakriCP version:** 3.4.2
**Container:** AWS Lambda

Any help for this issue?

**Comment by brettwooldridge** [comment]
@mabdelazim I do not understand your code at all.  You declare an array of CompletableFutures ``myThreads`` with size 13, but you never assign any of the ``CompletableFuture`` objects returned by ``CompletableFuture.runAsync()`` to elements of that array. And then you try to do ``CompletableFuture.allOf(myThreads).join();``. It makes no sense, as all of the elements of ``myArray`` are not ``CompleteableFuture`` instances, they are still ``null``.

Furthermore, you have declared a *volatile* variable, ``doneSharedConnect``, *outside* of the lambda. This makes ``doneSharedConnect`` [effectively final](https://www.baeldung.com/java-effectively-final). So, I am suprised if that code even compiles, as the assignment of ``doneSharedConnection = true`` should fail to compile with the error: *"Local variable doneSharedConnect defined in an enclosing scope must be final or effectively final"*. You cannot assign a value to a final or *effectively final* field.

Can you provide actually working code?

For example, in your code above you create connections and assign them to ``threadConn``, but that is a local variable that never survives the block, and so will be garbage collected, and therefore never closed. Therefore, if you run this lambda more than once, then you will exhaust all _RDS_ connections, and the code will **block** (not deadlock). It is not until RDS times out the connections that you will be able to connect again. This could take a long time, minutes or hours.

None of these issues have anything to do with HikariCP.  The line that you indicate as a "deadlock" is merely a call that is blocking due to the inability to create new connections. Because you exhausted them in prior runs.

**Comment by mabdelazim** [comment]
@brettwooldridge Sorry for providing incomplete code in the beginning.  In our application we use HikraiCP integrated with [JOOQ](https://www.jooq.org/) library and the code is spanned among different functions and classes. I wanted here to simplify and abstract the code under concern to make it is easier for HikraiCp contributors to help me. I fixed the code now by handling your comments.
I appreciate you open the issue again unless you are highly confident it is not HikrariCP.issue.
My replay to your comments are:

- doneSharedConnection is class member so it compiles and can be altered.
- I assigned the myThreads objects correctly now.
- I closed the connections after usage now.


Please also note in our usage with JOOQ, the connection is closed automatically in every Jooq statement execution
