### ISSUE TITLE
Communications link failure - 2+ hours after DB crashed

### ISSUE THREAD

**Issue by tamasssimon** [brettwooldridge/HikariCP#1777]
Hi - 

Using Hikari 2.7.9.

-  ConnectionTimeout | 10000 
-  IdleTimeout | 300000   
-  LeakDetectionThreshold | 10000 
-  MaxLifetime | 1800000 
-  MaximumPoolSize | 30 
-  MinimumIdle | 3 
-  ValidationTimeout | 5000

Running into an issue whereas when/if the database crashes/fails over, connections don't fail, but hold on for an unexplainable amount of time.   When we realized it, we isolated the server with the hanging connection, and waited until it threw an error.

org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method '[method]' on target class [class] failed; nested exception is org.springframework.dao.RecoverableDataAccessException: PreparedStatementCallback; SQL [sql]; Communications link failure

The last packet successfully received from the server was 7,893,852 milliseconds ago.  The last packet sent successfully to the server was 7,893,852 milliseconds ago.; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

That's ~131 minutes.  There is obviously nothing configured with that kind of timeout.    The database was down, gone. For 131 minutes.

What was going on here, why didn't the failure happen sooner?

We have seen this before when we failover databases, and it just does not add up.  We'd obviously like to shorten this period significantly, so the application can recover.

Any thoughts?

Thanks!

**Comment by Chris2018998** [comment]
You are welcome to try BeeCP.

**Comment by lfbayer** [comment]
This is very unlikely to be caused by anything in HikariCP. It could be that you have a quartz job that hasn't run in 131 minutes and during that time the connection was lost. But since nothing tried to use the connection in that time there was no chance for a failure to be detected.

If I had to guess, I would say it looks like your job is actually holding on to an old connection rather than getting a new connection from the connection pool when it needs it. I would expect the isValid check to actually detect the problem when getConnection is called. Since this doesn't appear to be the case, that would make it seem as though you must be still holding on to an old connection.

**Comment by brettwooldridge** [comment]
@tamasssimon Please read about [Rapid Recovery](https://github.com/brettwooldridge/HikariCP/wiki/Rapid-Recovery).  It documents the exact 2+ hour timeout, and how to avoid it.  Hint: it's an OS setting.

**Comment by lfbayer** [comment]
Or I could be wrong, since generally @brettwooldridge knows what he is talking about.

**Comment by tamasssimon** [comment]
Thank you.  I will read up on it, and get back with any followup questions.  After I submitted my post, I had also come to realize this is unlikely to be a hikari issue.
