### ISSUE TITLE
Hikari Pool not using idle connection and creates new one

### ISSUE THREAD

**Issue by aman41907** [brettwooldridge/HikariCP#1797]
Hi
I have observed that in my spring boot java application, which is using hikari pool, that when new request comes idle connections are not reused. Upon receiving a new request a new connection is created.I am using following

Hikari:3.41
Spring Boot:2.2.2.RELEASE
Java:1.8
AWS RDS PostgreSQL 12.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11), 64-bit

Hikari Config
--------------
    hikari:
      minimumIdle: 10
      maximumPoolSize: 100
      connectionTestQuery: "SELECT 1"

Please help to solve it 

Thanks

**Comment by aman41907** [comment]
Hi
I have observed that in my spring boot java application, which is using hikari pool, that when new request comes idle connections are not reused. Upon receiving a new request a new connection is created.I am using following

Hikari:3.41
Spring Boot:2.2.2.RELEASE
Java:1.8
AWS RDS PostgreSQL 12.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11), 64-bit

Hikari Config
hikari:
  minimumIdle: 10
  maximumPoolSize: 100
  connectionTestQuery: "SELECT 1"

Please help to solve it

**Comment by brettwooldridge** [comment]
New connections *will* be created, that is by design. If ``minimumIdle=10`` and a request comes in, then it consumes a pool connection. Now the pool has ``9`` idle connections, not ``10`` as required by ``minimumIdle``. Therefore, a connection is added (asynchronously). ``minimumIdle`` means: *ensure minimumIdle connections are always available for use*.
