### ISSUE TITLE
What is the recommended value for connectionTimeout??

### ISSUE THREAD

**Issue by MithilCoder** [brettwooldridge/HikariCP#1933]

**Comment by MithilCoder** [comment]
@brettwooldridge

**Comment by lfbayer** [comment]
Your connectionTimeout property should be longer than the maximum amount of time you would normally expect to need to wait before a connection is returned to the pool. In ideal circumstances, in both large and small systems, the vast majority of all requests to get a new connection shouldn't need to wait at all. If you have threads waiting to get a connection, then there is likely a design issue somewhere in your application.

Generally you shouldn't have to update this value unless you are having contention issues where all the connections in your pool are being used and you have pending threads waiting for a new connection. My gut instinct would say that if you have this question you likely actually have some queries that are running too long. Or you have threads that hold on to connections longer than they should. If holding those connections for a long time is expected, then I would expect you to have the context yourself in order to compute an appropriate connectionTimeout for your needs.

This ticket is actually better suited to stackoverflow, as the github issue tracker is meant to track issues. Also, the nature of this particular ticket appears low-effort (only a title and no description) and a little passive aggressive (using two question marks is a bit aggressive). Given that any help you will get for questions on github will be provided by people who are not getting paid to do so, you should treat their time with respect, and at least put in as much effort into opening the ticket as you would expect is required in order to answer the ticket.

**Comment by MithilCoder** [comment]
Thanks for answering my query.
Whether you are getting paid or not, I respect everyone's time. I don't think query required description so I didn't provide.
