### ISSUE TITLE
Thread starvation or clock leap detected

### ISSUE THREAD

**Issue by leopardorossi** [brettwooldridge/HikariCP#1951]
Dear all,
in a Java project I'm working on I'm using `HikariCP 3.4.0` as a db pool. In my application logs I started to see the following warning message:

`[HikariPool-1 housekeeper] WARN com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=47s466ms577µs431ns)`

My application has to finish within a certain time frame and in normal conditions it ends in 20 minutes. Sometimes, in particular when the error above appears in the log, it slows down. The application, to complete its logic, uses a pool of 32 threads,

Given this context, I have some questions about the warning:

- What is the meaning of this warning?
- How can I face this warning in order to solve it?
- Can the threads my application internally uses, interfere with Hikari one?
- Can this warning affect the performance of my application?

I saw that there are other issues related to this problem, but none of them answered the questions above.

Thank you in advance for your support!

**Comment by lfbayer** [comment]
That message means exactly one thing, that HikariCP did not receive any CPU time for 47 seconds.

Two likely causes would be:
1. The system was in sleep mode thus no processes were being executed.
2. Other threads/processes on the system were too busy and the HikariCP threads didn't get any CPU time.

This is absolutely not a bug in HikariCP.

When you say that the system slows down when that warning is in the log, I believe you have the causation backwards. That warning is shown BECAUSE the system was slow. It is not the cause of the slowness.

**Comment by wangwenzhao1** [comment]
2025-01-23 09:20:45.004[ WARN] 122093 [] [HikariPool-1 housekeeper:229294143] [com.zaxxer.hikari.pool.HikariPool.?:?] HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=32m10s221ms838µs213ns).
2025-01-23 09:26:56.732[ WARN] 122093 [e8df73a25e59414cbce13469d4f583eb] [XNIO-2 task-93:229665871] [c.g.z.boot.handler.DefaultGlobalExceptionHandler.?:?] Exception:
org.springframework.transaction.CannotCreateTransactionException: Could not open JDBC Connection for transaction; nested exception is java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 970095ms.
