### ISSUE TITLE
 Connection marked as broken because of SQLSTATE(08S01) , ErrorCode(0)

### ISSUE THREAD

**Issue by sudha1124** [brettwooldridge/HikariCP#1986]
@brettwooldridge . Please help us with  this issue. I have been struggling on this from past few weeks. Tried everything from forums.

we are facing below error every couple of errors (10-12 hours) consistently everyday. I have enabled leakDetection and do not see any leaks.
 Connection marked as broken because of SQLSTATE(08S01) , ErrorCode(0)

Hikaricp: 4.0.3
Aurora MySql : 5.7.12
mysql-connector-java : 8.0.29
JDK: 11

The last packet successfully received from the server was 211 milliseconds ago. The last packet sent successfully to the server was 211 milliseconds ago

minimum-idle:10
maximum-pool-size:50
idle-timeout: 30000ms ( 30 secs)
leakDetectionThreshold : 120000ms ( 2 mins)
keepAliveTime: 60000ms ( 1 min, tried 10 mins too) 
maxLifeTime : default ( 30 mins ) 

MySQL timeouts
wait_timeout: 28800secs ( 8hrs) 
interactive_timeout:  28800secs ( 8hrs) 
connect_timeout: 10 secs
bind-address: *
skip-networking: OFF

ConnectionString : sslMode=DISABLED&serverTimezone=UTC&useLegacyDateTimeCode=false&autoConnect=true&useUnicode=true&characterEncoding=UTF-8&tcpKeepAlive=true

**Comment by casolxia** [comment]
If there is additional network infrastructure, such as load-balancers, between your application and the database, they may be imposing a separate (shorter) timeout. The pool maxLifetime should be one minute shorter than the shortest timeout in the infrastructure path.

**Comment by parsons-smith** [comment]
@brettwooldridge We have encountered similar problem. We configue MAX_EXECUTION_TIME so that long running queries would be killed. When a query is killed, the connection is broken and could not been used. However, the server returns "SQL state [HY000]; error code [1105] ", so the connection is not recognized as broken and still remain in the pool. It will cause "Communications link failure, marked as broken because of SQLSTATE(08S01), ErrorCode(0)" when another new request uses this connection next time.
![CSdoyRC8sB](https://user-images.githubusercontent.com/12904475/215699488-fd64e516-0408-4bd5-acec-b498c1d688f7.jpg)
![r7jI2A1OWe](https://user-images.githubusercontent.com/12904475/215699524-d8d72500-0fca-4fd8-a3ab-5af78a89f9c3.jpg)

**Comment by casolxia** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，邮件已收到了了了了

**Comment by brettwooldridge** [comment]
@parsons-smith I have added error code 1105 to the list of known error codes. I will make a release in the next few days.

**Comment by brettwooldridge** [comment]
@sudha1124 Also, please remove ``tcpKeepAlive=true`` and ``autoConnect=true`` from the connection parameters, these can potentially adversely impact pool management. If you need keep-alive behavior, consider setting ``keepaliveTime`` to some reasonable value.

**Comment by mokamoto12** [comment]
@brettwooldridge There seem to be several similar issues here (https://github.com/brettwooldridge/HikariCP/issues/1960, https://github.com/brettwooldridge/HikariCP/issues/2015). I think it would be nice if users could handle errors freely. I am trying to address the issue here https://github.com/brettwooldridge/HikariCP/pull/2031. If you don't mind, please let me know what I can do to merge this one. Thank you.

**Comment by yakirgb** [comment]
@brettwooldridge version 5.0.2 released ?

**Comment by casolxia** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，邮件已收到了了了了
