### ISSUE TITLE
Error in documentation?

### ISSUE THREAD

**Issue by paulc4** [brettwooldridge/HikariCP#2018]
There is a section in the README explaining why HikariCP does not have a statement cache.

But the first Initialization example immediately below shows these configuration properties:

```java
config.addDataSourceProperty("cachePrepStmts", "true");
config.addDataSourceProperty("prepStmtCacheSize", "250");
config.addDataSourceProperty("prepStmtCacheSqlLimit", "2048");
```

An error or am I confused?

**Comment by lfbayer** [comment]
DataSource properties are not read by hikariCP itself but rather just passed on to the DataSource. So that example shows setting properties for a DataSource implementation that happens to support a prepared statement cache. HikariCP does not prevent a DataSource/Driver implementation from supporting features like prepared statement caches.
