### ISSUE TITLE
Just checking to see if the project is actively being maintained

### ISSUE THREAD

**Issue by FollowSteph** [brettwooldridge/HikariCP#2105]
This may be a mature project and barely needs any updating but I ask because the last commit seems to be from Feb and there doesn't seem to be any activity in terms of responses to Issues. In other words it would just be nice to see if anyone is monitoring the project. Thank you.

**Comment by lfbayer** [comment]
I read every ticket and comment, but the vast majority of them are errors that indicate an issue in the user's code rather than a HikariCP issue. At this point it would futile to try to answer all of them. A few years ago Brett told me he thought it might make sense to actually disable the GitHub issues for the project. 99% of the issues reported should really be on stackoverflow instead of here. And anything else should really just be a pull request with new unit tests instead of just a ticket. 

There have been a few Pull Requests that I would like to merge, but there is a risk with every change. Since HikariCP is potentially the most used connection pool for Java now, it is probably a good thing to not touch it as the impact of any bug could be pretty big. 

There are one or two legitimate bugs that people have reported but they are for cases that probably only impact less than 0.1% of users. Neither Brett nor myself are likely to just go and fix one of those bugs ourselves, so there would need to be a pull request submitted that looks rock solid and includes an explanation that demonstrates enough knowledge and understanding that we could trust it.

**Comment by FollowSteph** [comment]
Thank you for responding. That's what I suspected but it's great to have it confirmed. You are correct most issues here are questions and could be posted on Stackoverflow. I actually did that myself initially and since I didn't get anyone to respond I then tried here and similarly got no response so I was a bit concerned, which is why I posted this question.

It's great to hear how highly used the HikariCP is, I've been testing it recently and it's quite impressive. You guys have done great work. My hate goes off to you guys. Some projects are mature and need very little maintenance. 

That being said I would recommend keeping the issues open but maybe having an auto-responder (or even someone manually doing it since it looks to be about 10 new issue a month) that essentially says it's more of a question than an issue and should be posted on SO rather than leave them open which makes it look like the project is innacgive. This could also be added in the text as part of the posting form for an issue, to minimize even this. In essence it would keep the issue list clean and it would show activity. I would recommend this over both not responding (which feels like the project is not active) or closing issues entirely because at least there is a venue in case there is a real issue. Plus again it shows activity which can be challenging from a more complete and/or mature project. Less issues is not a bad thing for such a project, and in fact can be a good thing.

Again my kudos to you guys, you've done an amazing job. It's very impressive. Here's to many more years.

**Comment by lfbayer** [comment]
I can't take much credit for this project (other than being moral support for Brett).

Thanks for your recommendations. Your post motivated me to try to be a little more active. My first goal is now to perform a release with the changes that are already committed. Unfortunately I'm struggling to get the maven release build working. I just need to put the time in to work through the problems.

For no reason whatever I'd like to leave a link to a blog post a read many years ago that stuck with me: https://steveklabnik.com/writing/how-to-be-an-open-source-gardener

I'm marking this ticket as closed.
