### ISSUE TITLE
keepaliveTime for indifinte connections (maxLifetime=0)

### ISSUE THREAD

**Issue by budzow** [brettwooldridge/HikariCP#2107]
I understand it is not recommended, but let's assume `maxLifetime` is set to 0 (infinite connection lifetime). I wanted to understand if in that case I can set `keepaliveTime` > 0 and if it will be effective? The documentation for `keepaliveTime` says:
> This value must be less than the `maxLifetime` value.

but do I understand correctly that connections with  `maxLifetime=0` will be the exception to this  and `keepaliveTime` > 0 will be effective for them?

**Comment by lfbayer** [comment]
[The code](https://github.com/brettwooldridge/HikariCP/blob/8c1a7c29341348b3ea71ccfe35d4858b378160e2/src/main/java/com/zaxxer/hikari/HikariConfig.java#L1056) that does this validation skips the comparison if maxLifetime is zero. I see the wording in the javadoc is ambiguous, but since 0 represents infinity, then any `keepaliveTime` would be less than infinity.
