### ISSUE TITLE
Connection-timeout not working intermittently

### ISSUE THREAD

**Issue by sagarsitap596** [brettwooldridge/HikariCP#2109]
I have set Connection-timout to 11000 (11 seconds).

In logs I could see both 
"@timestamp":"2023-09-15T03:04:33.893Z","@version":"1","message":"HikariPool-1 - Connection is not available, request timed out after 11000ms."

"@timestamp":"2023-09-15T03:04:51.064Z","@version":"1","message":"HikariPool-1 - Connection is not available, request timed out after 29092ms."

What could be the reason for this behaviour ?

hikariCp version : 4.0.3
Springboot : 2.7.13

**Comment by lfbayer** [comment]
This could easily happen if the thread that is trying to get the new connection doesn't get any CPU time for 20 seconds. The easiest way to force this is to put your system in sleep mode right after the connection attempt is started but before the 11 seconds passes. Then when you wake your system up again, the process will continue and see that MORE than 11 seconds has passed, thus triggering the timeout. The log message shows the actual time that has passed rather than just the configured timeout.

There are many other reasons why the thread might not be given CPU time. On an overloaded system with many other threads or processes running the scheduler in the OS kernel might not find an opportunity for your application to run. So this sort of timeout is normally indicative of an overloaded or under-provisioned system.

**Comment by sagarsitap596** [comment]
Thank you @lfbayer for the explanation
