### ISSUE TITLE
HikariCP Warning: "Driver does not support get/set network timeout for connections"

### ISSUE THREAD

**Issue by xiaogc123** [brettwooldridge/HikariCP#2196]
We are experiencing a HikariCP warning: "Driver does not support get/set network timeout for connections" while attempting to use read-write separation based on ShardingSphere 5.4.0. We have explicitly specified to use the MySQL driver (mysql-connector-java 8.0.28).
Detailed steps to reproduce:
We added the dependency for mysql-connector-java 8.0.28 in our pom.xml file;
We explicitly specified the usage of the MySQL driver in ShardingSphere's configuration file (set driver-class-name property).However, the warning message persists.
From our understanding, HikariCP should be able to correctly set the network timeout when using the MySQL driver. We seek some assistance in resolving this issue.
Additional Information:

- ShardingSphere Version: 5.4.0
- MySQL Driver Version: mysql-connector-java 8.0.28
- HikariCP Version: (if available)

Thank you for your assistance!

**Comment by linghengqian** [comment]
- As a Committer of Apache ShardingSphere, I recommend closing this issue and reopening it on the ShardingSphere git https://github.com/apache/shardingsphere to facilitate further investigation. This is a known issue particular to ShardingSphere JDBC's JDBC Driver implementation, present since two years ago, though the original issue report has unfortunately been misplaced. 

- It's necessary to replicate the fetching of this property within ShardingSphere due to ShardingSphere JDBC Driver being a virtual driver that serves as a proxy for multiple underlying real Drivers.

- This should look like https://github.com/pgjdbc/pgjdbc/pull/849 .

**Comment by linghengqian** [comment]
- Fixes by https://github.com/apache/shardingsphere/pull/33024 .
