### ISSUE TITLE
MultiPoolKey equals uses reference comparison

### ISSUE THREAD

**Issue by predhme** [brettwooldridge/HikariCP#226]
We have a [Delegating Data Source](http://docs.spring.io/spring-framework/docs/3.2.x/javadoc-api/org/springframework/jdbc/datasource/DelegatingDataSource.html) with the HikariDataSource as the target data source. As such, our delegating data source typically invokes the `HikariDataSource.getConnection(String username, String password)`. The purpose of the delegating datasource is to determine which username and password to connect to the database as (uses information from our security layer). 

The issue then is [Line 302 - HikariDataSource](https://github.com/brettwooldridge/HikariCP/blob/dev/hikaricp-common/src/main/java/com/zaxxer/hikari/HikariDataSource.java#L302)
`else if (username == null && otherKey.username != null) {`

This is an issue because although the username and password may resolve the same (i.e. 'user1', 'password1') for multiple different users, the strings will have different memory locations. Therefore, Hikari is creating pools for each user, despite the database connection username and password being the same. 

With high regards, Ken

**Comment by predhme** [comment]
I should also say then that line 308 is equally culprit (the password reference comparison)

**Comment by predhme** [comment]
You know what, I noticed that the source I copied and the source I have (version 1.3.8) are different. It seems as though I just need to do an update. Sorry for the waste. Ken

**Comment by brettwooldridge** [comment]
@predhme I would like to note that in 2.3.0 we have marked ``HikariDataSource.getConnection(username, password)`` as deprecated.  It is an unnecessary complication to the library that has various issues with it's implementation.  For example, if you ask for MBeans to be registered and you specify a pool name, exceptions will occur -- because you are in reality creating one pool for each unique username/password tuple -- and pools with duplicate names cannot be registered.  There would also be isssues with methods like ``HikariDataSource.shutdown()`` which will shutdown all pools, or ``HikariDataSource.evictConnection()`` which doesn't know which pool is the eviction target.

It would be better to only support a single pool per HikariDataSource for a single username/password tuple, and allow a user-defined *delegating DataSource* to map the username/password to a pool manually.

Anyway, just a heads up.

**Comment by predhme** [comment]
Thanks for getting back to me Brett. I will take your advice, regarding the implementation. I do like that way more. Thanks!
