### ISSUE TITLE
Error Code Not Compliant with JDBC Specification When Changing User Password While Using HikariCP Connection Pool

### ISSUE THREAD

**Issue by oobujieshi** [brettwooldridge/HikariCP#2261]
**Environment Information**

-   Operating System: Windows 10
-   Java Version: 11.0.25
-   HikariCP Version: 6.1.0
-   MySQL Version: 8.0
-   JDBC Driver Version: mysql-connector-java-8.0.26

**Steps to Reproduce**
1. Configure HikariCP connection pool to connect to a MySQL database.
2. Perform normal database operations and establish a connection.
3. Change the password of the MySQL user.
4. Attempt to reconnect to the database.

**Expected Behavior**

- When the password is changed and the connection fails, the error code and message should comply with the JDBC specification.
`java.sql.SQLException: Access denied for user 'username'@'localhost' (using password: YES)
    at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:337)
    at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
    at com.aliyun.HikariCPConfig.main(HikariCPConfig.java:15)
`

**Actual Behavior** 

- When the connection fails after changing the password, the returned error code and message do not comply with the JDBC specification.
`java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30010ms (total=10, active=10, idle=0, waiting=0)
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:711)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:189)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:99)
	at com.aliyun.JdbcService.getConnectionAndQuery(JdbcService.java:24)
	at com.aliyun.Main.main(Main.java:14)
`

**Comment by brettwooldridge** [comment]
What makes you think the ``SQLTransientConnectionException`` thrown is not compliant with the JDBC specification?

> The subclass of [SQLException](https://docs.oracle.com/javase/9/docs/api/java/sql/SQLException.html) for the SQLState class value '08', or under vendor-specified conditions.

"or under vendor-specified conditions".

Update: Also [see here](https://github.com/brettwooldridge/HikariCP/blob/ffdb8106bccb285d1775af1e8b040bfce4588dc1/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L709). The original exception is recoverable by calling ``getNextException()``.

**Comment by oobujieshi** [comment]
However, when I use other connection pools such as c3p0, DBCP, and Druid, they always return the original exception. But with HikariCP, I need to call getNextException() to get the original exception. This is very unfriendly for downstream users.

**Comment by oobujieshi** [comment]
I tried to get the original exception using getNextException(), but when I reproduced the exception, the original exception I got was empty.
![image](https://github.com/user-attachments/assets/f1982493-1754-4492-a44f-b579839f18a6)

**Comment by brettwooldridge** [comment]
You are misunderstanding what is occurring here.

No **_connection failures_** have occurred, so there is no underlying exception. The detail message says:

> Connection is not available, request timed out after 30018ms *(total=10, active=10, idle=0, waiting=0)*

The pool is full (*total=10*) but all connections are in use (*active=10*). HikariCP is not receiving any exceptions from the driver, so there is no exception to wrap. The application is using all available connections and is holding them for more than the timeout (30 seconds).

**Comment by svendiedrichsen** [comment]
The complete code example with which you can reproduce the problem would help to examine the reason.

**Comment by brettwooldridge** [comment]
To be clear, the only time HikariCP will throw a ``SQLTransientConnectionException`` *that actually wraps an underlying exception* is when:

1.  The pool is **NOT** full, *and*
2. There is a thread waiting for a connection in ``getConnection()``, *and*
3.  HikariCP is *trying* to refill the pool but getting exceptions from the driver, and cannot get a connection before ``connectionTimeout`` occurs.

Let's examine several cases.

(1) The pool **IS** full. In this case, HikariCP is not trying to acquire any new connections from the driver, so there are no ``SQLException`` being throw from the driver. If the application calls ``getConnection()``, but all connections are in-use, and none become available during the ``connectionTimeout``, then a ``SQLTransientConnectionException`` will be thrown.

(2) If you reboot the database while the pool is running, all connections are lost and the pool starts trying to refill. Until the database recovers, HikariCP will be getting tons of ``SQLException`` trying to connect. Now, imagine that the application calls ``getConnection()`` during this time. Even though HikariCP is getting ``SQLException`` from the driver, if the database recovers and HikariCP is able to create a connection *before* the ``connectionTimeout`` occurs, then the application will be given that connection and never needs to know there was a connection issue.

A connection pool should consider every connection-related ``SQLException`` to be *transient*. Because if the database is down or unreachable it may recover -- in fact, we assume that it will. Also, if the pool is *full* but all connections are *active* (in use), it is also a *transient* condition -- we assume active connections will be returned to the pool.

So, even if HikariCP throws ``SQLTransientConnectionException`` from ``getConnection()``, the very next call to ``getConnection()`` *may* succeed because a connection was returned or was able to be acquired.

**Comment by oobujieshi** [comment]
You may not have understood my problem. My issue is that after using HikariCP to establish a connection, the exception occured when changing the database password does not conform to the JDBC specification. When I want to reproduce this exception scenario, I need to use up all the connections in the pool so that the pool will attempt to create new connections. When it discovers that the original password is incorrect and cannot create a connection, the program will then throw the exception I am looking for. However, the exception thrown here does not conform to the HikariCP and JDBC specifications. Your previous response was that HikariCP retrieves the original exception using getNextException(), but through testing, I found that under the conditions to reproduce this scenario, getNextException() does not retrieve the original exception.

**Comment by brettwooldridge** [comment]
@oobujieshi I would suggest this is certainly not the intended pattern for altering a password. The supported pattern used by most users is to pro-actively change the username/password like so:

1. Ensure ``allowPoolSuspension=true``.
2. Call ``HikariPoolMXBean.suspendPool()`` to suspend giving out connections
3. Evict connections via ``HikariPoolMXBean.softEvictConnections()``
4. Spin and sleep until ``HikariPoolMXBean.getTotalConnections()`` goes to zero
5. Change the username/password through ``HikariConfigMXBean``
6. Call ``HikariPoolMXBean.resumePool()`` to restart the pool

Depending on a ``SQLException`` to trigger a password change seems strange and non-deterministic.

**Comment by oobujieshi** [comment]
Have you tried it through this step and is it okay?

**Comment by oobujieshi** [comment]
Sure! Can you provide me with a complete test example code?
