### ISSUE TITLE
Comments on "Bad Behavior: Handling Database Down"

### ISSUE THREAD

**Issue by simeonmalchev** [brettwooldridge/HikariCP#230]
Hi Brett,

I'm the author of Vibur DBCP and I'm opening this issue with regards to your post "_Bad Behavior: Handling Database Down_". I have 3 main comments on it:

1) There is no defined standard for DataSource.getConnection() timeouts, each pool implements them in its own way.
2) How to configure properly the connection validation frequency and timeouts for Vibur DBCP.
​3) The amount of JDBC timeouts which may occur during the execution of the internal to the pool JDBC calls is only ​a very small part of the total amount of JDBC timeouts which may occur during an application lifecycle.

I will go in details on each of these points below:

1) There is no defined standard for DataSource.getConnection() timeouts, each pool implements them in its own way.

Saying that in the context of someJDBCConnectionPool.getConnection(timeout) "_a connection timeout is a contract between you and the pool; your application should get a connection within the specified time, or get an exception_" - is incorrect. The original JDBC API spec doesn't say anything about any timeouts when it comes to creating or getting JDBC connections. If there is any contract for that, the concrete terms of this contract will be defined entirely on a pool-by-pool basis. In the Vibur DBCP case, the documentation for connectionTimeoutInMs can be seen [here](http://www.vibur.org/#connection-timeouts).

2) How to configure ​properly ​the connection validation frequency and timeouts for Vibur DBCP.

I believe that the focus of your testing has been to verify whether the chosen connection pools properly apply Java socket read timeouts when executing various specific to the pool implementation JDBC calls. It appears that HikariCP uses the Connection.setNetworkTimeout() method to control these timeouts. Vibur DBCP doesn't currently use this method, however this method is not the only way how to control these socket timeouts.

​There are 2 different ways how to configure the Vibur DBCP connection validation frequency and socket read timeouts:

​2.​1) Use Connection.isValid() for connection validation and timeouts control.

// Add the below line to the Vibur config. This will cause each connection to be always 
// validated disregards of how recently it has been used:
vibur.setConnectionIdleLimitInSeconds(0);
// Comment out the line below. This will cause Vibur DBCP to issue a call to Connection.isValid()
// for connection validation purposes, which is the Vibur default behaviour​:
// vibur.setTestConnectionQuery("SELECT 1");

The implementation of Connection.isValid(timeout) in the MySQL Connector/J driver (and likely in all other recent and solid JDBC drivers) sets the socket read timeout to the given timeout value. In the Vibur DBCP case, this timeout value is not currently configurable, and is hardcoded to 5 seconds (this may change in future).

Regarding the connection validation frequency, Vibur has its connectionIdleLimitInSeconds property set by default to 15 seconds. This is an intentional choice, as I felt that validating the connection before every single use will have much more penalizing effect on the using it application, rather than contributing any good. ​If I haven't misunderstood the HikariCP source, it employs a very similar idea as it also doesn't validate all recently used connections, I'm speaking about the ALIVE_BYPASS_WINDOW property which has a default value of 1 second.

2​.2​) Use arbitrary SQL query for connection validation but add "?socketTimeout=5000" to the JdbcUrl connection string.

// Firstly, ​as before, ​​a​dd the below line​:
vibur.setConnectionIdleLimitInSeconds(0);
​// Add "?socketTimeout=5000" to the JdbcUrl connection string:
vibur.setJdbcUrl("jdbc:mysql://192.168.0.114/test?socketTimeout=5000");

As already explained in the CUBRID's article to which your original post links to, and for the reasons which I will outline below, the explicit configuration of the socket read timeout at the JDBC driver level is of **utmost importance**. Note that similar JdbcUrl change should cause all tested JDBC connection pools to properly timeout their validation queries, not only Vibur DBCP. However, the importance of this explicit socket timeout configuration is much broader​, because​:

​3) The amount of JDBC timeouts which may occur during the execution of the internal to the pool JDBC calls is only ​a very small part of the total amount of JDBC timeouts which may occur during an application lifecycle.

A typical busy web application will usually execute many thousands of custom written SQL queries each hour, plus the mentioned above and specific to the pool implementation JDBC calls. These internal to the pool JDBC calls, will most likely take less than 1% of the total application time spent in JDBC calls, and the other 99% of the time will be spent in execution of the application's custom SQL queries. If the application hasn't properly configured the socket read timeout in the JdbcUrl connection string and if a network connection glitch occurs, then the application is risking some of its threads to face very long timeouts, and these timeouts will happen not during the execution of the specific to the pool JDBC calls but during the execution of the application's own SQL queries.

Simeon.

**Comment by brettwooldridge** [comment]
Hi Simeon,

Thanks for the feedback, I'll update the Vibur configuration as per your recommendations in (2) and (2.1) above, and re-run the tests.

I'll offer a few of my thoughts on your feedback here.

I do understand that JDBC itself does not define a ``connectionTimeout`` semantic, and that it is left to pool implementations to define what that means.  Which might make the statement *"a connection timeout is a contract between you and the pool; your application should get a connection within the specified time, or get an exception"* dogmatic to some.  However, in practical terms, and from a pool consumer's perspective I still believe it to be true.  If ``connectionTimeout`` is only interpreted to mean "when all systems are functionally normally", it is of little value to a developer.  If a user makes a web request, and I want to either fulfil their request within X ms or display an error page, it is of little value if obtaining a connection against a downed database might actually hang the request thread for 30 seconds (or 2 minutes).  Under that interpretation I can offer no service level agreements (SLAs) to consumers of my service.

``socketTimeout`` is a poor substitute for ``connectionTimeout`` because it is applied across the board to all activity on the connection.  I might want to provide an initial response to a request within, for example, 500ms, but subsequent data infill requests may take several seconds or tens of seconds to complete.  We actually had a bug related to this where we set the ``networkTimeout`` to a low value (=``connectionTimeout``) but the user's subsequent queries running several seconds were terminated prematurely.  It is important that they be kept separate; a need which was recognized by JDBC in the separation of ``loginTimeout``, ``queryTimeout``, ``isValid(timeout)``, and recently ``networkTimeout`` and ``abort(timeout)``.

**Comment by brettwooldridge** [comment]
I will close this issue after the tests have been re-run and further discussion concluded.

BTW, I am generally impressed with the quality and conciseness of the Vibur codebase, and if these timeout issues can be remediated I feel that Vibur can be a viable contender/alternative to HikariCP.

**Comment by simeon-malchev** [comment]
Brett, I'll try to structure my response on per comment/per paragraph basis in order to make it more clear what I'm responding at.

[@Comment-70508282](https://github.com/brettwooldridge/HikariCP/issues/230#issuecomment-70508282)

@Paragraph1: Just to add that you may also disable the retries on connection failure if you want to. For this, just add the below line:
vibur.acquireRetryAttempts(0);

@Paragraph3: I think that these are 2 different approaches for dealing with possible network outages: one is to adhere to a strict SLA requirement for getConnection() return time or timeout, which is what HikariCP is doing, and the other approach is to allow for N re-connect attempts, which is what Vibur DBCP doing. I have seen in practice how the retries approach has on occasions helped to resolve/bypass a temporary network glitch, and that's why I have chosen it, but besides of this, both of these approaches are valid.

@Paragraph4: It makes sense to me to keep these timeouts separate, there are some scenarios which may benefit from similar separation. I was touching on this point at the end of my original post.

[@Comment-70508895](https://github.com/brettwooldridge/HikariCP/issues/230#issuecomment-70508895)

I'll definitely consider employing the setNetworkTimeout() method in the next version of Vibur DBCP as a way to control the socket read timeouts of the internal to the pool JDBC calls, or I'll at least explicitly and clearly document what is the expected way to configure these timeouts externally.

I'm looking forward for an update on how the testing went.

**Comment by simeonmalchev** [comment]
Brett, this issue is now more than a year old and I think that you should consider closing it. I opened it for communication / discussion purposes, however the github issues are maybe better suited for bugs reporting purposes rather than for what I used it for, so I guess, it will be better for this issue to get closed.

**Comment by brettwooldridge** [comment]
@simeonmalchev I do have an update.  About two weeks ago I did setup two systems and again tested the pools.  As far as I could tell the updated version of Vibur behaved correctly.

I didn't have time to capture the outputs from the runs in order to update the wiki, but since the systems are setup now, I'll try to do it this week.  Hopefully that can put this issue to rest.  

Thanks for the continual poking, without it running the tests and updating the wiki would simply fall to the bottom of the queue.

**Comment by missedone** [comment]
hi @brettwooldridge
please update the wiki to reflect the latest status.
thanks

**Comment by johnou** [comment]
@simeonmalchev does Vibur have a benchmarking suite / project? I would love to see a comparison between Vibur and HikariCP from "the other side of the fence".

**Comment by brettwooldridge** [comment]
@simeonmalchev @missedone BTW, I did update the textual content of the [DB Down wiki page](https://github.com/brettwooldridge/HikariCP/wiki/Bad-Behavior:-Handling-Database-Down) about a week and a half ago, but I haven't had time to format the logs for inclusion on the page.

**Comment by simeonmalchev** [comment]
@johnou Vibur doesn't currently have a JMH benchmark test, if this was your question, although writing such test is on my todo list for a while.. Vibur has one performance test which I'm running when I'm profiling it before a new release, but this test is not JMH based.

**Comment by simeonmalchev** [comment]
@brettwooldridge thanks for coming back to this and updating the page.

**Comment by simeonmalchev** [comment]
After the latest updates I think that this issue can be now closed.
