### ISSUE TITLE
javassist.NotFoundException: com.zaxxer.hikari.proxy.ConnectionProxy

### ISSUE THREAD

**Issue by Traubenfuchs** [brettwooldridge/HikariCP#249]
I downloaded the latest hikariCP 2.3.2 .jar, javassist 3.19.0 .jar and sl4j-api-1.7.10.jar, and when I start an application with hikaricp in Eclipse I get the following exception:
 javassist.NotFoundException: com.zaxxer.hikari.proxy.ConnectionProxy
at javassist.ClassPool.get(ClassPool.java:450)
at javassist.ClassPool.getCtClass(ClassPool.java:515)
at com.zaxxer.hikari.proxy.JavassistProxyFactory.generateProxyClass(JavassistProxyFactory.java:130)
etc.

Is there anything I can do to fix this?

**Comment by brettwooldridge** [comment]
Running in Eclipse can be tricky due to how Eclipse manages the classpath.  I suggest checking the launch configuration for whatever application you are trying to launch to make sure that all jars are included.  If you're not using a dependency management tool like maven, you will have to chase down the dependencies yourself.  For example, Javassist depends on asm.

Also sl4j-api-1.7.10.jar is not enough by itself, you need a logging implementation like slf4j-log4j12.jar.  There are many logging implementations available, check the slf4j website.
