### ISSUE TITLE
minimum connectionTimeout value has changed, readme.md out of sync

### ISSUE THREAD

**Issue by drobert** [brettwooldridge/HikariCP#252]
Similar to https://github.com/brettwooldridge/HikariCP/pull/140 it seems the readme.md file in master indicates a minimum connectionTimeout of 100ms, while the code (after moving this logic from HikariConfig to AbstractHikariConfig) throws an exception if this value is under 1000ms. 

Was the shift to 1s intentional or a typo during porting? Version 2.1.0 has 100ms in HikariConfig while 2.3.1 has 1000ms in AbstractHikariConfig.

**Comment by brettwooldridge** [comment]
@drobert The shift was intentional, but I will consider whether there is a way to enable shorter timeouts reliably.  The basic issue comes from the fact that HikariCP introduced the concept of ``validationTimeout``.  We had a user (possibly several) that want an infinite ``connectionTimeout`` (they're willing to wait in ``getConnection()`` until one is available), but the fact that HikariCP was also using ``connectionTimeout`` for connection alive validation causes a problem in that case.  The expectation is that a connection can be validated as alive within some smaller amount of time (for example, several seconds).

We come then to connection validation.  Whether the user is using a validation query (eg. SELECT 1) or JDBC4 validation, the minimum timeout for ``setQueryTimeout()`` or ``isValid()`` is denominated in seconds, not milliseconds.  So, 1 second is the lower-limit on validation.  If that is the case (as per JDBC), there is no way to guarantee a ``connectionTimeout`` of 100ms when, after obtaining a Connection from the internal bag, it might take a minimum of 1 second to validate the Connection.

HikariCP treats the ``connectionTimeout`` as a hard contract.  The user will either receive a Connection within ``connectionTimeout`` or they will get a SQLException.  As it stood, there was no way to satisfy this guarantee.

Having said that, there is one "out" that may allow HikariCP to support a shorter timeout.  If the JDBC driver supports the ``setNetworkTimeout()`` method, which is denominated in milliseconds, it is possible to uphold a ``connectionTimeout`` (and ``validationTimeout``) of less than 1000ms.

The question then becomes, is it actually reliable.  For example, if ``connectionTimeout`` is 100ms then ``validationTimeout`` must necessarily be 100ms or less.  If a database server is busy (loaded), can it reliably satisfy a connection validation in 100ms or less?  A connection failing validation is closed and ejected from the pool.  If a DB server under even moderate load cannot satisfy validations with 90% or better success, the pool will end up churning Connections severely, resulting is even more load on the DB and downward spiral of failure.
