### ISSUE TITLE
Method like checkout(C3P0 connectionCustomizer) in HikariCp

### ISSUE THREAD

**Issue by jayashsam** [brettwooldridge/HikariCP#278]
I want a method that can be executed before a connection is given to the client. But there is only method called customize() in IConnectionCustomizer . Is there any thing that I can have

**Comment by jnehlmeier** [comment]
As a workaround you could wrap the Hikari Datasource with your own, e.g.
```java
class DataSourceWithCallback implements DataSource {

  DataSourceWithCallbacks(DataSource delegate, Callback callback) {
    // store in fields
  }

  Connection getConnection() {
    Connection con = delegate.getConnection();
    callback.exec(); // alternatively move before delegate.getConnection()
    return con;
  }

  // add remaining delegate methods 
}

// Somewhere in your code:
Callback onBeforeConnectionObtained = new Callback() {
   void exec() {
     // callback code
   }
}
DataSource ds = new DataSourceWithCallback(new HikariDataSource(config), onBeforeConnectionObtained);
```

**Comment by jayashsam** [comment]
Then in this case I have to write whole HikariDataSource class on my own. Right?

**Comment by brettwooldridge** [comment]
If you just need to execute statements on-borrow from the pool, the simplest way of doing this is with a *helper* rather than a *wrapper*.  For example:
```java
class DbHelper {
   private DataSource delegate;

   Connection getConnection() throws SQLException {
      Connection con = delegate.getConnection();
      con.execute(...);  // your code here
      return con;
   }
}
```
However, if you are constructing a DataSource to pass into another framework (for example, Hibernate), a *wrapper* class would be necessary.

The question is, what are you trying to achieve, and how does that fit with the standard model of DataSources?  Using hooks, like that provided by C3P0, can be useful but it also locks your application to C3P0.  A similar hook would lock your application to HikariCP.

A good general goal should be an application that is portable across pool implementations.  A *helper* class or *wrapper* class will give you that.  A pool-specific *interface* hook will not.
