### ISSUE TITLE
"DriverManager-based" configuration, force use named driver class.

### ISSUE THREAD

**Issue by vkolodrevskiy** [brettwooldridge/HikariCP#288]
Hi,

I'm using "DriverManager-based" configuration(specifying `jdbcUrl`).
I have mysql server running, mariadb and mysql jdbc drivers in classpath.
As you know, `DriverManager` returns the first driver from classpath that is able to connect to a given jdbc url, so it can be `com.mysql.jdbc.Driver` and `org.mariadb.jdbc.Driver`, this depends on the order these classes were loaded.
The goal is to make `com.mysql.jdbc.Driver` work with mysql server. Setting `HikariConfig.driverClassName` property does not guarantee which driver will be used.
The workaround that I found is to use `dataSourceClassName` based configuration.

This looks like a bug or enhancement, for example c3p0 has an option `forceUseNamedDriverClass` that together with `driverClass` can make pool work with a given driver.

**Comment by brettwooldridge** [comment]
There are two workarounds for this.  One, as you found is using the DataSource, which is the preferred way to create connections since JDBC 2.0.  The second is to explicitly call ``Class.forName("com.mysql.jdbc.Driver")`` *before* any reference to ``java.sql.DriverManager`` is made.  This will force the MySQL driver to be the first in the list of registered drivers.

**Comment by vkolodrevskiy** [comment]
These lines of code: 
```
Class.forName("com.mysql.jdbc.Driver");
HikariConfig config = new HikariConfig();
config.setJdbcUrl(DB_URL);
config.setUsername(DB_USER);
config.setPassword(DB_PASS);

HikariDataSource ds = new HikariDataSource(config);
Connection connection = ds.getConnection();

if (connection != null){
    System.out.println(connection.getMetaData());
}
```
Give the output:
```
org.mariadb.jdbc.MySQLDatabaseMetaData@285fdb25
```
I'm on OSX Y, jdk 1.7.0_51. So `Class.forName` did not help in my case.
Is there something I'm missing?

**Comment by brettwooldridge** [comment]
@vkolodrevskiy I was wrong.  Calling ``Class.forName()`` *will* force the MySQL driver to self-register, but the problem is that it will do so by calling ``DriverManager.register(Driver)`` ... and as soon as it does that then the ``DriverManager`` static initializer will run and auto-register all the drivers in the classpath *before* the MySQL has a chance to register.

The last option is the only option currently, and it's not pretty.  I will take this as an enhancement, such that specifying a ``driverClassName`` property will explictly create an instance of that Driver, instead of using ``DriverManager.getDriver(url)``.

**Comment by vkolodrevskiy** [comment]
@brettwooldridge, that's awesome! Thank you!
