### ISSUE TITLE
Hikari logs continue to print debugging output in sbt when no tasks are running

### ISSUE THREAD

**Issue by carymrobbins** [brettwooldridge/HikariCP#292]
I could be doing something wrong here, but when running sbt interactively, hikari debug logs continue to report out information even after the tasks are completed (e.g. after the test suite runs).

```
Before pool cleanup Pool stats (total=15, inUse=0, avail=15, waiting=0)
After pool cleanup Pool stats (total=15, inUse=0, avail=15, waiting=0)
```

Shouldn't the hikari process stop once the task has completed?

If it helps, I am using -
* scala 2.10.2
* sbt 0.13.6
* play 2.2.2
* play-hirakicp 1.0.0

And yes, it is _hiraki_.

**Comment by brettwooldridge** [comment]
@carymrobbins You need to shutdown the pool by calling either ``shutdown()`` or ``close()`` on the HikariDataSource.  I don't know whether this is something one of your frameworks can do or not, but if you never shutdown the pool, that background thread is going to keep going (how could it know otherwise).  Either way, this is not a HikariCP issue per se.

**Comment by carymrobbins** [comment]
Thanks @brettwooldridge, is there a good way to do it from sbt?  Although, I'm thinking that may not be possible.

I am also using play-jdbc-standalone 2.1.1, so maybe that has something to do with it.  I'll try to read the docs then figure out how to get an instance of HikariDataSource and how this thing is working under the hood.

**Comment by brettwooldridge** [comment]
You might ask over on the Play forums, somebody must have solved this
before.
