### ISSUE TITLE
Restore Pool After Shutdown

### ISSUE THREAD

**Issue by joebrassi** [brettwooldridge/HikariCP#300]
I am running some tests with different databases, but HikariCP is unable to switch from one configuration (hsqldb, h2, mysql) to another. After the data source is closed, there is no (apparent) way of restoring the connection pool. And if one tries to retrieve a connection, then it returns:

```console
java.sql.SQLException: Pool has been shutdown
or
java.sql.SQLException: Data source is closed
```

Also, is there any way of determining whether a Data Source is closed? Something like an `isClosed()` method.

**Comment by brettwooldridge** [comment]
HikariCP is not designed to support altering configuration once the pool has started, other than the properties available to set via the JMX MBean.  In order to achieve the performance that it does, HikariCP determines the capabilities of a JDBC driver the first time that driver is accessed and caches this information for the life of the pool.

There is no ``isClosed()`` method on ``HikariDataSource`` at present (no one as asked), but I will consider this issue to be an enhancement request.
