### ISSUE TITLE
HikariCP does not respect minimumIdle 

### ISSUE THREAD

**Issue by yosstef** [brettwooldridge/HikariCP#306]
Hello,
We are using v2.3.5 with PGSimpleDataSource; The pool is configured programmatically. 

I have noticed that around each 9 minutes the HouseKeeper closes most of the connections (the minimum idle number of connections) due to IdleTimeout. This doesn't make sense - why would the pool close connections if the minimumIdle is reached ? Note that the maxLifetime is set to 0 (zero). 

			config.setRegisterMbeans(true); // Default false
			config.setConnectionTimeout(60000); // default 30000 ms = 30s
			config.setIdleTimeout(60000); // Default: 600000 (10 minutes)
			config.setMaxLifetime(0); // Default: 1800000 (30 minutes)
			config.setMinimumIdle(10); // Default: same as maximumPoolSize (10)
			config.setMaximumPoolSize(100); // Default: 10
			config.setValidationTimeout(50000); // Default: 5000 ms = 5s

Reading the HikariCP code I just don't see why in this check below, the minIdle number is not respected (not checked anywhere) - this makes using a pool meaningless ? :   

               if (bagEntry.evicted || (idleTimeout > 0L && now > bagEntry.lastAccess + idleTimeout)) {
                  closeConnection(bagEntry);
               }

**Comment by brettwooldridge** [comment]
@yosstef From the ``minimumIdle`` documentation:

"This property controls the minimum number of idle connections that HikariCP __tries__ to maintain in the pool. __If the idle connections dip below this value__*, HikariCP will make a best effort to add additional connections quickly and efficiently.*"

Generally speaking, in an application that is even *just a little* active, connections very quickly obtain *lastAccess* timestamps that are different than each other.  When this occurs, idle connections will start expiring at different times, rather than all at once.

Expiring connections that reach timeout is considered a higher priority than maintaining a constant number of minimum connections.  Having said that, what you omitted from you code fragment above, is this:
```
fillPool(); // Try to maintain minimum connections
```
After expiring connections, HikariCP will immediately (within tens of milliseconds) replace them in the pool with new connections until minimumIdle is reached.  If you find that this is not occurring, please let us know.

**Comment by fjjiaboming** [comment]
I meet one question in 2.4.1 .
Do I need to open one new issue?
