### ISSUE TITLE
connection.setReadOnly(isReadOnly) at  PoolUtilities.java:129 throws SQLFeatureNotSupportedException with Voltdb

### ISSUE THREAD

**Issue by saj1th** [brettwooldridge/HikariCP#340]
Looks like VoltDB does not support  read-only mode. so when used with hirakicp it throws the error

java.sql.SQLFeatureNotSupportedException
	at org.voltdb.jdbc.SQLError.noSupport(SQLError.java:65)
	at org.voltdb.jdbc.JDBC4Connection.setReadOnly(JDBC4Connection.java:480)
	at com.zaxxer.hikari.pool.PoolUtilities.setupConnection(PoolUtilities.java:129)

Wondering how to use hirakicp with data stores that do not support read-only mode

**Comment by brettwooldridge** [comment]
I would consider this a bug (in HikariCP), I will take a look at how to detect this case.

**Comment by brettwooldridge** [comment]
v2.3.9 is now available with this fix.

**Comment by saj1th** [comment]
Great! :)  Thanks a lot for looking into it

**Comment by brettwooldridge** [comment]
@saj1th Unfortunately, we are going to remove this change in a future release of HikariCP.

Here is the rationale that was posted for a [similar issue](https://github.com/brettwooldridge/HikariCP/issues/369#issuecomment-128008306):

----------------------
The ``readOnly`` exception added for VoltDB set a bad precedent, and in truth should be removed from HikariCP.  Both VoltDB and Hive2 are open-source projects and the issue should be taken up there.

----------------------

The documentation for ``SQLFeatureNotSupportedException`` states:

*The subclass of SQLException thrown when the SQLState class value is '0A' ( the value is 'zero' A). This indicates that the JDBC driver does not support an optional JDBC feature. Optional JDBC features can fall into the fallowing categories:*

 * *no support for an optional feature*
 * *no support for an optional overloaded method*
 * *no support for an optional mode for a method. The mode for a method is determined based on constants passed as parameter values to a method*

The exception documentation for ``setReadOnly()`` states:
![screen shot 2015-08-06 at 17 08 27](https://cloud.githubusercontent.com/assets/1538661/9106806/dc2ed800-3c5d-11e5-8c1a-b8eeb9da7c75.png)

The most correct behavior for the driver (both Hive2 and VoltDB) is, if the driver has *no concept* of "read-only" operation, it can throw *if ``true`` is passed to ``setReadOnly()``*.

Conversely, if the driver has no concept of "writability", it can default readOnly to ``true`` (i.e. ``isReadOnly()`` should return true), and it can throw if ``false`` is passed to ``setReadOnly``.

Please [report the issue](https://forum.voltdb.com) to VoltDB.  Feel free to direct any VoltDB developers here.  We will wait a reasonable amount of time (1-2 months) before removing this feature from a future release.

Please report back here when you have confirmed that this issue is fixed in VoltDB.
