### ISSUE TITLE
Transaction connection isolation level should handle integers

### ISSUE THREAD

**Issue by antonsarov** [brettwooldridge/HikariCP#349]
I am using HikariCP with Hibernate 3. One of the option is the hibernate.connection.isolation which I would like to set to "2" - this is a valid value (http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/java/sql/Connection.java/#398).

The problem for me is that the `UtilityElf` expects the provided String parameter to the method `getTransactionIsolation(...)` to correspond to one of the constants in the `java.sql.Connection` class. Which is of course perfectly valid but it forces me to use this constant in my configuration.

Given the fact that no further sanity checks are done, I would like to suggest that this method also handles integers masked as Strings - e.g. with `Integer.valueOf(...)`.
Alternative: create a second method with int parameter or even do the check in `AbstractHikariConfig`'s `validate()` and if really a string then call the `getTransactionIsolation`

**Comment by brettwooldridge** [comment]
``hibernate.connection.isolation`` will accept string constants.  While it is true that ``setTransactionIsolation()`` takes an ``int``, the [JavaDoc states](http://docs.oracle.com/javase/7/docs/api/java/sql/Connection.html#setTransactionIsolation(int)) that the constants defined in the interface should be used.

The whole point of using constants is to 1) reduce coding errors, and 2) abstract "magic numbers" from the code.  If Oracle redefined ``TRANSACTION_REPEATABLE_READ`` as ``4096`` instead of ``4``, properly written code (or configuration) should be unaffected.  It is actually for this reason that the constant values themselves do not appear in the JavaDoc.  And until Oracle open-sourced Java, looking at those values required decompilation.

**Comment by antonsarov** [comment]
I am perfectly familiar with the advantages of constants. However some flexibility should not hurt in this case.

**Comment by brettwooldridge** [comment]
@antonsarov the ``dev`` branch currently has a commit that supports using an integer.

**Comment by antonsarov** [comment]
Thanks
