### ISSUE TITLE
SQLTimeoutException & CommunicationsException

### ISSUE THREAD

**Issue by pxrsps** [brettwooldridge/HikariCP#370]
Hi, 

I am using HikariCP to handle multiple database services on my gaming server, such as an automatic voting system. This service in specific is handled somewhat often (on average every 30-60 seconds) by several hundred users a day. I have been running into some issues with connections timing out and in turn throwing SQLTimeoutException and CommunicationsException, causing the gaming server to freeze for 15-30 seconds. This seems to be happening every 4 to 6 hours and I have just been restarting the service to temporarily resolve it.

I have not been able to pinpoint the issue yet. I'm not sure if it is a misconfiguration with HikariCP, or I am not closing the connections properly. I have posted some code and details below. I am hoping someone can give me some tips on how to resolve these issues. 

Libraries: 
HikariCP-2.3.9
Slf4j-jdk14-1.7.12
Slf4j-api-1.7.12

HikariCP properties and initialization: http://pastie.org/10331743
Handler code: http://pastie.org/10331719
Stack trace (CommunicationsException): http://pastie.org/10331744 AND   java.sql.SQLTimeoutException: Timeout after 34002ms of waiting for a connection.

Thanks in advance, 

William

**Comment by jnehlmeier** [comment]
In `com.prodigyx.database.impl.Vote.execute(Vote.java:128)` you are executing a query that fails with a timeout because 

- the query is too slow and no answer has been send from the database within the specified socket timeout, or
- your database does not react for whatever reasons

That HikariCP also says that a connection leak has been detected is the result of the above because the connection on which the query executes is not returned to the pool (via connection.close()) within the specified connection leak threshold. 
Its a bit strange that your configuration does not configure leak detection but still Hikari's LeakTask is run but maybe you just have not pasted your configuration completely.

Your handler code will close connections correctly (if you use Java7+ then checkout try-with-resource to simplify the code) but your real issue is that your query does not complete in a given amount of time.

**Comment by nitincchauhan** [comment]
In addition to what jnehlmeier said:

dataSource.connectionTimeout=34000 
dataSource.maxLifetime=180000
dataSource.idleTimeout=120000

Above are properties of pool, Not data source. Remove "dataSource." from them.

Also remove configuration.setConnectionTestQuery("SELECT 1"); as 'recent' mysql drivers supports isValid() and this will result in get connection even faster.

Also you have not given 'full' configuration ! I do not see leak detection threshold set but leak shown as exception !

**Comment by pxrsps** [comment]
Thank you for the tips, I apologize - I had leak detection threshold set at the time of that stack trace. 

I will test some more with these changes and report back.
