### ISSUE TITLE
HouseKeeper should not close idle connections once reached to min number of connections

### ISSUE THREAD

**Issue by yaojuncn** [brettwooldridge/HikariCP#379]
https://github.com/brettwooldridge/HikariCP/blob/bc010fba486b27ae3d034cc9701e0c4217457ddb/src/main/java/com/zaxxer/hikari/pool/HikariPool.java
line 633 to 650, in housekeeper check,  it will close all the idle connections; and then try to fill the connection pool;
in prod I've seen logs showing that the total connections are less than the configured min number;

this is incorrect in terms of 2 points: 
1. connection pool should keep the contract of keeping min number of connections in the pool; 
2. more important, the fillPool() in this way will cause a connection storm issue, which means the databases will receive a large number of new connections request, will might be a big overhead to database; 
while this issue is not that serious on single web servers, it becomes a big problem in distributed systems with good number of application servers connecting to the same database; 
in practice there're cases that connection storm caused a big problem for db;

**Comment by brettwooldridge** [comment]
The minimumIdle is not a contract, the documentation states clearly:

This property controls the minimum number of idle connections that HikariCP
***tries*** to maintain in the pool. *If the idle connections dip below this value, 
HikariCP will make a* **best effort** *to add additional connections quickly 
and efficiently.*

Having said that, connections are added by a single threaded executor and is highly unlikely to overload a server.  In a environment with "a good number of application servers" within each pool connections will reach idle at different times, distributing the renewal of connections.

Actually, even within the same pool connection, connections with have different distribution as to when idle is reached.

**Comment by yaojuncn** [comment]
1. "in practice there're cases that connection storm caused a big problem for db;" 
This is from practice as things like this did happen.  that's under a large volume, high concurrency , distributed system. 

although the different servers may create the connections at different times, when you say unlikely, they are still possible, which means in some cases they will happen; when there several thousand application servers connecting to one database, and usually the database server is under heavy load, any connection storm spike has a big impact on the whole system. 

2. with HikariCP, I've also seen the total number of connection reach to a very small number such as 4; 
(the config is 10-40);    if at this time there're some sudden traffic coming in, it will have to create many more connections (6 more in this case) because the pool has too little connections;  the current housekeeper logic may also lead to 0 connections in some cases, which at the moment is like no pool at all; 
 
3. stop closing the connections when reaching at min number of connections is surely better than closing them all and then refill them. the stop check is actually the common implementations in some other connection pools;  I do not see any reason why HikariCP wouldn't want to do it?

**Comment by brettwooldridge** [comment]
@yaojuncn I'll take the points out of order.

First, if you are concerned about "spike loads" the HikariCP documentation specifically recommends running as a fixed-size pool.

Re: "with HikariCP, I've also seen the total number of connection..."
You say you've seen HikariCP reach 4 connections after the housekeeper runs.  I'm not surprised.  But you also don't cite how long the refill took.  It is logged, and creating 6 connections to reach your 10 minimum likely took less than 400ms (possibly less than 100ms).

Still, let's imagine that the pool is at 10 idle connections.  A "spike demand" comes in and claims 6.  What is going to happen?  Well, now you have only 4 idle so the pool still has to create 6 new ones to reach the 10 minimum.

Again, if you are concerned about spike demands, then creating connections *during* the spike, as *dictated* by having a ``minimumIdle`` set is going to place undesirable load on the DB at a time when it can least afford it.  That is why a fixed-size pool is recommended.

Re: "stop closing the connections when reaching at min number..."
Reasonable.

Re: "although the different servers may create the connections at different times..."
If you are talking about "several thousand" application servers, there is no way for HikariCP to coordinate connection retirement or creation between them  In practice, this means that whether connections are retired because of reaching ``idleTimeout`` or because of reaching ``maxLifetime`` it is always possible to have "waves" of connection closure and creation.

However, we are arguing how many angels can dance on the head of a pin.  If "things like this did happen" it is because of poor architecture not pool implementation.  It is hard to imagine an environment where this could possibly make sense.  If "several thousand application servers" are connecting to one database -- and I'll be generous here and say 1000 application servers -- and each pool has a ``minimumIdle`` of 10, you are suggesting a single database server with 10000 connections.

Even Oracle recommends something like a 96-connection pool for a 16-core server.

My recommendation for a stable pool that is responsive to spike loads and does not place creation load on the DB would be something like ``maxPoolSize`` of 10-30 connections, no ``minimumIdle`` (ie. same as ``maxPoolSize``),  no ``idleTimeout`` (ie. 0), ``maxLifeTime`` of 10 minutes (600000ms).

**Comment by yaojuncn** [comment]
1. fixed size pool is not always the best choice; most times you will need min-max setting; because if you stick to some small value, it might be not enough, client side may get timeout when trying to get connections; if you stick to big value, it's a waste, since total number of connections in db side are expensive resources; if one application occupies some, other application may not be get those needed; 
2. giving min=10,  when reach 4, the faster you created the 6 connections, the bigger impact to database systems because creating a connection is a relatively very expensive operations, especially for large volume systems
3.  since you agree that "stop closing the connections when reaching at min number.", I'll create a pull request for you later;
4. for more than 1000 application servers connecting to one db server, it's not pool architecture; it's just because some systems process much much more orders than amazon.com every day. the architecture is actually very good because the only standard to judge architecture is how much business it can support.
 for oracle, i've seen many servers configured as several thousand connections using dedicated connections mode and they run very well together with more than 1000 application servers;
the way how connection pool is implemented indeed impacts whether it's usable in such cases;

**Comment by brettwooldridge** [comment]
Don't bother with a pull request, we already have one waiting ... #383

**Comment by yaojuncn** [comment]
I saw the change,  I think the code can be improved by below; please check  
https://github.com/brettwooldridge/HikariCP/pull/384
