### ISSUE TITLE
ERROR: canceling statement due to user request

### ISSUE THREAD

**Issue by Viniciusmsss** [brettwooldridge/HikariCP#477]
Hello,

We are using HikariCP in our desktop software that uses Postgresql installed at the users machines (almost 6000). We've made our software to send us e-mails if exceptions occur. Every day we receive around 20 automatic e-mails from different users reporting the following exception:

ERROR: canceling statement due to user request
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)  <-
org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)  <-
org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419)  <-
org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:304)  <-
com.zaxxer.hikari.proxy.PreparedStatementProxy.executeQuery(PreparedStatementProxy.java:44)  <-
m.c.b(Unknown Source)  <-
...

Searching in Google we've found the following site: http://postgresql.nabble.com/ERROR-canceling-query-due-to-user-request-td2077761.html

We think that it probably has nothing to do with HikariCP, but we've decided to report you anyway. It might be useful to know this potential problem. 

Thank you!

**Comment by brettwooldridge** [comment]
@Viniciusmsss Thank you for the interesting report.  Because of a fairly amount of asynchronicity within HikariCP, there is always the possiblility that HikariCP is provoking this issue in the Postgresql backend.

Have you done anything to narrow the issue down?  It is always in the same piece of application code?  Is it only PreparedStatement.executeQuery()?

**Comment by Viniciusmsss** [comment]
It is very difficult to narrow down because it never happened in ours tests, but it happens daily in production, at our users machines. Also, our code is extensive.

We know that it comes from a lot of different pieces of the application code because we have the complete stack trace of the exceptions. We only use PreparedStatement.executeQuery() so there's no other scenario.

In my opinion, this can be happening because of viruses in the user's machines (what is very common) or because they are shutting down the OS while the software and database connections are still opened.

You said that there is always the possibility that HikariCP is provoking this issue. In this case, is it a HicariCP bug or is it normal behavior? Or maybe misuse of HicariCP?

Thank you!

**Comment by brettwooldridge** [comment]
@Viniciusmsss If something about HikariCP's access pattern with PostgreSQL is provoking this issue, it is almost certainly a bug in PostgreSQL.  But even if that is the case, it is possible that we can identify what is causing it, and provide a workaround.  That is why I have temporarily left this issue open.

**Comment by brettwooldridge** [comment]
@Viniciusmsss I opened a tracking issue https://github.com/pgjdbc/pgjdbc/issues/412 on the pgjdbc project.

**Comment by nitincchauhan** [comment]
@Viniciusmsss meanwhile set 'connectionTestQuery' as workaround

**Comment by brettwooldridge** [comment]
@nitincchauhan That won't work.  When we use a test query we use setQueryTimeout() directly, therefore it is equivalent to the isValid() method as implemented by pgjdbc.

**Comment by nitincchauhan** [comment]
aww f*** :( better driver guys up the priority and fix this :)

**Comment by Viniciusmsss** [comment]
Thank you, Brett, for your concern and for taking this issue forward. You are amazing! Thank you also, @vlsi (the man of the fastest fixes in the world) and @nitincchauhan . 

I will wait @vlsi fix [#412](https://github.com/Gordiychuk/pgjdbc/commit/e4a20425f82aa3810ce3fbc589704f0b71071d49)  of pgjdbc to be merged. Then I'll update the libraries of our project and tell you if it resolved our specific problem.

**Comment by Viniciusmsss** [comment]
Hello, I would like to inform that pgjdbc new releases fixed the problem for us. We are no longer having the exception "ERROR: canceling statement due to user request".
Thank you very much!

**Comment by brettwooldridge** [comment]
@Viniciusmsss Great, glad to hear it.

**Comment by rogue2yjg** [comment]
With a new version of pgjdbc, the same issue still happened, and it's worth noting that no matter how big I set the validationTimeout config, the issue always happened 10s after the query executed in multi thread scene.
[https://github.com/pgjdbc/pgjdbc/issues/412](url)

**Comment by rogue2yjg** [comment]
@brettwooldridge 
Hi brett,
  I want to consult with you about the previous "cancelling statement due to user request" problem. 
  As vlsi said, I had increased the defaultStatementOut value in mybatis config file and there hadn't been problems any more. But I thought that wasn't a grassroots solution.
  On the one hand, I would try to improve performance of the query sql.
  On the other hand, I found an interesting phenomenon in my test case. I used a thread pool with 5 threads to run 5 query sql tasks, and you could find the HikariCP config in my test case. Every query sql task was same and it would cost 2s+. When I started the test, the sql execution log and the HikariCP adding connection log appeared successively. But the program came to block after the log appeared 5 times, and after about 13s, the 5 query results log appeared almost at the same time.
  What I doubted were below: 
  1、The sql was just a query and there shouldn't be any lock wait when the 5 sql commands were executed in pg server concurrently;
  2、The 5 task used 5 different db connections to run the query sql, right?
