### ISSUE TITLE
About Pool Sizing

### ISSUE THREAD

**Issue by Maatary** [brettwooldridge/HikariCP#479]
I have a quick question about the part on Pool Sizing. 

Something i do not understand, is that it seems that there is no difference made between the client side of the application and the database Server. 

When you give the formula on the PoolSize and the number of Core, this seems to concerns, the client side only. But the way it is explained, such as taking into account Disk access, this seems to be database related. Hence i wonder how the two connect because this seems to be confusing here. 

How you Poolsize affect the perform of your application ? On the client size ? Does one connection correspond to one thread ? How does it affect the behavior of your database. 

Are your explanation only concerning the client side ? how does it relate to Blocking API vs Asynchronous API (database access). 

Many thanks

**Comment by brettwooldridge** [comment]
@Maatary The formula is used to determine how many concurrent connections *the database server* is capable of handling before performance starts to decrease.  Because the query performance starts to decline when the number of *client connections* exceeds that number, then that same number should be used to determine the maximum size of the pool *on the client* (HikariCP).

In other words, there is a direct relation between the size of the pool (number of connections to the database) and the performance of the database.  If the peak transactions per second (TPC) performance of the database occurs at 16 concurrent queries, for example, then the pool should be set to allow 16 connections maximum.

If peak DB TPS performance occurs at 16 concurrent queries, then allowing 32 connections from the pool would likely result in *more than* 2x decrease in TPS due to thread context switching overhead.
