### ISSUE TITLE
connnection in idle state , query commit indefinitely

### ISSUE THREAD

**Issue by abhishekparwal** [brettwooldridge/HikariCP#519]
I am using hikari cp 2.4.1 and I see a lot of connections in postgres in idle state with commit query:

 2015-12-11 11:28:23.056753+00 (backend_start) |    2015-12-11 11:28:23.082532+00  (query_start)| 2015-12-11 11:28:23.082557+00 (state_change) | f    (waiting)   | idle   (state)| COMMIT (query)

Hikari cp is printing them as ACTIVE. why is it so? Is it some connection holding by hikaricp for next query or a connection couldn't be closed properly?

**Comment by brettwooldridge** [comment]
@abhishekparwal According to [this page](http://www.postgresql.org/docs/9.2/static/monitoring-stats.html) that looks perfectly normal:
```
The waiting and state columns are independent. If a backend is in the active state, it may
or may not be waiting. If the state is active and waiting is true, it means that a query is
being executed, but is being blocked by a lock somewhere in the system.
```
That sems to indicate that the connection is not waiting (waiting=false), the current state is idle (``idle: The backend is waiting for a new client command``), and when the state is idle the *query_start* query ("COMMIT") reflects the last statement that was executed.

What does the HikariCP debug log show?

**Comment by abhishekparwal** [comment]
Understood the db part.
Hikari cp logs is printing them as ACTIVE.

**Comment by brettwooldridge** [comment]
If HikariCP is printing them as active, then some user thread has borrowed but not yet returned the connection.  If you enable the ``leakDetectionThreshold`` you can get a stacktrace that points to the connection borrow site.  That should identify at least where in the application or intermediate framework the borrow took place.

HikariCP does keep connection in the active state.  When you call ``getConnection()`` it becomes "active", and when you call ``close()`` on that connection it becomes "idle".  If HikariCP is consistently show "active" connections, it is because some caller has borrowed a connection but not yet returned it.
