### ISSUE TITLE
consider increasing maxLifetime to sensible default

### ISSUE THREAD

**Issue by nitincchauhan** [brettwooldridge/HikariCP#537]
at present it is 30mins.
main purpose of pool is to save clients from creating new connection cost.
dbcp2/tomcat/vibur does not even set it (default to zero)
I do not see any apparent benefit to retire them as early as 30 mins as pool takes care of  'idle/stale/broken' connections and DBs of today are able to manage resources of connection more efficiently.
I propose to set its default to zero or at least 'hour' or more

**Comment by brettwooldridge** [comment]
You would be amazed how many databases have high-availability proxies, load balancers, and firewalls between the application tier and the DB.  Quite often these components automatically and independently terminate connections around the 30 minute mark.

There are hundreds of questions on the Internet regarding DB communication exceptions the ultimately come down to these components.  These kinds of issues can generate considerable support load as they are extremely hard to distinguish from possible pool defects.

A 30 minute timeout is quite reasonable, particularly because connection establishment typically takes milliseconds, and the new variance injection makes the retirement and re-establishment practically immeasurable at the application level.

**Comment by nitincchauhan** [comment]
@brettwooldridge IMO remove ThreadPoolExecutor for use with setNetworkTimeout and use SynchronousExecutor in all cases as it needs to be synchronous and to be set 'before' activity.
