### ISSUE TITLE
javax.sql.ConnectionPoolDataSource support

### ISSUE THREAD

**Issue by dimzon** [brettwooldridge/HikariCP#54]
Current HikariCP solution contains of 2 parts
1. Codegen/Proxy related stuff to wrap `java.sql.Connection` to **something like** `javax.sql.PooledConnection`
2. Pool management code itself (inc thread syncronization, lifetime management etc)

Some JDBC drivers provide `javax.sql.ConnectionPoolDataSource` out-of the box. So bytecode generation isn't requred. I propose to split HikariCP for 2 **lose-coupled** parts:
1.   Codegen/Proxy related stuff to generate `javax.sql.DataSource` to exact `javax.sql.ConnectionPoolDataSource` adapter
2. Pool management code to deal directly with  `javax.sql.ConnectionPoolDataSource` api.

In this case you can use both parts if JDBC driver doesn't support `javax.sql.ConnectionPoolDataSource` and only second part otherwise...

**Comment by Glusk2** [comment]
@brettwooldridge - With so much obsolete/unused interfaces in javax.sql have you ever considered suggesting improvements to this API or do you think that it's fine the way it is?

**Comment by ViliusS** [comment]
> I'm sorry, I don't like the idea of splitting the implementation. Ordinary users cannot make an informed choice between the implementations. As I did, user's would need to understand whether their JDBC driver ConnectionPoolDataSource implementation properly resets connection state or not in order to choose it. While this is possible with open source drivers, it is not possible with closed source drivers. And in the end, what is the "win"? The "win" is simply the removal of generated proxies. Frankly, I don't care. It's not worth it to me either in terms of code complexity, or dealing with user issues because they misconfigured their pool. Javassist is practically ubiquitous in server stack dependencies these days, and we haven't had any users clamoring for its removal.

I would like to weight in on that and share recent experience of my own. One of our Java applications use HikariCP and MS SQL JDBC driver. Application just calls stored procedures on MS SQL and returns the result to the user. As mentioned in related mssql-jdbc link above, the driver itself doesn't "reset" the connection before every call. And as mentioned in this ticket, HikariCP doesn't implement `ConnectionPoolDataSource` API. So if there is orphaned transaction on SQL side (for whatever reason), connection gets reused and all hell breaks loose. Temporary tables are not cleared, SELECT queries use exclusive locking, etc. etc. In short, the experience is terrible and debugging such issues takes forever.

You could say that driver itself should implement connection "reset". Probably, but that would be very inefficient because without Pooling API returned from pooling implementation they don't know when the connection is reused. They would need then to send "reset" after every SQL call. Some older JDBC drivers did exactly that, but I see the trend that now more and more drivers start to rely on `ConnectionPoolDataSource` API instead, and this is understandable.

That's why I kindly ask to reconsider this issue. `ConnectionPoolDataSource` API implementation is needed, there is no question about that. The question is how to correctly implement it in HikariCP, so its benefits won't be lost.
