### ISSUE TITLE
QUESTION: Why is the minimum value for connectionTimeout limited to 1000?

### ISSUE THREAD

**Issue by bysse** [brettwooldridge/HikariCP#547]
Hi, we're evaluating this connection pool and i have a question as to why the minimum value of connectionTimeout is limited to 1000 ms?
> This property controls the maximum number of milliseconds that a client (that's you) will wait for a  connection from the pool. If this time is exceeded without a connection becoming available, a SQLException will be thrown. 1000ms is the minimum value. Default: 30000 (30 seconds)

If we have an issue with a single shard we will fill up all available threads on the server waiting for a connection rather than just drop the request straight away. Any thoughts on this?

**Comment by bysse** [comment]
After finding the forums I came across this answer:

> The issue with setting the connectionTimeout too low (for example 10's of milliseconds) is that the connectionTimeout doubles as both the time that the user is willing to wait for a connection from the pool and the time that HikariCP itself is willing to wait when creating new connections to add to the pool.  A timeout in the 10's of milliseconds might be insufficient in many environment to establish and authenticate a new connection.

- https://groups.google.com/forum/#!searchin/hikari-cp/"connectionTimeout"/hikari-cp/ohaKBZma3R0/RPxqIkJ3DRQJ

Which unfortunately makes HikariCP unusable for our  needs.

**Comment by brettwooldridge** [comment]
@bysse What minimum would be sufficient for your use case?

**Comment by brettwooldridge** [comment]
@bysse We can certainly consider a lower floor, but 125ms would be the absolute minimum.

Both Windows and Linux have a default scheduler quantum of 20ms.  If 16 threads are running on a 4-core CPU, a single thread may have to wait up to 80ms just to be allowed to run.  If the pool has a vacancy due to, for example, the retirement of a connection at maxLifetime, this leaves precious little time to establish a connection to fill the slot without returning a *spurious* failure to the client.

If careful consideration is not taken to ensure the CPU and scheduler are not oversaturated, running at a 125ms timeout, puts your application tier at risk of spurious failures even if the pool has available connections.

**Comment by bysse** [comment]
@brettwooldridge Thanks for the response. I would say that the problem as I see it is that the timeout for connecting, and the timeout waiting for a free connection from a full pool is the same. However, since we already have a thin layer that is limiting the number of simultaneous connections to the database we're not affected by the later. I think my initial thoughts was a bit skewed by our solution :)

We do not need to go as low as 125 ms but a smaller connectionTimeout of say 250 - 500 ms would be better.

**Comment by brettwooldridge** [comment]
@bysse I think we can agree to a 250ms floor for the ``connectionTimeout``.

**Comment by bysse** [comment]
@brettwooldridge :+1:

**Comment by brettwooldridge** [comment]
@bysse HikariCP 2.4.4 RC1 [is available](https://groups.google.com/forum/#!topic/hikari-cp/Hp9D-Q8IVtg) for testing.

**Comment by bysse** [comment]
@brettwooldridge Great thanks! We'll increase the number of nodes running Hikari next week then i guess.

**Comment by brettwooldridge** [comment]
@bysse After implementing this fix, I'm one fence about what to do.  The ``connectionTimeout`` should be fine, but the ``validationTimeout`` has constraints imposed by JDBC.

Where possible HikariCP uses the ``Connection.isValid()`` method rather than executing a database query.  However, the ``isValid()`` interface, as defined says:

> timeout - - The time in seconds to wait for the database operation used to validate the
>                  connection to complete.

Similarly, the ``Statement.setQueryTimeout()`` accepts units only in seconds.

I'm going to have to fix the validation code.  As it stands a timeout less than one second is going to round *down* to ``0 seconds``, which is interpreted by the driver (per spec.) as *no timeout*.

**Comment by bysse** [comment]
@brettwooldridge I appreciate your work on this. For our use the 250 ms `connectionTimeout` is sufficient even though there will be different timeouts depending on the previous state on the connection.
However, if you feel that the discrepancies between `connectionTimeout` and `validationTimeout` introduce inconsistencies into the framework then I think that should weigh heavier than a specific feature request.

**Comment by brettwooldridge** [comment]
@bysse It creates more of a documentation issue than anything.

For example, if the driver supports ``setNetworkTimeout()`` which is denominated in milliseconds (MySQL, PostgreSQL), HikariCP will still "time-box" the ``isValid()`` or ``setQueryTimeout()`` calls down to 250ms resolution.

So, setting a ``validationTimeout`` of 250ms *will* be honored if the driver supports ``setNetworkTimeout()``, even though we will call ``isValid()`` with a 1 second timeout.  However, the same 250ms timeout on a driver that doesn't not support setting the network timeout will result in a minimum 1 second resolution.  This will not be apparent to the user and will require documentation to explain.

Not a problem, just an issue.

**Comment by nitincchauhan** [comment]
Even if desirable it is not practical even 'today' is explained in this old thread https://community.oracle.com/thread/552257?start=3
