### ISSUE TITLE
QUESTION: minimumIdle and maximumPoolSize

### ISSUE THREAD

**Issue by victropolis** [brettwooldridge/HikariCP#573]
@brettwooldridge you've mentioned previously that a maximumPoolSize of 100 is enormous, however, if paired with a minimumIdle of say 5, what harm is there in having a high maximumPoolSize to prevent possible connection timeouts in a production environment.

**Comment by victropolis** [comment]
Any thoughts on thie @brettwooldridge ?

**Comment by jnehlmeier** [comment]
If your Database can handle 100 connections without crashing then its fine. If it can not then you have given the client the possibility to crash your server. I am pretty sure you don't want to give a client that much power ;-) 
Its better when things become slower under heavy load because you need to wait for free connections instead of creating lots of connections until the whole server dies. So choose your maximumPoolSize and timeout values wisely.

**Comment by brettwooldridge** [comment]
@victropolis A pool that is larger than your database's capacity to handle connection load is more likely to cause timeouts and degraded performance.

When sizing a pool we always suggest running load tests (there are many open source load testing tools) to find at what connection count the peak performance (TPS) is achieved.  Typically, if you graph connections on the X-axis and TPS (or requests/sec) on the Y-axis you will find that it is a curve that has a peak and drops off to either side.  You want to set your ``maximumPoolSize`` right on that peak.

For example:
![sysbench-ins-del](https://cloud.githubusercontent.com/assets/1538661/13025921/58ae8bc4-d258-11e5-8c7d-de8b3770b748.png)
