### ISSUE TITLE
relax lastAccess setting

### ISSUE THREAD

**Issue by nitincchauhan** [brettwooldridge/HikariCP#576]
With narrower escape validation window and many refactor / updates later, I think it is time to revisit decision to have overhead (in case of read-only or auto-commit connections) of initializing lastAccess in markCommitStateDirty(). earlier it was always set in close() only.

**Comment by brettwooldridge** [comment]
If we *always* set ``lastAccess`` to ``CloseSource.currentTime()`` in ``close()``, as we used to, then the connection can be immediately borrowed without a validation check (bc of the alive-bypass window).  This lead to a rare error where a connection that was borrowed, but never used, was returned to the pool in a disconnected state.  Because we set ``lastAccess`` to ``currentTime()`` in ``close()``, the connection was borrowed without testing, resulting in an error at the application level.

It is important that ``lastAccess`` reflect the last known time that we *know* that the connection was valid.
