### ISSUE TITLE
Class Not Found org/slf4j/LoggerFactory 

### ISSUE THREAD

**Issue by nandhusriram** [brettwooldridge/HikariCP#595]
I am using the HikariCP through spring boot 1.3.3 , HikariCP version 2.4.4 , getting class not found. Here is the exploded WEB-INF/lib.  I do see slf4japi and logback.
<img width="834" alt="screen shot 2016-03-09 at 3 17 16 pm" src="https://cloud.githubusercontent.com/assets/2879342/13650825/2a2f2004-e60a-11e5-9f4f-eb7cf09377ef.png">
<img width="937" alt="screen shot 2016-03-09 at 3 16 50 pm" src="https://cloud.githubusercontent.com/assets/2879342/13650826/2a30459c-e60a-11e5-9dbd-a3e9eb1820e5.png">

Caused by: java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at com.zaxxer.hikari.HikariConfig.<clinit>(HikariConfig.java:51) ~[HikariCP-2.4.4.jar:na]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_60]

**Comment by brettwooldridge** [comment]
@nandhusriram This is a Spring boot classpath issue, I recommend that you ask on stackoverflow or Spring boot forums.  A NoClassDefFoundError cannot be caused by HikariCP itself, it can only be caused the container in which HikariCP is deployed.

You might try enabling verbose debug logging for Spring to help determine the runtime classpath.
