### ISSUE TITLE
allow to configure JMX domain

### ISSUE THREAD

**Issue by turbospaces** [brettwooldridge/HikariCP#629]
right now JMX domain configuration is hard-coded like this
```java
ObjectName beanConfigName = new ObjectName("com.zaxxer.hikari:type=PoolConfig (" + poolName + ")");
ObjectName beanPoolName = new ObjectName("com.zaxxer.hikari:type=Pool (" + poolName + ")");
```
and causes issue when you try to export metrics to GRAPHITE using netflix servo library.

I suggest to externalize configuration of domain to hikari config.

**Comment by asafm** [comment]
Can you please elaborate what trouble this causes you with Servo?

**Comment by turbospaces** [comment]
the problem is in illegal characters in JMX name. there are whitespaces and '(' and ')' characters. I simply suggest to provide ability for client code to be able to use different JMX domain name, not hard-code it into library.

**Comment by brettwooldridge** [comment]
@turbospaces Are you saying that is a limitation of Servo?  Because all of those characters are legal with respect to a [JMX name](http://docs.oracle.com/javase/6/docs/api/javax/management/ObjectName.html).  Nothing that I can find in the Servo documentation speaks about limitations on JMX names.

**Comment by brettwooldridge** [comment]
@turbospaces If the issue is Servo exporting to Graphite, you need to [open an issue](https://github.com/Netflix/servo/issues) against Servo.  They are performing [JMX name mappings in this class](https://github.com/Netflix/servo/blob/master/servo-graphite/src/main/java/com/netflix/servo/publish/graphite/BasicGraphiteNamingConvention.java), and clearly it needs to be expanded to handle other characters.
