### ISSUE TITLE
Is 'dirtyBits & DIRTY_BIT_AUTOCOMMIT) != 0' useless in PoolBase.resetConnectionState method

### ISSUE THREAD

**Issue by kenny319** [brettwooldridge/HikariCP#655]
if ((dirtyBits & DIRTY_BIT_AUTOCOMMIT) != 0 && proxyConnection.getAutoCommitState() != isAutoCommit) {
			connection.setAutoCommit(isAutoCommit);
			resetBits |= DIRTY_BIT_AUTOCOMMIT;
		}

Because the autocommit state has been checked by 'proxyConnection.getAutoCommitState() != isAutoCommit', why is the 'dirtyBits & DIRTY_BIT_AUTOCOMMIT) != 0 ' statement still used?

**Comment by brettwooldridge** [comment]
@kenny319 It is checked because ``ProxyConnection.getAutoCommit()`` unconditionally sets ``dirtyBits |= DIRTY_BIT_AUTOCOMMIT``.  However, the user may start at ``autoCommit=true``, set it to ``autoCommit=false``, and then reset it to ``autoCommit=true``.  In this case, ``dirtyBits & DIRTY_BIT_AUTOCOMMIT) != 0`` is true, however the actual autocommit state has returned to the default, in which case the extra check avoids the ``setAutoCommit()`` call.

**Comment by kenny319** [comment]
@brettwooldridge Just use your scenario as the example,  whether the setAutoCommit() can be avoided still totally depends on the result of 'proxyConnection.getAutoCommitState() != isAutoCommit'. Is there any case can explain '(dirtyBits & DIRTY_BIT_AUTOCOMMIT) != 0' is useful?

**Comment by brettwooldridge** [comment]
Sure, if for example the transaction isolation was dirtied, the resetConnectionState() will be called.  If the autoCommit was *not* dirty, the bit check avoids a call to connection.getAutoCommit(), which is a round trip for many databases.

**Comment by brettwooldridge** [comment]
In other words, getSuoCommit() can be just as expensive as setAutoCommit().
