### ISSUE TITLE
JMX monitoring of connections

### ISSUE THREAD

**Issue by liester** [brettwooldridge/HikariCP#666]
I have been trying for a full day now to get JMX monitoring of my connection pool working.

There is a wiki page under brettwooldridge that documents how to do this:
https://github.com/brettwooldridge/HikariCP/wiki/MBean-(JMX)-Monitoring-and-Management

I attempted to do just that and I am receiving the following error:
![image](https://cloud.githubusercontent.com/assets/6137420/16671948/37b76d5a-4468-11e6-843b-10e40522405c.png)

Here is my code snippet:
![image](https://cloud.githubusercontent.com/assets/6137420/16671986/835dbb9c-4468-11e6-8033-bc2d9502d003.png)

My googling skills haven't yielded many results.  Most seem to imply that this configuration should work.  The datasource jmx does appear, so that is good.  But it doesn't give me all the data I want about the connection pool.
![image](https://cloud.githubusercontent.com/assets/6137420/16672052/1af9f998-4469-11e6-8ac1-81e7fd0a0931.png)

Any help would be much appreciated.  If you need more information just let me know!

Thank you in advance.

**Comment by liester** [comment]
Of course my issue is #666, totally fits!  This is my nightmare!

**Comment by brettwooldridge** [comment]
HikariCP is designed for two different configuration patterns in mind: 1) configuration through the HikariConfig class, or 2) direct configuration of the HikariDataSource.

If your case, you have combined the two, which is not valid.  If you are using the HikariConfig approach, you need to call setRegisterMBean(true) on that object instead of the DataSource.  And that call needs to occur before the HikariDataSource is created.

**Comment by liester** [comment]
You were absolutely right.  As soon as I changed it to be valid it worked as expected.  Thank you for the quick response.
