### ISSUE TITLE
HA and application level fail-over capabilities

### ISSUE THREAD

**Issue by kuroneko25** [brettwooldridge/HikariCP#732]
Hello we are planning to do some HA improvements for our MySQL database and I’m trying to figure out if there is an easy way to accomplish the following with HikariCP:
1) The connection string/IP to the MySQL instance becomes a randomly selected element from one of two IPs (could be N in the future) at the start of a transaction.
2) Failed connections to the IP (with a certain MySQL error code from a predefined list of codes) cause either a reconnect to the other IP or, in the event of an open transaction, an exception to raise making the transaction fail hard. Failure to connect to an IP blacklists that IP’s use for some number of seconds.

Should we build this as a layer on top of Hikari or use an out-of-process proxy to achieve the desired behavior?

**Comment by brettwooldridge** [comment]
@kuroneko25 It depends on whether you will use Master-Master or Master-Slave replication.  Master-master is much easier from an application perspective.  You can use either [HAProxy](https://www.digitalocean.com/community/tutorials/how-to-use-haproxy-to-set-up-mysql-load-balancing--3) or the [built-in replication/load-balancing support](https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-master-slave-replication-connection.html#connector-j-multiple-master-replication) in the MySQL driver.  In the case of the built-in driver, you must use ``autoCommit=false``.

If you use Master-Slave replication , it can be difficult to get it to work reliably with a connection pool when using the MySQL driver.  At a minimum your application must call ``Connection.setReadOnly()`` in order to execute against a slave.

However, because the pool has a *logical* connection to the driver (``ReplicationConnection``), the pool is not able to accurately perform connection validation.  You will rely completely on the MySQL driver to determine which hosts are available.  Using the ``ReplicationConnectionGroup `` object [you can control](https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-master-slave-replication-connection.html) MySQL server registration, slave promotion, etc. from your application.
