### ISSUE TITLE
Large amount of concurrent lead to performance degradation

### ISSUE THREAD

**Issue by wplatform** [brettwooldridge/HikariCP#735]
I have made the contrast with druid data source performance tests, but performance was behind the druid, can you help me analyse
Code is: https://github.com/openddal/openddal/blob/master/openddal-engine/src/main/java/com/openddal/repo/JdbcUpdateWorker.java

HikariCP DataSource:
summary +  95301 in     6s = 16568.3/s Avg:     6 Min:     1 Max:   169 Err:     0 (0.00%) Active: 200 Started: 200 Finished: 0
summary + 831206 in    30s = 27706.9/s Avg:     7 Min:     1 Max:   516 Err:     0 (0.00%) Active: 200 Started: 200 Finished: 0
summary = 926507 in    36s = 25914.8/s Avg:     7 Min:     1 Max:   516 Err:     0 (0.00%)
summary + 809478 in    30s = 26982.6/s Avg:     7 Min:     1 Max:   158 Err:     0 (0.00%) Active: 200 Started: 200 Finished: 0
summary = 1735985 in    66s = 26402.0/s Avg:     7 Min:     1 Max:   516 Err:     0 (0.00%)
summary + 264015 in    11s = 24146.2/s Avg:     6 Min:     1 Max:   308 Err:     0 (0.00%) Active: 0 Started: 200 Finished: 200
summary = 2000000 in    77s = 26080.0/s Avg:     7 Min:     1 Max:   516 Err:     0 (0.00%)

Druid DataSource:
summary +      1 in   0.2s =    4.9/s Avg:    66 Min:    66 Max:    66 Err:     0 (0.00%) Active: 7 Started: 7 Finished: 0
summary + 764453 in    27s = 28526.5/s Avg:     6 Min:     1 Max:   341 Err:     0 (0.00%) Active: 200 Started: 200 Finished: 0
summary = 764454 in    27s = 28312.1/s Avg:     6 Min:     1 Max:   341 Err:     0 (0.00%)
summary + 933438 in    30s = 31114.6/s Avg:     6 Min:     1 Max:   392 Err:     0 (0.00%) Active: 200 Started: 200 Finished: 0
summary = 1697892 in    57s = 29787.1/s Avg:     6 Min:     1 Max:   392 Err:     0 (0.00%)
summary + 302108 in    10s = 30546.8/s Avg:     5 Min:     0 Max:   117 Err:     0 (0.00%) Active: 0 Started: 200 Finished: 200
summary = 2000000 in    67s = 29899.4/s Avg:     6 Min:     0 Max:   392 Err:     0 (0.00%)

**Comment by nitincchauhan** [comment]
@wplatform at-least, one must post configuration and result of each for any comparison.
besides configuration, there are other factors that influence results as well, ie. platform, versions, tools / methods used etc...
Also read [benchmarking](https://github.com/brettwooldridge/HikariCP/wiki/%22My-benchmark-doesn't-show-a-difference.%22)... till the end.

**Comment by brettwooldridge** [comment]
@wplatform Can you share the source of your test?

**Comment by wplatform** [comment]
hi, brettwooldridge 

Code source:
[https://github.com/openddal/openddal/](https://github.com/openddal/openddal/blob/master/openddal-engine/src/main/java/com/openddal/repo/JdbcUpdateWorker.java)

Test program:
[https://github.com/openddal/performance-test](https://github.com/openddal/performance-test)
DataSource was configed on conf/engine.xml

run Mysql Server
 ./openddal.sh start
run jmeter
 ./jmeter -n -t insert.jmx -l insert.jtl (need mysql driver)

The program is a bit complicated, hope these can help to you. Thx!

**Comment by brettwooldridge** [comment]
@wplatform Yeah, I eventually figured out it was jmeter.  You're right, openddal is a bit complicated.  I got it to start (kinda) but the schema is not created/does not exist so the test can't run.  I don't know how to force it to create the schema.  No errors are reported in the log.

Anyway, [last time I checked Druid](https://github.com/brettwooldridge/HikariCP/issues/232) it performed badly when configured with the same reliability guarantees as HikariCP.

But I can tell you, looking at the Druid configuration, it is not a fair comparison due to the different reliability settings.  If you want to benchmark Druid with the same reliability as HikariCP, this would be the configuration:
```xml
<datasource id="db1m" class="com.alibaba.druid.pool.DruidDataSource">
  <!-- New Reliability Properties -->
  <property name="validationQuery" value="/* ping */ SELECT 1" />
  <property name="testOnBorrow" value="true" />
  <property name="maxWait" value="5000" />

  <!-- Existing Properties -->
  <property name="url" value="jdbc:mysql://10.199.188.136:3306/openddal?characterEncoding=utf8&amp;connectTimeout=1000&amp;useConfigs=maxPerformance" />
  <property name="driverClassName" value="com.mysql.jdbc.Driver"/>
  <property name="username" value="root" />
  <property name="password" value="!Passw0rd01" />
  <property name="initialSize" value="16" />
  <property name="minIdle" value="1" />
</datasource>
```

A couple more things.  I recommend no more than 16 connections per pool for either Druid or HikariCP.  I will be surprised if more connections than that actually result in higher throughput.

I also recommend using the ``useConfigs=maxPerformance`` property in MySQL.  If you do use these for the benchmark, make sure to use the same pool size and URL properties for both HikariCP and Druid.

A few points:
 * Druid recommends not setting ``maxWait`` because it impacts performance.  But not configuring it means there is no limit on how long a client might wait.  HikariCP has no trouble honoring a maximum wait time without sacrificing performance.
 * Druid does not implement rollback-on-return of uncommitted Connections.  This means that transactions from a thread that does not ``commit()``, will be committed later by another thread using the same connection.  That is a troubleshooting nightmare; a SQL failure can occur in a completely different part of the code, in a class that had nothing to do with the original SQL, possibly minutes after the original code ran.
 * Druid does not reset SQL warnings between uses of a Connection.
 * Druid does nothing to protect against network partition events.
