### ISSUE TITLE
setConnectionInitSql doesn't work for SQLite

### ISSUE THREAD

**Issue by searhiy** [brettwooldridge/HikariCP#737]
I'm working with SQLite and have to execute "PRAGMA foreign_keys=ON" to enable ON DELETE CASCADE functionality, i.e. 
FOREIGN KEY (book_id) REFERENCES book(id) ON DELETE CASCADE

Trying to do it in such way:
HikariConfig config = new HikariConfig();
config.setJdbcUrl("jdbc:sqlite:mydb")
config.setUsername("sa")
config.setPassword("")
config.setConnectionInitSql("PRAGMA foreign_keys=ON");

I'm using HikariCP latest version: 2.5.1. 

Unfortunately it doesn't work. Any thoughts?

**Comment by brettwooldridge** [comment]
@searhiy Try this trick ... try using "PRAGMA foreign_keys=ON" as the ``connectionTestQuery``.

**Comment by searhiy** [comment]
@brettwooldridge I tried this trick, it doesn't work too. People use Slick on skala, this tool resolves this issue.
For now decided to write trigger...

**Comment by martyn0ff** [comment]
I know this is old, googling led me here. I had this problem as well and was frustrated for quite a bit as nothing offered here worked. Turns out the issue was not HikariCP at all. The reason for my case was that SQLite is sneaky and disables `foreign_keys` pragma in its dumps and does not turn it back on. If you feed your app data dump make sure to turn this pragma back on in however way appropriate in your application. Without connection pool in place it's not a problem and the issue gets especially noticeable when using Hikari to share a single connection.
