### ISSUE TITLE
Warm Connection in Connection pool

### ISSUE THREAD

**Issue by sandeep27st** [brettwooldridge/HikariCP#765]
Hello,

We are planning to  use the HikariCP in our product. Including all connection pooling features, I have informed that we need to add the warm connection concept in the pool. 

Can you please tell me concept behind the warm connection and Is that concept implemented in HikariCP

Thanks.

**Comment by brettwooldridge** [comment]
I can't tell you what the "warm connection concept" is because it is not a technical term.  Maybe you can tell *us* what is meant by that requirement.

By default HikariCP acts as a fixed-size pool.  When run as a variable sized pool, controlled by setting *minimumIdle*, HikariCP will keep *minimumIdle* connections available ("warm") even as usage floats up and down.

**Comment by sandeep27st** [comment]
In your issue [https://github.com/brettwooldridge/HikariCP/issues/256](url) I have seen that after allocating connection, to achieve the minimum idle size, pool "refill" occurs every 30 seconds or so. 
Can I configure to reduce this 30 second time span.

**Comment by brettwooldridge** [comment]
@sandeep27st There is an undocumented system property, ``com.zaxxer.hikari.housekeeping.periodMs``, you can try ``-Dcom.zaxxer.hikari.housekeeping.periodMs=10000`` (10 seconds).
