### ISSUE TITLE
Is there any objection in principle of having an option to test the connection periodically, eg. testFrequency

### ISSUE THREAD

**Issue by stottpaul** [brettwooldridge/HikariCP#766]
Firewalls often blackhole idle connections after a few minutes, and in general DB connections should be kept alive for hours at a time.

Furthermore this could in certain situations be a more efficient alternative to testing on every borrow, with the caveat of the odd connection error.

**Comment by brettwooldridge** [comment]
@stottpaul HikariCP is opposed to idle connection testing.  It generates unnecessary queries to the database, defeats the database configured idle timeouts, takes away control from the network infrastructure team, and does not remove the need for test on borrow.

Regarded as an alternative to test-on-borrow, we do not consider caveat of "the odd connection error" as acceptable, given the time scale between the potential periodic test and a potential borrow.  E.g. there could be tens of seconds between a test and a borrow.  HikariCP contains an optimization for extremely active pools where by the test-on-borrow is bypassed if it was used within the past 500ms.  That is about as far as we're willing to go in terms of eliding an aliveness test.

We consider firewall resets of idle connections to be an issue better addressed at the infrastructure level rather than compensated for by HikariCP.

Taking a Cisco ASA as a typical firewall, the default idle reset timeout is 1 hour.  That is actually quite acceptable, and setting the ``idleTimeout`` in HikariCP to just shy of that would avoid any visible connection errors to pool clients.

Having said that, most firewalls have mechanisms to specify exceptions for idle timeout policies.  In the case of Cisco ASA it is called [Dead Connection Detection](http://www.cisco.com/c/en/us/td/docs/security/asa/asa82/configuration/guide/config/conns_connlimits.html#wp1080752).  For a McAfee Next Generation Firewall it is called [Connection Tracking](http://help.stonesoft.com/onlinehelp/StoneGate/SMC/5.10.3/GUID-0CD08BDC-EDE6-43F1-8F72-DACADB0C5BAB.html).

Having said *that*, it is generally *not* a great idea to keep individual database connections open for hours.  Databases and drivers both track connections internally with sessions, and both have historically been sources of memory leaks.  Allowing drivers and the database itself to release session-associated state periodically improves overall stability.  HikariCP has a default ``maxLifetime`` of 30 minutes.

The cost of replacing a retired connection, due to exceeding idle or lifetime limits, is typically measured in double-digit milliseconds.  If a maxLifetime of 30 minutes is considered, and a pool of 20 connections, you are looking at 20 events, several tens of milliseconds each, occurring in a span of 30 minutes, in the background.  Finding a measurable impact on the application would be challenging.

**Comment by stottpaul** [comment]
Many thanks Brett for a very thorough response to this issue.

We will make efforts to change the firewall policy internally, however just
a couple of thoughts occurred to me whilst pondering your response.

1) It would be really useful if a metric was added to measure the time it
takes for Hikari to create a physical connection to the database, this
would allow us to take a view on whether the recycling of connections is a
potential issue for our system, eg. if it was sub 20ms then probably
nothing to worry about, but if we are talking greater than a second then
that would be a cause for concern.

2) Setting idleTimeout to just shy of the firewall timeout does not really
work, as Hikari does not timeout idle connections if that would violate the
minimumIdle configuration.   I guess this is by design, but in my case I
would prefer it to timeout all idle connections and then just replace them
with new connections to meet the minimumIdle configuration.

If you believe either of these enhancements would be accepted then I will
add them as issues.

Again, many thanks for you response and your ongoing work on HikariCP.

**Comment by brettwooldridge** [comment]
Go ahead and open an issue for adding a new connection setup time metric.

I'm going to make a change so that the housekeeper will, on each run, pick off one (1) connection that has exceeded the idleTimeout even if it is below the minimumIdle threshold.
