### ISSUE TITLE
How can I speed up Hikari with MySQL

### ISSUE THREAD

**Issue by tejalshah84** [brettwooldridge/HikariCP#773]
Hi there Brett,

Thank you for the Hikari pooling library. I have a MySQL backend with 110 Million records and two front-end undertow servers behind ELB using Hikari for connection pooling. My queries are really slow at the moment, each taking about 24 seconds (granted I am yet to index the tables). But I compared Hikari's performance to DBCP on the same table and DBCP was running the query in 21 seconds. I need to get as much throughput as possible. So need to tune Hikari to server as many requests as possible at its max capacity. The throughput requests need to meet target of 7000 RPS for this query and 27000 for other queries. We will optimize the query and also use a larger cluster but how can I set Hikari to give maximum throughput. I am a student and am working on a project where I need to achieve high RPS. My current settings using Hikari 2.4.7 are:

			HikariConfig config = new HikariConfig();

			config.setDriverClassName("com.mysql.jdbc.Driver");
			config.setJdbcUrl("jdbc:mysql://"+"localhost/twitter?useSSL=false&useUnicode=yes&characterEncoding=UTF-8");
			config.setUsername("root");
			config.setPassword("blahblah");
			//config.setMinimumIdle();
			config.setIdleTimeout(0);
			config.setMaxLifetime(0);
			config.setMaximumPoolSize(250);
			config.addDataSourceProperty("cachePrepStmts", "true");
			config.addDataSourceProperty("prepStmtCacheSize", "250");
			config.addDataSourceProperty("prepStmtCacheSqlLimit", "2048");
	
			datasource = new HikariDataSource(config);

Also, is it better to hold on to a connection if I am running one query, then doing a little bit of calculation and then running second query. Or is it better to return the connection and fetch it again after every query. So my option is that the servlet gets the connection and keeps it until done with all operations or returns in intermediate steps. Asking because I am not sure how expensive it is to fetch connection and return repeatedly. I am still learning so sorry for too many questions.
Thank you for your help :)

**Comment by billoneil** [comment]
To start it looks like you have an extremely large pool size. Take a look at https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing your pool size should be much lower.

As far as the optimizations go properly indexing the data and optimizing the queries will most often be more beneficial than optimizing the pool itself. Once you have made a lot of progress there you can look at the pool.

>Also, is it better to hold on to a connection if I am running one query, then doing a little bit of calculation and then running second query.
This is the purpose of a connection pool. Internally it holds onto all of the connections and leaves them open. The difference between manually holding it and letting the pool manage it should be fairly negligible.

You may want to set some MaxLifetime and IdeTimeout.

**Comment by tejalshah84** [comment]
oh..great insight on relation with # of cores. Thank you. So I have a 2 core machine so perhaps about 5-6 would be the pool size. Not sure why would I want IdleTimeout. If it is idle shouldn't it just sit around so a new connection doesn't need to be created when a request finally does come in? Same question for MaxLife, shouldn't it just stay alive forever....as I will need to handle 7000 RPS for roughly 5 hours.

Thank you again.

**Comment by brettwooldridge** [comment]
@tejalshah84 Possibly take a look at [My Benchmark Doesn't Show a Difference](https://github.com/brettwooldridge/HikariCP/wiki/%22My-benchmark-doesn't-show-a-difference.%22).  My guess is that DBCP is "faster" because it is actually not testing connection validity (among other things).  I think if you configure DBCP with the same correctness and reliability guarantees, you'll find that DBCP runs much slower than HikariCP.

**Comment by brettwooldridge** [comment]
@tejalshah84 To answer your other questions.  In the case on HikariCP, obtaining a connection from the pool should typically take an almost immeasurable amount of time.  Therefore I recommend that your servlet:

1) Obtain a connection, run a query, then close the connection.
2) Perform whatever calculation you want to perform -- as long as it takes more than a few milliseconds.
3) Obtain a new connection and run your second query.

However, if the calculation time is less than say 10 milliseconds, it may prove better to hang on to a single connection rather than re-obtaining one.

Regarding ``maxLifetime``, infinite is typically not good.  Drivers and server-side sessions have been known to have leaks, or at a minimum accumulate state that consumes increasing amounts of memory, that is freed by releasing and replacing connections periodically.  Though it is probably perfectly safe to set lifetimes up to 8 hours or more.  Monitoring Java and/or database memory over time can help you determine what the impact of long-lived connections are in your environment.
