### ISSUE TITLE
Less variation for maxLifetime

### ISSUE THREAD

**Issue by pauldraper** [brettwooldridge/HikariCP#782]
We use DNS failover for the database.

This means we need DNS to reresolve periodically.

> maxLifetime
> This property controls the maximum lifetime of a connection in the pool. When a connection reaches this timeout it will be retired from the pool, subject to a maximum variation of +30 seconds. 

A variation of 30s can be a lot. Making the variation smaller, or configurable (say, to 5s) would be very helpful.

**Comment by brettwooldridge** [comment]
Sorry, we need to update our documentation. Connections used to be retired by the housekeeper thread, which runs every 30 seconds.  But maxLifetime retirements fire on their own triggers now and are accurate within several milliseconds.

If you expect DNS to re-resolve though, you'll need to adjust the JVM DNS TTL setting, otherwise the JVM will merely return a cached lookup.
