### ISSUE TITLE
Which version of each library was used for "Bad Behavior: Handling Database Down" tests?

### ISSUE THREAD

**Issue by chinhodado** [brettwooldridge/HikariCP#805]
I would like to know which version of each library was used for the tests on this page: https://github.com/brettwooldridge/HikariCP/wiki/Bad-Behavior:-Handling-Database-Down

Also the tests were done in 2014. Has anything changed since then?

**Comment by brettwooldridge** [comment]
@chinhodado The library versions can be [viewed here](https://github.com/brettwooldridge/HikariCP-benchmark/blob/cd9056f25f555a328d0c0dfa5851a6061107ef1b/pom.xml).

According to the author of the Vibur pool, they now handle this situation.  A quick test (rather than a full re-test) run by myself last summer seems to verify that.

The test code is [part of the HikariCP-benchmark](https://github.com/brettwooldridge/HikariCP-benchmark/blob/master/src/main/java/com/zaxxer/hikari/benchmark/DbDownTest.java) project.  If you are interested in running it, I would certainly be interested in your results, based on the latest published versions of the libraries involved.
