### ISSUE TITLE
2.3.9 to 2.4.11 - 25% Degradation of Performance

### ISSUE THREAD

**Issue by andysenn** [brettwooldridge/HikariCP#820]
First of all, I want to thank you for your timely response to issue #600. The latest "*-java7" artifact (2.4.11) is functional on Java 7. Unfortunately, after upgrading from 2.3.9, we've seen about a 25% degradation of performance, measured in "transactions" per second with our software.

Our automated performance tests were run against our product using the commits immediately preceding / following the HikariCP dependency change in the POM.

I am in the process of digging for more information, but I was wondering if you would be able to either:

1) Perform your benchmarks using the two aforementioned versions to corroborate the issue we're seeing
2) Explain any legitimate reason why the performance would have degraded (e.g. it's performing additional work that is necessary for the stability and reliability of the connection pool)
3) Tell us that everything is fine, nothing is broken, and the issue is solely our fault

This presents once the service is under load (~100 concurrent Tomcat threads). Aside from a change from HikariCP 2.3.9:*-java6 to 2.4.11:*-java7, the performance testing environment remained exactly the same. I've double and triple checked many of the fine details with them, and I requested the pertinent configuration files from both runs to verify that nothing had changed. I've explained to them that our default configuration of a minimum pool size of 5 and a maximum pool size of 90 is not ideal for a box with 8 physical (16 logical) cores and an SSD, but those settings were consistent across all of their test runs. After rolling back to 2.3.9:*-java6, performance returned to normal.

For now, we are okay with rolling back to 2.3.9:*-java6, but would like to benefit from the many changes that have taken place since. I've read through the documentation for any significant configuration changes, but didn't see anything that I perceived to be pertinent.

If more details come to light, I will make sure to share them here.

Thank you!

**Comment by brettwooldridge** [comment]
@andysenn 

Just as a level set I ran our standard benchmark on 2.3.9:
```
Benchmark                       (jdbcUrl)  (maxPoolSize)  Mode  Cnt      Score      Error   Units
ConnectionBench.cycleCnnection  jdbc:stub             32  thrpt   16   9749.378 ±  201.532  ops/ms
StatementBench.cycleStatement   jdbc:stub             32  thrpt   16  57119.593 ± 4468.053  ops/ms
```
And on 2.4.11:
```
Benchmark                       (jdbcUrl)  (maxPoolSize)  Mode  Cnt      Score       Error   Units
ConnectionBench.cycleCnnection  jdbc:stub             32  thrpt   16  43880.048 ±  3210.205  ops/ms
StatementBench.cycleStatement   jdbc:stub             32  thrpt   16  94296.275 ± 10887.648  ops/ms
```
So, at a high-level, at least at the application→pool layer, things should be faster.  It is going to take some more investigation to see what is occurring at the pool→DB layer that could be affecting performance.

Can you tell me what JVM version you guys are running (e.g. 1.7.0_55-b13)?  And the exact pool configuration (excluding passwords, of course)?

**Comment by brettwooldridge** [comment]
@andysenn Also, is it possible to run the pool with debug logging enabled for the ``com.zaxxer.hikari`` package and collect some of the logs from the run?

**Comment by brettwooldridge** [comment]
@andysenn It would still like to see the configuration, and debug log, but having looked at the differences between 2.3.9 and 2.4.11 I did spot one difference.

#### Alive Bypass Window
HikariCP (all versions) contains an optimization that basically says, "If a connection was used within the last X milliseconds, skip the connection validation check because we assume it is still valid."  We call this the "alive bypass window".

In v2.3.9, the bypass window size was 1000ms.  In v2.4.11, the bypass window is 500ms.  And in v2.6.0, which you are not using, the bypass window is now 250ms.

So, Hypothesis One is that in under load, probably due to OS thread scheduling (if there are indeed 100 threads), connections are sitting in the pool beyond the 500ms v2.4.11 bypass cutoff.  For example, under v2.3.9, if a connection was returned by not borrowed for 700ms, it still fell under the 1000ms bypass cutoff and would not be validated.  But under v2.4.11, the same connection *would* be validated.

While validation is typically not that expensive, it is still a roundtrip to the database, and if it were occurring with higher frequency you would observe a difference.

If you want to test Hypothesis One, you can set a system property that controls the bypass window size to the same as v2.3.9, then run your load test again:
```
-Dcom.zaxxer.hikari.aliveBypassWindowMs=1000
```
If the load test still shows a discrepancy, we'll need to dig further (\*cough\* logs).

**Comment by andysenn** [comment]
I'm going to go ahead and close this for now. I don't feel good about the current state of this issue. I feel like something is amiss in our performance testing environment, but my team doesn't have full visibility into it. I'm working on doing some testing of my own, and I'm not seeing the results they're seeing. I will re-open this if I find anything groundbreaking.

I apologize for the inconvenience. I am shamed, sir. :)
