### ISSUE TITLE
How to specify the username properly? Tomcat8 error: Could not connect: Access denied for user ''@'localhost'

### ISSUE THREAD

**Issue by rustyx** [brettwooldridge/HikariCP#822]
I am using HikariCP-java7 2.4.11 with mariadb-java-client 1.5.8.
I create the dataSource Spring bean manually like this:
`new HikariDataSource(new HikariConfig("/datasource.properties"))`

My `datasource.properties` contains:
```
driverClassName=org.mariadb.jdbc.Driver
jdbcUrl=jdbc:mysql://localhost:3306/mydb
username=myuser
password=
dataSource.useUnicode=true
dataSource.characterEncoding=UTF-8
dataSource.useDynamicCharsetInfo=false
minimumIdle=15
maximumPoolSize=100
```

It **works** in Tomcat7 and Tomcat8 on Windows and in Tomcat7 on FreeBSD, but **fails** in Tomcat8 on FreeBSD with:
`org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Access denied for user ''@'localhost' to database 'mydb'`

To fix this I change the username/password lines line this:

```
dataSource.username=myuser
dataSource.password=
```

Then it works in Tomcat8 on FreeBSD but fails everywhere else.

The question is - what's going on? And what's the correct way to specify those? The documentation is **very unclear** on this. Help!

**Comment by Rugal** [comment]
Hi @rustyx ,

According to [code](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/util/PropertyElf.java#L45), you could set properties regardless of the "datasource." prefix.

**Comment by brettwooldridge** [comment]
@rustyx According to the [MariaDB documentation](https://mariadb.com/kb/en/mariadb/about-mariadb-connector-j/#using-external-pool) it seems that the preferred method is to use a ``dataSource.`` property.

When using the raw ``username`` or ``password`` properties, and at the same time using a Driver-based (``jdbcUrl``-based) configuration, HikariCP doesn't really know whether the driver would prefer ``username`` or ``user`` as a property.  It [makes a guess](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/util/DriverDataSource.java#L50) and uses ``user`` as a driver property.  This is [correct for MySQL](https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-configuration-properties.html), for example, but not correct for every database. 

When using a DataSource-based configuration, HikariCP can always obtain a connection because the [API defines method](https://docs.oracle.com/javase/7/docs/api/javax/sql/DataSource.html) -- ``getConnection(username, password)`` -- that is consistent.

However, both the MariaDB and MySQL DataSource implementations have serious issues, such as not implementing ``setNetworkTimeout()``, so it is better to stick with a ``jdbcUrl`` driver-based configuration.

**Comment by rustyx** [comment]
The problem seems to have been totally unrelated - the MariaDB driver incorrectly reports authorization errors - the username in the error message is always blank (as in `Access denied for user ''@'localhost' to database 'mydb'`, whereas the user was in fact `'myuser'@'localhost'`).
My original code with just `username=myuser` works fine.

**Comment by rustyx** [comment]
The issue was this:
https://jira.mariadb.org/browse/CONJ-432
On *NIX, the mariadb driver incorrectly reports "access denied" errors.
