### ISSUE TITLE
Action on Connection leak detection

### ISSUE THREAD

**Issue by Ni3Aphle** [brettwooldridge/HikariCP#823]
Hi,
I am trying to use hikari cp in my project. I came across the connection leak detection feature of the library. This seems to be a cool feature which will help identify that a connection is not returned to the pool for long.

As per my current knowledge, whenever a connection leak is detected, hikari cp just logs the possible connection leak with the stack trace.
I wanted to know whether hikari cp provides any hook on top of it to handle the leaked connection. A straightforward case would be to force close the connection. (either return the connection to the pool or directly have it closed).

We have observed cases where a Teamcenter connection was stuck in use for long and user would eventually want to kill the operation (indirectly the connection) so that other operations could proceed. If this happened for many connections, the only option left to the user is to restart Teamcenter which would kill all open connections. But this is the last and hardly preferred option.

Please let me know what can be done for such connection leak cases using Hikari CP.

**Comment by brettwooldridge** [comment]
@Ni3Aphle I understand what you are asking for, but it goes against the core philosophy of HikariCP.  HikariCP is happy to help identify connection leaks, but it is expected that the developer will fix them.  HikariCP will not "sweep them under the rug" but assassinating them for you.  Some pools do provide that capability, Tomcat for example.

But it seems what you are taking about is a run-away query and not a connection leak.  JDBC itself provides the mechanism for dealing with those cases -- a query timeout on the Statement.  If a query or connection is truly "stuck" due to some database issue, nearly every database provides the ability to kill connections from the database-side, rather than the client side.
