### ISSUE TITLE
Explicitly shutdown connection pool does not reject getConnection, blocks until timeout (Hikari 2.4.9)

### ISSUE THREAD

**Issue by noahlz** [brettwooldridge/HikariCP#861]
#### Environment
```
HikariCP version: 2.4.9
JDK version     : 
  java version "1.7.0_55"
  Java(TM) SE Runtime Environment (build 1.7.0_55-b13)
  Java HotSpot(TM) 64-Bit Server VM (build 24.55-b03, mixed mode)
Database        : MS SQL
Driver version  : jTDS 1.3.1
```
-----------------------------------------------------------------------------------------

We had a bug in our code where we were accidentally calling `HikariPool.shutdown()` - and then subsequent application threads were attempting to call upon this pool with `getConnection`

Even though this pool was in a closed, shutdown state, it did not "reject" the `getConnection` call ("IllegalStateException: pool is closed") or somesuch.  Instead, it blocks these calls until the timeout.  This caused long pauses / slowness in our application  due to blocking on a pool that was forever empty.

Before investigating submitting a patch with the desired behavior (fail-fast after pool is closed), I'm curious if the existing behavior is intentional?  Any other thoughts?

I noticed that `private volatile boolean closed` is used to prevent adding new connections to the pool, but getConnection chugs along none the wiser of the closed state. I would expect a check before each `getConnection`? 

Obviously, we're fixing our code to NOT call `HikariPool.shutdown()` unless we really mean it :roll_eyes:

**Comment by brettwooldridge** [comment]
@noahlz The behavior is in fact the result of a conscious decision.  While somewhat undesirable on the margins, I still feel it is worth the benefit.

What benefit?  *Performance.*

The assumption is/was that if a pool is shutdown (an explicit action) and yet an application continues trying to use it, the application will fall over rather quickly, probably noticeably, and possibly spectacularly. &nbsp; Which is OK, because getting a stream of timeout exceptions is not so different in terms of an application failure mode than a stream of ``IllegalStateExceptions``.  Granted, the timeout exceptions come at a slower pace.

As a side note, ``IllegalStateException`` would be an unchecked exception and would not be the desired exception.  ``SQLNonTransientException`` would be correct, were it to be thrown.

So what specifically about performance?

Well, the alternative would be a ``volatile`` memory access in the "hot path", checking the ``closed`` state. &nbsp; "Hot path" meaning that it would be accessed on *every borrow* from the pool.  And yet, it would be an access that for 99.999bar% of accesses is always ``false``.  In fact, in a *properly designed* application the check would serve no purpose; it merely throws a different exception in the marginal case.  However, it *would* impact performance.

``volatile`` variable access is not free.  It creates a [LoadLoad/LoadStore](http://gee.cs.oswego.edu/dl/jmm/cookbook.html) barrier.  The *LoadLoad/LoadStore* barrier creates a prohibition against re-ordering optimizations by both the compiler and CPU, which in turn affects the performance of surrounding code.

At one point we had a check for ``closed`` in the hot path, but it caused a 5% hit when benchmarked.  And as noted above, it represents optimizing for the 0.000001% case over the 99.999999% case.

**Comment by noahlz** [comment]
Thank you! Yes, our application was defective in closing the pool prematurely. This is the sort of answer I was looking for - closing.
