### ISSUE TITLE
Property url does not exist on target class com.informix.jdbcx.IfxDataSource

### ISSUE THREAD

**Issue by kksingh029** [brettwooldridge/HikariCP#916]

**Comment by nunnr** [comment]
The Informix driver class has not got a URL property. The required properties are listed here: https://docs.oracle.com/cd/E19575-01/821-0185/beanj/index.html

From that guide:
serverName - Specify the Informix database server name.
portNumber - Specify the port number of the database server.
user - Set as appropriate.
password - Set as appropriate.
databaseName - Set as appropriate. This is optional.
IfxIFXHost - Specify the host name or IP address of the database server.

So instead of spring.informix.datasource.dataSourceProperties.url=
You need multiple properties:
spring.informix.datasource.dataSourceProperties.serverName=...
spring.informix.datasource.dataSourceProperties.portNumber=...
...and so on.

**Comment by kksingh029** [comment]
this is url string 
#spring.informix.datasource.dataSourceProperties.url = jdbc:informix-sqli://CISCO-UCCE-EXP:1504/ddd_cra:INFORMIXSERVER=cisco_ucce_exp_uccx; Protocol=onsoctcp; client_locale=en_US.57372; db_locale=en_US.57372
so I split into this way
spring.informix.datasource.dataSourceClassName=com.informix.jdbcx.IfxDataSource
spring.informix.datasource.dataSourceProperties.serverName=CISCO-UCCE-EXP
spring.informix.datasource.dataSourceProperties.portNumber=1504
spring.informix.datasource.dbcp2.pool-prepared-statements=true
spring.informix.datasource.dataSourceProperties.IfxIFXHost = cisco_ucce_exp_ucc

java.lang.RuntimeException: Property IfxIFXHost does not exist on target class com.informix.jdbcx.IfxDataSource

so I opened the jar of informix with class com.informix.jdbcx.IfxDataSource

    Properties prop = getDsProperties();
    
    host = prop.getProperty("IFXHOST");
    port = prop.getProperty("PORTNO");
    connType = prop.getProperty("CONNECTIONCLASS");
    if (connType.equals("com.informix.jdbc.IfxSqliConnect")) {
      if ((host != null) && (port != null)) {
        urlString = host + ":" + port;
      }
    }
    
so I changed  
spring.informix.datasource.dataSourceProperties.IFXHOST = cisco_ucce_exp_uccx
but i got this 
java.lang.RuntimeException: Property IFXHOST does not exist on target class com.informix.jdbcx.IfxDataSource
	at com.zaxxer.hikari.util.PropertyElf.setProperty(PropertyElf.java:155) ~[HikariCP-2.4.7.jar:na]
kindly help me out

**Comment by kksingh029** [comment]
it was resolved
