### ISSUE TITLE
Prepared statements executed in batches are leaked

### ISSUE THREAD

**Issue by guidomedina** [brettwooldridge/HikariCP#918]
#### Environment
```
HikariCP version: 2.6.2
JDK version     : 1.8.0_131
Database        : PostgreSQL
Driver version  : 42.1.1
```
-----------------------------------------------------------------------------------------

It seems that `ConnectionProxy` is keeping the `PreparedStatement` as a result of `PreparedStatement.addBatch()`, one would expect them to be cleared out when you call `PreparedStatement.executeBatch()` but they are not.

They are only being GCed once the connection is returned to the pool.

This is being used to accomplish something like:
https://stackoverflow.com/questions/12100550/using-prepared-statement-multiple-times-efficiently

When the batch is executed or cleared `FastList<Statement> openStatements` is not being cleared:
https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/ProxyConnection.java#L62

**Comment by guidomedina** [comment]
When the batch is executed or cleared, this guys is not being cleared:
https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/ProxyConnection.java#L62

**Comment by brettwooldridge** [comment]
Statements are removed from the *openStatements* collection when they are closed:

https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/ProxyStatement.java#L70

If statements are *not* closed explicitly then they are closed when the connection is closed.

**Comment by guidomedina** [comment]
That's the issue, imagine executing millions of inserts in batches of 1000, the million of statements are kept until the end.

**Comment by guidomedina** [comment]
I'll get to the bottom of this when I get back to that project on Tuesday, seems to be related to `addBatch` adding to `FastList` but I don't know how if HikariCP proxy classes never implement `addBatch` method which is driving me crazy.

How can the PG driver add a `PreparedStatement` to the `FastList` via `addBatch`, so I will debug to track down what's really going on.

**Comment by brettwooldridge** [comment]
@guidomedina Just to be clear:

 * When you call ``Connection.prepareStatement()``, the  new ``PreparedStatement`` is added to the ``FastList``.
 * When you call ``PreparedStatement.close()`` the statement is removed from the ``FastList``.
 * Additionally, when you call ``Connection.close()`` then any statements which *have not been explicitly closed* are removed from the ``FastList`` (and closed).

**Comment by guidomedina** [comment]
I do know that, but what's happening is the following:
- We create a `PreparedStatement` which is added to the `FastList` which is expected.
- We set the parameters and add the the batch.
- When the batch reaches a limit, we execute it.
- Repeat.
- Then finally we close the `PreparedStatement`

What seems to be happening is that add batch is adding `PreparedStatement` to the `FastList` which ends up filling up to hundreds of thousands until the PS is closed.

What we expected to happen is that every time you execute a batch, the 100 PSs added so far would be also removed from the `FastList`, to be clear, we only call `createPreparedStatement` once.

I will investigate more as this might be something funny being done by the driver.

**Comment by brettwooldridge** [comment]
@guidomedina As far as I can tell, it is literally impossible for ``addBatch()`` to add anything to the ``FastList``.  ``PreparedStatement.addBatch()`` is not intercepted by HikariCP, which means the call is invoked directly against the ``PgPreparedStatement`` implementation.  The ``PgPreparedStatement`` class knows nothing of HikariCP and has no reference (direct or *indirect*) to the pool.

I note in your original comment you said:
> It seems that ConnectionProxy is keeping the PreparedStatement as a result of PreparedStatement.addBatch(), one would expect them to be cleared out when you call PreparedStatement.executeBatch() but they are not.

To be clear, calling ``executeBatch()`` will neither clear the batch, nor remove it from the ``FastList``.  The only thing that "clears the batch" is calling ``PreparedStatement.clearBatch()``.  And the only things that can remove the ``PreparedStatement`` from the ``FastList`` is either ``PreparedStatement.close()`` or ``Connection.close()``.

Since you seem to be using Java 8, I **strongly** suggest using *try-with-resources*:
```java
try (Connection con = dataSource.getConnection();
     PreparedStatement stmt = con.prepareStatement(...)) {

  int batchCount = 0;
  for (something in somelist) {
    stmt.setString(...);
    stmt.setInt(...);
    stmt.addBatch();

    if (++batchCount == 100) {
      stmt.executeBatch();
      stmt.clearBatch();
      batchCount = 0;
    }
  }

  if (batchCount > 0) {
      stmt.executeBatch();
      stmt.clearBatch();
  }

  con.commit();
}
catch (SQLException e) {
   // log error
}
```
There should be:
 * *one* call to ``DataSource.getConnection()``
 * *one* call to ``Connection.prepareStatement()``
 * *many* calls to ``PreparedStatement.addBatch()``
 * a handful of calls to ``PreparedStatement.executeBatch()/clearBatch()``

**Comment by guidomedina** [comment]
We found the root cause, old code before the place we thought it was causing the problem had created Statements without closing them, sorry for the hassle, closing the issue as well.
