### ISSUE TITLE
Connection is not available / Apparent connection leak detected

### ISSUE THREAD

**Issue by KITSAntonioTerreno** [brettwooldridge/HikariCP#923]
#### Environment
```
HikariCP version: 2.6.0
JDK version     : openjdk version "1.8.0_131"
Database        : PostgreSQL 
Driver version  : 9.4.1212
```
-----------------------------------------------------------------------------------------

Hi, 
while running some performance tests we hit a 
```
java.sql.SQLTransientConnectionException: products-api - Connection is not available, request timed out after 5002ms.
```
Exception, the config for hikari is: 

```
        hikari:
            leak-detection-threshold: 5000
            maximum-pool-size: 25
            connection-timeout: 5000
            pool-name: products-api
```
To investigate we turned the hikari logging to debug, and the leak detector shows a leak:
```
java.lang.Exception: Apparent connection leak detected
```
Our Gatling test runs with these values: 
200 concurrentUsers for 30 minutes 400 rps, if you are familiar with gatling, here's the scenario: 
```
  setUp(
    scenario("ProductSimulation").exec(test).inject(
      rampUsers(concurrentUsers) over 1.minutes
    ).throttle(
      reachRps(rps) in 30.minute,
      holdFor(30.minutes)
    )
```
The app runs on springBoot (1.5.3.RELEASE) and it's deployed on amazon EC2, we have 4x c4.xlarge instances, the RDS is a db.m4.xlarge, when under load autoscale up to 8x instances. 

If I look at the stack trace the code that is causing the DB issues is as straight forward as it can be, a controller, calling a service, calling a JPA repository doing a db query. 

The only a 'bit peculiar' that we do on our code base are: 

- we do have few standard rows and then an xml object in postgres, that's quite big in size, so I wonder if the total amount of data to return from the rds instance is that big that takes too long under heavy load, we also parse on the fly the xml, so that might take some time
- one of the queries under the lens is asking for 1000 database objects, in order to then perform by-id queries on those object, it's quite a lot of data transfer, the xml is ~ 20K, so that sums up to 2.5Mb

The RDS instance is doing rather fine: 
- Read Throughput (max):  614 Bytes/Sec
- Db connections (max): 250 (25*8 for this app and then there's 25+25 for two other apps which write on the db but were idle at the time of the tests) 
- CPU (max): 50%

I do struggle setting up the connectionPool, is 25 a too low number? is 5 seconds for leak and timeout detection too low? 

Thanks a lot

**Comment by brettwooldridge** [comment]
5 seconds *may* be too low (but maybe not).  You might want to [configure postgresql to log long queries](https://www.drupal.org/docs/7/guidelines-for-sql/logging-slow-sql-queries-server-side-in-postgresql) (set time as appropriate).

It is possible that the PostgreSQL query is fast, but processing the ``ResultSet`` is slow, due to parsing.  2.5MB does not see like a lot to transfer, in general, on the AWS 1Gbit/10Gbit network, but the processing may be slow.  In that case, you will need to profile your application instead of the database -- I recommend *sampling* over *instrumentation* for such high requests rates.

**Comment by spike01** [comment]
Hi @brettwooldridge, thanks for your response (I am/was on the same team as @KITSAntonioTerreno)

As I suspected, the problem was not a Hikari one - we were seeing a lot of SQLTransientConnectionException as certain queries were being held on to by Hibernate for no particularly good reason. It took rewriting a few queries as pure JDBC queries to find this out, and fully investigating the "leaked" connections, which would sometimes only return to the pool after 4-5 seconds, which 

Setting hibernate.connection.releaseMode to after_transaction made a huge difference and means we're now achieving decent performance with 20 connections. Bizarrely, the Hibernate docs seem to suggest that in most cases after_transaction is the default setting, but considering the difference we've seen after setting it, that doesn't seem to be the case.

Also, upping Hikari's connection-timeout eliminated any remaining errors. For any people facing similar issues, I'd say that really investigating when Hikari flags a connection leak (whether it's a real leak or just a connection taking too long to return to the pool) is pretty crucial. Hibernate seems to hang on to stuff for no good reason which is really annoying.

**Comment by brettwooldridge** [comment]
@spike01 Awesome, glad to hear you chased it down!  Hopefully this will help other/future Hibernate users.

We moved our entire application off of an ORM (H*bernate), replaced with [SansORM](https://github.com/brettwooldridge/SansOrm).  It was extremely painful (took the better part of two weeks), but our object-relational mappings were few and the ORM was basically acting as a way to jam POJOs into individual tables (with a few notable exceptions).
