### ISSUE TITLE
Adder thread execution behaviour

### ISSUE THREAD

**Issue by sandeep27st** [brettwooldridge/HikariCP#934]
#### Environment
```
HikariCP version: 2.4.11
JDK version     : 1.7.0_25
Database        : Oracle
Driver version  : x.x.x
```
-----------------------------------------------------------------------------------------
Hello,

In Hikari, adder thread of pool only accepts one task at a time(I found out after digging through code), hence connection creation is simultaneous operation. 

`  /**
    * Create a ThreadPoolExecutor.
    *
    * @param queue the BlockingQueue to use
    * @param threadName the thread name
    * @param threadFactory an optional ThreadFactory
    * @param policy the RejectedExecutionHandler policy
    * @return a ThreadPoolExecutor
    */
   public static ThreadPoolExecutor createThreadPoolExecutor(final BlockingQueue<Runnable> queue, final String threadName, ThreadFactory threadFactory, final RejectedExecutionHandler policy)
   {
      if (threadFactory == null) {
         threadFactory = new DefaultThreadFactory(threadName, true);
      }

      ThreadPoolExecutor executor = new ThreadPoolExecutor(1 /*core*/, 1 /*max*/, 5 /*keepalive*/, SECONDS, queue, threadFactory, policy);
      executor.allowCoreThreadTimeOut(true);
      return executor;
   }`
In our product, migration case solution is used to connect to Teamcenter. The connection creation time for Teamcenter is 30 seconds per connection.

So when there is spike demand in requirement to create maximum 50 connections ( In case of migration, since we have bulk task, we need to create these many transactions with connections). Since, it requires 30 seconds per connection, total time required to create 50 connections is 1500 sec (25 min) and  perform tasks, but, in between many requests get timed out.

Can we have parallel connection creation(by increasing thread execution) to avoid this scenario?

**Comment by brettwooldridge** [comment]
There is no plan to support multithreaded pool filling. It is not as trivial as simply adding threads.
HikariCP is highly optimized for (biased toward) pool consumption, not population, and rightly so.

The use case where connection creation takes three or four orders of magnitude longer than is typical does not justify a significant complication of the code.

You can probably find many places within the site documentation where we recommend running HikariCP as a fixed-size pool in order to provide consistent response even to spike demands. That is true even for databases where acquisition costs are measured in single digit milliseconds.

If you cannot run as a fixed size pool, I would recommend looking at Apache DBCP. Connection acquisition will occur on your own threads, synchronously, but in your case the loss of performance in other areas may be worth the trade off.
