### ISSUE TITLE
Is MariaDbDataSource buggy with network timeout support?

### ISSUE THREAD

**Issue by mohsen** [brettwooldridge/HikariCP#935]
This note is put on project homepage:

> MySQL and MariaDB DataSources are known to be broken with respect to network timeout support. Use jdbcUrl configuration instead

`org.mariadb.jdbc.MySQLDataSource` is now deprecated in favor of `org.mariadb.jdbc.MariaDbDataSource`. Does the issue persist? If yes please also mention `org.mariadb.jdbc.MariaDbDataSource` in README.

**Comment by brettwooldridge** [comment]
Do me a favor, look at the source of that class, at the setNetworkTimeout() method.  If it doesn't do anything, it's still an issue.

**Comment by zimmi** [comment]
I went ahead and checked and it turns out it [does something useful](https://github.com/MariaDB/mariadb-connector-j/blob/ed81a136efa7cd128d6c5a00ba95861b230a4504/src/main/java/org/mariadb/jdbc/MariaDbConnection.java#L1529).
The protocol instance [does something useful](https://github.com/MariaDB/mariadb-connector-j/blob/ed81a136efa7cd128d6c5a00ba95861b230a4504/src/main/java/org/mariadb/jdbc/internal/protocol/AbstractQueryProtocol.java#L973) as well.

**Comment by brettwooldridge** [comment]
@zimmi Project page updated.
