### ISSUE TITLE
Fail fast when adding new connections?

### ISSUE THREAD

**Issue by bcoughlan** [brettwooldridge/HikariCP#938]
We use Hikari to manage pools of connection pools to many different database servers. Hikari's exponential backoff/retry behaviour is problematic for this use case, as if there is an issue connection to one database it can quickly block up request threads for the whole service.

Any appetite for a pull request for an option to not retry (or a maxConnectionAttempts parameter) on the pool when creating new connections?

**Comment by johnou** [comment]
I'm not quite sure I understand how one failing database can cause other pools to block, can you provide some thread dumps of when you are experiencing issues?

**Comment by bcoughlan** [comment]
@johnou I don't mean that the other connection pools are blocked. I mean that a _request_ thread (e.g. the Jetty pool in a web environment) is blocked waiting for the connection pool, and if requests for that pool arrive faster than the timeout then eventually our whole pool gets blocked.

**Comment by brettwooldridge** [comment]
I still don't understand.  Application threads request a connection and block until the timeout occurs.  

Connection acquisition to keep the pool filled occurs on an independent thread.  This independent thread should never give up trying to refill the pool, so a maximumConnectionAttempts parameter makes no sense.  If this thread were to "give up", the entire pool would stall, never to recover.

As stated, the acquisition thread is completely orthogonal to application threads.  It can run even when there are no threads requesting connections.  Application threads are merely waiting for free connections to appear in the pool, and independently the acquisition thread adds connections to the pool -- possibly to be consumed immediately or not.

If service API X needs pool A, and API Y needs pool B, but *both* execute requests from a shared thread pool -- for example, the web server request thread pool -- then, yes, it is possible for an outage in pool B to block requests to service X, even though X does not depend on B.

This is a shared resource coupling that is "above" the pools, and there is nothing HikariCP can do to mitigate that.  What is needed is a decoupling at the application layer.  X and Y should not share the same thread pool with respect to the database pool.  You need (at least) a thread pool for handling requests to X, and a separate thread pool for Y.

Whether you can achieve this through web server configuration or not is a research question for you.  If the web request thread pool *must* be shared you will have to employ something like continuations *in addition to* independent thread pools at the application layer in order to avoid blocking request threads.
