### ISSUE TITLE
Use a strongly-typed exception for connection timeouts

### ISSUE THREAD

**Issue by bturner** [brettwooldridge/HikariCP#951]
When `HikariPool` times out acquiring a connection, it calls `createTimeoutException`, which returns a `SQLTransientConnectionException` that indicates acquiring a connection timed out in its message. That makes trying to apply handling for timeouts difficult and brittle, because the only thing I can do is parse the exception message to detect timeouts.

Let me provide a specific use case. For Atlassian Bitbucket Server, we provide a plugin framework which allows third-party developers to extend and augment the system. That extensibility includes access our database. The server is configured with default limits to how many connections are allowed, and how long it's allowed to wait to acquire a connection. However, since we (essentially) allow arbitrary code execution, in the form of custom add-ons, we have limited control over how long connections may be held.

Further complicating things, clustered installations use Hazelcast to communicate between nodes, and it's possible for a remote operation to be triggered while a thread is holding a connection. We're continuously working to reduce the number of places where this can happen, but for some things, short of abandoning Hazelcast (a massive undertaking), we can't eliminate the possibility completely.

When an instance "runs out" of database connections, inevitably it comes back through our support. When that happens, one of the first things we do is ask the administrator to provide a thread dump taken while all connections are in use so we can see where they're being used. That allows us to make improvements to our own code, as well as reach out to third-party developers with suggestions.

To eliminate that step, I want to add some logic that, when all connections are in use, automatically logs the stack traces for every thread which holds a connection. We already track which thread is using a connection, so I "just" need to log them.

That's where this request comes in. Currently, my only option is to catch `SQLTransientConnectionException`s thrown by the pool and check their messages for "Connection is not available, request timed out". It would be better if some richer exception was thrown. `SQLConnectionTimeoutException extends SQLTransientConnectionException` would not break compatibility for existing handlers, and would provide a strong type to catch to eliminate message parsing when handling is specifically targeting timeouts.

**Comment by brettwooldridge** [comment]
The underlying database exception, if there is one, should be available by calling getNextException() on the exception thrown by HikariCP.  Is that not sufficient?

**Comment by bturner** [comment]
If the pool is at its max size and a connection is not returned before the timeout expires, the exception thrown has no cause or next exception, and can only be identified by parsing the message. This isn't a `ConnectException`, as in a socket level timeout; it's a timeout waiting for a connection from the bag to become available to borrow.

**Comment by brettwooldridge** [comment]
Then I would argue that *is* a strongly typed exception.  We used to throw SQLException.  If we were to throw a different exception, it would be a standard one, not a HikariCP specific subclass.

**Comment by bturner** [comment]
...so I _shouldn't_ be able to tell a timeout apart from other failures trying to get a connection without string-matching your message--which could change in any release without warning and break my check? That doesn't make any sense. The "standard" exceptions aren't `final` for a reason. If you threw a subclass, anyone who doesn't care about the difference can continue to catch the "standard" exception, but for applications where the difference between a timeout and other types of failures matter wouldn't have to resort to brittle string comparisons to tell the two apart.

**Comment by brettwooldridge** [comment]
You *should* be able to tell without resorting to string comparison.  If the "next" exception is null, it was a simple pool timeout, all connections were in use.  If there *is* a next exception, it is the one reported by the driver during acquisition.

**Comment by bturner** [comment]
A `SQLTransientConnectionException` is also thrown without a cause [here](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/pool/PoolBase.java#L378).

It still feels like a brittle approach, built around the assumption that HikariCP will _never_ throw a `SQLTransientConnectionException` without a cause exception for any other reason, especially given that it _already does_, compared to having an explicit type. But I guess it can be argued that even if an explicit type was added, it could always get thrown for another reason. I don't know. It seems a bit short-sighted to me, all to avoid adding a specific subclass.

**Comment by brettwooldridge** [comment]
Unlike other pools, HikariCP goes out of its way to avoid "pool lock-in".  We believe that the user should be able to switch pools without any code change.

The code cited protects against a case we have never actually encountered, and would be a violation of the spec. -- the driver should either return a Connection or throw an exception, but never return null.

If we were to throw a subclass unique to HikariCP, and the user switched to another pool, at runtime they would encounter a ClassNotFoundException without the HikariCP jar present.

**Comment by bturner** [comment]
Only if they're _handling_ that exception. Anyone using HikariCP would have the option of ignoring the library-specific exception and simply handling its standard base type. But a consumer who _cares_ about the difference would have the choice to accept a little lock-in in return for a richer exception model and the ability to handle specific cases according to their needs. I'm sorry, but I just don't see a downside for anyone. The new exception would be completely invisible to anyone who didn't need it.

**Comment by brettwooldridge** [comment]
@bturner Re-reading your original text, I think there is a fundamental misunderstanding.

> When HikariPool times out acquiring a connection, it calls createTimeoutException, which returns a SQLTransientConnectionException that indicates acquiring a connection timed out in its message. That makes trying to apply handling for timeouts difficult and brittle, **_because the only thing I can do is parse the exception message to detect timeouts._**

The **only** exception the pool *ever* throws from ``getConnection()`` *is* a timeout exception.  There is nothing to detect.  If ``getConnection()`` throws an exception, it is because the timeout was reached without a connection becoming available in the pool.

From the perspective of the pool, *every* exception thrown from ``getConnection()`` is transient -- hence ``SQLTransientConnectionException``.

> This indicates that the connection operation that failed might be able to succeed if the operation is retried without any application-level changes.

It is up to the application to decide whether to retry, and if so, how many times before giving up.

In a standard HikariCP pool, operating as a fixed-size pool, Connections are only renewed roughly every 30 minutes.  It is only during a very short window of time that ``getNextException()`` might return anything other than ``null``.

Even when a next exception is reported, it is merely informational.  This is because connection acquisition is asynchronous with respect to calls to ``getConnection()``, and occurs even in the absence of application demand.  Because of this, if Thread A times out, it may not contain a next exception, whereas Thread B might, even if the acquisition was initiated *before* Thread A called ``getConnection()`` -- merely depending on the timing of the acquisition.

An exception at the driver level is never directly attributable to a call to ``getConnection()`` by either Thread A or Thread B.

A call to ``getConnection()`` can be satisfied by either a connection returning to the pool or, rarely, by a connecting being added to the pool.  Either way, it is equally valid to attribute the timeout to lack of return as it is lack of acquisition.  The application should not try to distinguish between the two, because the remedy available to the application is the same -- retry the operation (or not).  In retrying the operation, the thread is equally likely to have its request satisfied by a connection returned to the pool as it is by the addition of a connection to the pool.

**Comment by bturner** [comment]
Okay, I'll buy that.

For what it's worth, I _did_ understand the separation between the two, and that it's a "timeout" either way. _Whether right or wrong_, I guess I was looking at it a little differently. (The difference _very well may not matter_, to be clear; I'm just trying to better elucidate my point.)

Take these 2 specific situations where timeouts can happen:
* The pool has less-than-max connections (which, for a fail-slow pool may be 0). An attempt to acquire a connection triggers the pool to try to add a connection, but it can't due to a driver-level failure (Socket issue, whatever).
* The pool is _full_, with all connections active, and a connection was not returned to the pool quickly enough to satisfy the request before it timed out

It very well could be considered an arbitrary difference, but it's the difference between these two that I'm interested in. As you say, with how the last connection is implemented (which, to be clear, I'm neither saying nor even _implying_ is "wrong"), you can't really read much into its presence or absence. Either way, acquiring a connection from the pool timed out.

When a connection cannot be acquired, the exception (with all its `next` and `cause` exceptions) is logged. So troubleshooting cases arising from driver-level issues (a strangely common one is that the database server went on break) is fairly easy, in that all the data we need tends to be in the logs already.

But when the pool is _full_, and the database is working well, and we can't get a connection, that's "hard" to troubleshoot because a key piece of data is missing: What were all the threads that had connections doing that took so long?

Anyway, reconsidering this from the _library's_ perspective, the difference between the two is most likely not "your" (the library's) problem. I'll solve it from my own end. (I know how many connections the pool is allowed to have, and I know how many are in use, so based on that I also know when it has none left.)

**Comment by brettwooldridge** [comment]
@bturner We're on the same page.  I definitely understand the "timeout when full" scenario, distinct from the less-than-max connections.

As you say, by tracking the connections yourself, or by calling the JMX pool bean to get the active/total count, you can likely attribute the cause of the timeout with a *fairly* high degree of confidence.  If using the JMX bean, due to the temporal separation (however few microseconds) between the catch of the exception and the interogation of the pool counts, the attribution can never be 100% certain.  If tracking the counts yourself, you might be able to achive a higher degree of certainty (if it matters).
