### ISSUE TITLE
Transactional active connections

### ISSUE THREAD

**Issue by spbsti** [brettwooldridge/HikariCP#965]
#### Environment
```
HikariCP version: 2.6.3
JDK version     : 1.8.0_111
Database        : PostgreSQL
Driver version  : 42.1.4
```
-----------------------------------------------------------------------------------------

Hello,

I have Spring application. How can I limit access to database to only 1 active connection within transaction? Please help.

```java
@Transactional(rollbackFor = Exception.class)
public void setNextKey(Object object) {
        Key key = db.getNextKey(object); //select max(key)+1 from objects
        object.setKey(key);
        entityManager.merge(object);
        entityManager.flush();
}
```

**Comment by nunnr** [comment]
Hi, I hope I understand your intention: Take the highest numeric value in the "key" column, add 1, set the incremented value into a row. I think you are trying to avoid concurrency problems where two threads calculate the same new value simultaneously. ...Please correct me if I'm wrong! Here goes...

Firstly, I guess you are asking via HikariCP ticket because one possibility is to limit connection pool size to 1. As long as this application is the only thing accessing the database this would work, but... Don't do this! It would mean every database querying thread across your application would queue. Performance would likely be terrible due to serialised access bottleneck.

Secondly, to answer your question directly, seeing you are hinting at a code solution for that transaction-wrapped method, you could add the Java keyword "synchronized" to the method:

public synchronized void setNextKey(Object object) {

...but don't do this! If this is the only place the increment logic happens, it would be safe, but can you make that guarantee? Also, it's still an unnecessary bottleneck, considering the serialised code section is in the application (therefore including app time, OS time, network time, etc.), when you actually want to serialise database work only.

Thirdly - I think this is what you want - you could look at using a database Sequence. An SQL sequence is an auto-generated number facility, with incrementation built in. It's in the database, so it's useable in an ACID operation. E.g. INSERT INTO objects (key) SELECT nextval(seq)

You can then ensure safety for this application and any other. You also get the best performance, as the database is allowed to manage the data itself.

PostgreSQL supports this, and you can use Hibernate to set it up (assuming your project uses Hibernate as entity manager). Take a look at the @SequenceGenerator annotation, here's a guide http://www.logicbig.com/tutorials/java-ee-tutorial/jpa/seq-generator/

Create sequence SQL syntax:
https://www.postgresql.org/docs/9.5/static/sql-createsequence.html

SQL sequence usage syntax:
https://www.postgresql.org/docs/9.5/static/functions-sequence.html

**Comment by brettwooldridge** [comment]
@nunnr Thanks for jumping in!  I couldn't have written a better answer.
