### ISSUE TITLE
Running connection not timing out

### ISSUE THREAD

**Issue by sachin681** [brettwooldridge/HikariCP#986]
#### Environment
```
HikariCP version: x.x.x
JDK version     : 1.7.0_79
Database        : Oracle|...
Driver version  : 11.0
```

Hi Team,

I am using hikari cp 2.4.11 version. Here is my usecase:
- I am intending to see a timeout which never happens.
- I login to my oracle DB via TOAD and run a update on one particular record, but did not commit it yet.
- Now i run my java application using Hikari Pool , this application also tries to update the same record
- Since the record is locked via my TOAD session, my java application keeps waiting almost for infinite time period. 
- Where in what we expect is it should fail after certain time duration which timeout exception, which is not happening.
- Here are the different properties i have set hoping to get exception after time duration.
   - maxLiifeTime - 30 seconds
   - IdleTimeout - 60 seconds
   - validationTimeout - 20 seconds

Can you please suggest how can this be achieved?

Thanks
Sachin
 
-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking [stackoverflow](https://stackoverflow.com/search?q=HikariCP)?*

**Comment by brettwooldridge** [comment]
HikariCP will never timeout a transaction in-progress.

The idleTimeout obviously does not apply in this case; it only applies to connections sitting idle *in the pool*.

The maxLifetime timeout *will* fire, but because the connection is *in-use* it will only be *marked* for eviction and will not be retired *until it returns* to the pool.

You either need to set a timeout on the Statement itself, or configure a transaction timeout in the database.
