### ISSUE TITLE
Connection.setNetworkTimeout cannot be called on a closed connection

### ISSUE THREAD

**Issue by mani76** [brettwooldridge/HikariCP#993]
#### Environment
```
HikariCP version: 2.7.2
JDK version     : 1.8.0_111
Database        : MariaDB
Driver version  : 2.1.2
```
-----------------------------------------------------------------------------------------

Hello,

When upgraded Hikari CP from older version I am getting following exception after some idle time:

WARN: PoolBase:183 - connection pool - Failed to validate connection org.mariadb.jdbc.MariaDbConnection@7144a01f (Connection.setNetworkTimeout cannot be called on a closed connection)

This seems to be caused by the isConnectionAlive() method in the PoolBase class.
In the latest version setNetworkTimeout(connection, validationTimeout) is called even if jdbc4 connection validation is used. That is causing exception because network timeout can not be set to the closed connection.

Previously connection validation was done before the setNetworkTime() call.

See commit id 9e9a97508ca12d00dbe7b016f3912d01b096eea5

**Comment by brettwooldridge** [comment]
This change was intentional.  Some drivers merely execute a query as the implementation of *isValid()*, which leaves them vulnerable to a network partition event unless a socket-level timeout is in place.  With respect to connection validation, the result is the same.  If the connection is closed, the validation is going to fail anyway.

The larger question is, why is the connection closed and yet still in the pool to begin with?  One possibility is the maxLifetime setting in the pool is lower than that of the database.
